// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/action_workspace.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GitLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commit        string                 `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Author        *GitLog_Authoring      `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Committer     *GitLog_Authoring      `protobuf:"bytes,5,opt,name=committer,proto3" json:"committer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitLog) Reset() {
	*x = GitLog{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitLog) ProtoMessage() {}

func (x *GitLog) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitLog.ProtoReflect.Descriptor instead.
func (*GitLog) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *GitLog) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GitLog) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GitLog) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *GitLog) GetAuthor() *GitLog_Authoring {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *GitLog) GetCommitter() *GitLog_Authoring {
	if x != nil {
		return x.Committer
	}
	return nil
}

// Information about the checked-out repo in the workspace.
type WorkspaceRepo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path of the checkout relative to the home directory of the user.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The manifest loaded from the repo, maybe empty.
	Manifest *Repo_Manifest `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	// The processes defined in the manifest.
	Processes []*Process `protobuf:"bytes,3,rep,name=processes,proto3" json:"processes,omitempty"`
	// Current branch. This can be empty if in "detached HEAD" state (e.g. AUTO workspace).
	Branch string `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	// The most recent git commit.
	LastCommit *GitLog `protobuf:"bytes,5,opt,name=last_commit,json=lastCommit,proto3" json:"last_commit,omitempty"`
	// If any uncommitted changes.
	UncommittedChanges bool `protobuf:"varint,6,opt,name=uncommitted_changes,json=uncommittedChanges,proto3" json:"uncommitted_changes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkspaceRepo) Reset() {
	*x = WorkspaceRepo{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceRepo) ProtoMessage() {}

func (x *WorkspaceRepo) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceRepo.ProtoReflect.Descriptor instead.
func (*WorkspaceRepo) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *WorkspaceRepo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkspaceRepo) GetManifest() *Repo_Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *WorkspaceRepo) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *WorkspaceRepo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *WorkspaceRepo) GetLastCommit() *GitLog {
	if x != nil {
		return x.LastCommit
	}
	return nil
}

func (x *WorkspaceRepo) GetUncommittedChanges() bool {
	if x != nil {
		return x.UncommittedChanges
	}
	return false
}

// Fetch the information of all checked out repos.
type FetchReposAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchReposAction) Reset() {
	*x = FetchReposAction{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchReposAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReposAction) ProtoMessage() {}

func (x *FetchReposAction) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReposAction.ProtoReflect.Descriptor instead.
func (*FetchReposAction) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{2}
}

// EnableProcessesAction enables or disables processed defined in repo manifest.
type EnableProcessesAction struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Types that are valid to be assigned to Processes:
	//
	//	*EnableProcessesAction_Specific
	//	*EnableProcessesAction_All
	Processes     isEnableProcessesAction_Processes `protobuf_oneof:"processes"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableProcessesAction) Reset() {
	*x = EnableProcessesAction{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableProcessesAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableProcessesAction) ProtoMessage() {}

func (x *EnableProcessesAction) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableProcessesAction.ProtoReflect.Descriptor instead.
func (*EnableProcessesAction) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *EnableProcessesAction) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EnableProcessesAction) GetProcesses() isEnableProcessesAction_Processes {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *EnableProcessesAction) GetSpecific() *EnableProcessesAction_SpecificProcesses {
	if x != nil {
		if x, ok := x.Processes.(*EnableProcessesAction_Specific); ok {
			return x.Specific
		}
	}
	return nil
}

func (x *EnableProcessesAction) GetAll() *EnableProcessesAction_AllProcesses {
	if x != nil {
		if x, ok := x.Processes.(*EnableProcessesAction_All); ok {
			return x.All
		}
	}
	return nil
}

type isEnableProcessesAction_Processes interface {
	isEnableProcessesAction_Processes()
}

type EnableProcessesAction_Specific struct {
	// Only enable/disable the specified processes.
	Specific *EnableProcessesAction_SpecificProcesses `protobuf:"bytes,2,opt,name=specific,proto3,oneof"`
}

type EnableProcessesAction_All struct {
	// Enable/disable all the processes matching the specified kinds.
	All *EnableProcessesAction_AllProcesses `protobuf:"bytes,3,opt,name=all,proto3,oneof"`
}

func (*EnableProcessesAction_Specific) isEnableProcessesAction_Processes() {}

func (*EnableProcessesAction_All) isEnableProcessesAction_Processes() {}

// Fetch or generate home snapshot white/black lists.
type PrepareHomeSnapshotAction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GenerateIfAbsent bool                   `protobuf:"varint,1,opt,name=generate_if_absent,json=generateIfAbsent,proto3" json:"generate_if_absent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrepareHomeSnapshotAction) Reset() {
	*x = PrepareHomeSnapshotAction{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareHomeSnapshotAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareHomeSnapshotAction) ProtoMessage() {}

func (x *PrepareHomeSnapshotAction) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareHomeSnapshotAction.ProtoReflect.Descriptor instead.
func (*PrepareHomeSnapshotAction) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareHomeSnapshotAction) GetGenerateIfAbsent() bool {
	if x != nil {
		return x.GenerateIfAbsent
	}
	return false
}

// Run test commands in the specified repo.
type RunRepoTestAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	TestName      string                 `protobuf:"bytes,2,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRepoTestAction) Reset() {
	*x = RunRepoTestAction{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRepoTestAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRepoTestAction) ProtoMessage() {}

func (x *RunRepoTestAction) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRepoTestAction.ProtoReflect.Descriptor instead.
func (*RunRepoTestAction) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *RunRepoTestAction) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *RunRepoTestAction) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

// Fetch results of test commands in the specified repo.
type FetchRepoTestResultAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	TestName      string                 `protobuf:"bytes,2,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRepoTestResultAction) Reset() {
	*x = FetchRepoTestResultAction{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRepoTestResultAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRepoTestResultAction) ProtoMessage() {}

func (x *FetchRepoTestResultAction) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRepoTestResultAction.ProtoReflect.Descriptor instead.
func (*FetchRepoTestResultAction) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *FetchRepoTestResultAction) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *FetchRepoTestResultAction) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

// Request a certificate for connecting to a workspace.
type ConnectAuthorizeAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Csr           string                 `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectAuthorizeAction) Reset() {
	*x = ConnectAuthorizeAction{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectAuthorizeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAuthorizeAction) ProtoMessage() {}

func (x *ConnectAuthorizeAction) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAuthorizeAction.ProtoReflect.Descriptor instead.
func (*ConnectAuthorizeAction) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectAuthorizeAction) GetCsr() string {
	if x != nil {
		return x.Csr
	}
	return ""
}

type DisableRestriction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRestriction) Reset() {
	*x = DisableRestriction{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRestriction) ProtoMessage() {}

func (x *DisableRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRestriction.ProtoReflect.Descriptor instead.
func (*DisableRestriction) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{8}
}

type GitLog_Authoring struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitLog_Authoring) Reset() {
	*x = GitLog_Authoring{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitLog_Authoring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitLog_Authoring) ProtoMessage() {}

func (x *GitLog_Authoring) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitLog_Authoring.ProtoReflect.Descriptor instead.
func (*GitLog_Authoring) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GitLog_Authoring) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GitLog_Authoring) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GitLog_Authoring) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FetchReposAction_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*WorkspaceRepo       `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchReposAction_Result) Reset() {
	*x = FetchReposAction_Result{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchReposAction_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReposAction_Result) ProtoMessage() {}

func (x *FetchReposAction_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReposAction_Result.ProtoReflect.Descriptor instead.
func (*FetchReposAction_Result) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FetchReposAction_Result) GetRepos() []*WorkspaceRepo {
	if x != nil {
		return x.Repos
	}
	return nil
}

type EnableProcessesAction_SpecificProcesses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessRef          `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableProcessesAction_SpecificProcesses) Reset() {
	*x = EnableProcessesAction_SpecificProcesses{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableProcessesAction_SpecificProcesses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableProcessesAction_SpecificProcesses) ProtoMessage() {}

func (x *EnableProcessesAction_SpecificProcesses) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableProcessesAction_SpecificProcesses.ProtoReflect.Descriptor instead.
func (*EnableProcessesAction_SpecificProcesses) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{3, 0}
}

func (x *EnableProcessesAction_SpecificProcesses) GetProcesses() []*ProcessRef {
	if x != nil {
		return x.Processes
	}
	return nil
}

type EnableProcessesAction_AllProcesses struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kinds []ProcessRef_Kind      `protobuf:"varint,1,rep,packed,name=kinds,proto3,enum=sandboxes.api.v1.ProcessRef_Kind" json:"kinds,omitempty"`
	// If specified with repo paths, only match the processes from the specified repos.
	FromRepos     []string `protobuf:"bytes,2,rep,name=from_repos,json=fromRepos,proto3" json:"from_repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableProcessesAction_AllProcesses) Reset() {
	*x = EnableProcessesAction_AllProcesses{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableProcessesAction_AllProcesses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableProcessesAction_AllProcesses) ProtoMessage() {}

func (x *EnableProcessesAction_AllProcesses) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableProcessesAction_AllProcesses.ProtoReflect.Descriptor instead.
func (*EnableProcessesAction_AllProcesses) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{3, 1}
}

func (x *EnableProcessesAction_AllProcesses) GetKinds() []ProcessRef_Kind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *EnableProcessesAction_AllProcesses) GetFromRepos() []string {
	if x != nil {
		return x.FromRepos
	}
	return nil
}

type EnableProcessesAction_Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of updated processes. If error happens, it will be set in the
	// corresponding ProcessResult.
	Processes     []*EnableProcessesAction_Result_ProcessResult `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableProcessesAction_Result) Reset() {
	*x = EnableProcessesAction_Result{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableProcessesAction_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableProcessesAction_Result) ProtoMessage() {}

func (x *EnableProcessesAction_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableProcessesAction_Result.ProtoReflect.Descriptor instead.
func (*EnableProcessesAction_Result) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{3, 2}
}

func (x *EnableProcessesAction_Result) GetProcesses() []*EnableProcessesAction_Result_ProcessResult {
	if x != nil {
		return x.Processes
	}
	return nil
}

type EnableProcessesAction_Result_ProcessResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       *Process               `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableProcessesAction_Result_ProcessResult) Reset() {
	*x = EnableProcessesAction_Result_ProcessResult{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableProcessesAction_Result_ProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableProcessesAction_Result_ProcessResult) ProtoMessage() {}

func (x *EnableProcessesAction_Result_ProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableProcessesAction_Result_ProcessResult.ProtoReflect.Descriptor instead.
func (*EnableProcessesAction_Result_ProcessResult) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{3, 2, 0}
}

func (x *EnableProcessesAction_Result_ProcessResult) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *EnableProcessesAction_Result_ProcessResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type PrepareHomeSnapshotAction_Result struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Includes          []string               `protobuf:"bytes,1,rep,name=includes,proto3" json:"includes,omitempty"`
	Excludes          []string               `protobuf:"bytes,2,rep,name=excludes,proto3" json:"excludes,omitempty"`
	GeneratedIncludes bool                   `protobuf:"varint,3,opt,name=generated_includes,json=generatedIncludes,proto3" json:"generated_includes,omitempty"`
	GeneratedExcludes bool                   `protobuf:"varint,4,opt,name=generated_excludes,json=generatedExcludes,proto3" json:"generated_excludes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrepareHomeSnapshotAction_Result) Reset() {
	*x = PrepareHomeSnapshotAction_Result{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareHomeSnapshotAction_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareHomeSnapshotAction_Result) ProtoMessage() {}

func (x *PrepareHomeSnapshotAction_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareHomeSnapshotAction_Result.ProtoReflect.Descriptor instead.
func (*PrepareHomeSnapshotAction_Result) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{4, 0}
}

func (x *PrepareHomeSnapshotAction_Result) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

func (x *PrepareHomeSnapshotAction_Result) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

func (x *PrepareHomeSnapshotAction_Result) GetGeneratedIncludes() bool {
	if x != nil {
		return x.GeneratedIncludes
	}
	return false
}

func (x *PrepareHomeSnapshotAction_Result) GetGeneratedExcludes() bool {
	if x != nil {
		return x.GeneratedExcludes
	}
	return false
}

type RunRepoTestAction_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRepoTestAction_Result) Reset() {
	*x = RunRepoTestAction_Result{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRepoTestAction_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRepoTestAction_Result) ProtoMessage() {}

func (x *RunRepoTestAction_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRepoTestAction_Result.ProtoReflect.Descriptor instead.
func (*RunRepoTestAction_Result) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RunRepoTestAction_Result) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type FetchRepoTestResultAction_Result struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Found               bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	IsLastRunSuccessful bool                   `protobuf:"varint,2,opt,name=is_last_run_successful,json=isLastRunSuccessful,proto3" json:"is_last_run_successful,omitempty"`
	Result              string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	ResultType          string                 `protobuf:"bytes,4,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FetchRepoTestResultAction_Result) Reset() {
	*x = FetchRepoTestResultAction_Result{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRepoTestResultAction_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRepoTestResultAction_Result) ProtoMessage() {}

func (x *FetchRepoTestResultAction_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRepoTestResultAction_Result.ProtoReflect.Descriptor instead.
func (*FetchRepoTestResultAction_Result) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{6, 0}
}

func (x *FetchRepoTestResultAction_Result) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FetchRepoTestResultAction_Result) GetIsLastRunSuccessful() bool {
	if x != nil {
		return x.IsLastRunSuccessful
	}
	return false
}

func (x *FetchRepoTestResultAction_Result) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *FetchRepoTestResultAction_Result) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

type ConnectAuthorizeAction_Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Issued certificate in PEM.
	Certificate string `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// CA certificate for workspace access, in PEM.
	Ca string `protobuf:"bytes,2,opt,name=ca,proto3" json:"ca,omitempty"`
	// The server name used for TLS handshake.
	ServerName string `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// The FQDN of the endpoint to access the workspace.
	Endpoint      string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectAuthorizeAction_Result) Reset() {
	*x = ConnectAuthorizeAction_Result{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectAuthorizeAction_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAuthorizeAction_Result) ProtoMessage() {}

func (x *ConnectAuthorizeAction_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAuthorizeAction_Result.ProtoReflect.Descriptor instead.
func (*ConnectAuthorizeAction_Result) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ConnectAuthorizeAction_Result) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *ConnectAuthorizeAction_Result) GetCa() string {
	if x != nil {
		return x.Ca
	}
	return ""
}

func (x *ConnectAuthorizeAction_Result) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ConnectAuthorizeAction_Result) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type DisableRestriction_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRestriction_Result) Reset() {
	*x = DisableRestriction_Result{}
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRestriction_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRestriction_Result) ProtoMessage() {}

func (x *DisableRestriction_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_workspace_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRestriction_Result.ProtoReflect.Descriptor instead.
func (*DisableRestriction_Result) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP(), []int{8, 0}
}

var File_sandboxes_api_v1_action_workspace_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_action_workspace_proto_rawDesc = "" +
	"\n" +
	"'sandboxes/api/v1/action_workspace.proto\x12\x10sandboxes.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dsandboxes/api/v1/common.proto\x1a\x1esandboxes/api/v1/process.proto\x1a\x1bsandboxes/api/v1/repo.proto\x1a\x1fsandboxes/api/v1/workload.proto\"\xb3\x02\n" +
	"\x06GitLog\x12\x16\n" +
	"\x06commit\x18\x01 \x01(\tR\x06commit\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12:\n" +
	"\x06author\x18\x04 \x01(\v2\".sandboxes.api.v1.GitLog.AuthoringR\x06author\x12@\n" +
	"\tcommitter\x18\x05 \x01(\v2\".sandboxes.api.v1.GitLog.AuthoringR\tcommitter\x1ae\n" +
	"\tAuthoring\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x9d\x02\n" +
	"\rWorkspaceRepo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12;\n" +
	"\bmanifest\x18\x02 \x01(\v2\x1f.sandboxes.api.v1.Repo.ManifestR\bmanifest\x127\n" +
	"\tprocesses\x18\x03 \x03(\v2\x19.sandboxes.api.v1.ProcessR\tprocesses\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\x129\n" +
	"\vlast_commit\x18\x05 \x01(\v2\x18.sandboxes.api.v1.GitLogR\n" +
	"lastCommit\x12/\n" +
	"\x13uncommitted_changes\x18\x06 \x01(\bR\x12uncommittedChanges\"S\n" +
	"\x10FetchReposAction\x1a?\n" +
	"\x06Result\x125\n" +
	"\x05repos\x18\x01 \x03(\v2\x1f.sandboxes.api.v1.WorkspaceRepoR\x05repos\"\xf6\x04\n" +
	"\x15EnableProcessesAction\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12W\n" +
	"\bspecific\x18\x02 \x01(\v29.sandboxes.api.v1.EnableProcessesAction.SpecificProcessesH\x00R\bspecific\x12H\n" +
	"\x03all\x18\x03 \x01(\v24.sandboxes.api.v1.EnableProcessesAction.AllProcessesH\x00R\x03all\x1aO\n" +
	"\x11SpecificProcesses\x12:\n" +
	"\tprocesses\x18\x01 \x03(\v2\x1c.sandboxes.api.v1.ProcessRefR\tprocesses\x1af\n" +
	"\fAllProcesses\x127\n" +
	"\x05kinds\x18\x01 \x03(\x0e2!.sandboxes.api.v1.ProcessRef.KindR\x05kinds\x12\x1d\n" +
	"\n" +
	"from_repos\x18\x02 \x03(\tR\tfromRepos\x1a\xd9\x01\n" +
	"\x06Result\x12Z\n" +
	"\tprocesses\x18\x01 \x03(\v2<.sandboxes.api.v1.EnableProcessesAction.Result.ProcessResultR\tprocesses\x1as\n" +
	"\rProcessResult\x123\n" +
	"\aprocess\x18\x01 \x01(\v2\x19.sandboxes.api.v1.ProcessR\aprocess\x12-\n" +
	"\x05error\x18\x02 \x01(\v2\x17.sandboxes.api.v1.ErrorR\x05errorB\v\n" +
	"\tprocesses\"\xea\x01\n" +
	"\x19PrepareHomeSnapshotAction\x12,\n" +
	"\x12generate_if_absent\x18\x01 \x01(\bR\x10generateIfAbsent\x1a\x9e\x01\n" +
	"\x06Result\x12\x1a\n" +
	"\bincludes\x18\x01 \x03(\tR\bincludes\x12\x1a\n" +
	"\bexcludes\x18\x02 \x03(\tR\bexcludes\x12-\n" +
	"\x12generated_includes\x18\x03 \x01(\bR\x11generatedIncludes\x12-\n" +
	"\x12generated_excludes\x18\x04 \x01(\bR\x11generatedExcludes\"p\n" +
	"\x11RunRepoTestAction\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x1b\n" +
	"\ttest_name\x18\x02 \x01(\tR\btestName\x1a!\n" +
	"\x06Result\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xe4\x01\n" +
	"\x19FetchRepoTestResultAction\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x1b\n" +
	"\ttest_name\x18\x02 \x01(\tR\btestName\x1a\x8c\x01\n" +
	"\x06Result\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x123\n" +
	"\x16is_last_run_successful\x18\x02 \x01(\bR\x13isLastRunSuccessful\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x1f\n" +
	"\vresult_type\x18\x04 \x01(\tR\n" +
	"resultType\"\xa3\x01\n" +
	"\x16ConnectAuthorizeAction\x12\x10\n" +
	"\x03csr\x18\x01 \x01(\tR\x03csr\x1aw\n" +
	"\x06Result\x12 \n" +
	"\vcertificate\x18\x01 \x01(\tR\vcertificate\x12\x0e\n" +
	"\x02ca\x18\x02 \x01(\tR\x02ca\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\"\x1e\n" +
	"\x12DisableRestriction\x1a\b\n" +
	"\x06ResultB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_action_workspace_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_action_workspace_proto_rawDescData []byte
)

func file_sandboxes_api_v1_action_workspace_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_action_workspace_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_action_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_action_workspace_proto_rawDesc), len(file_sandboxes_api_v1_action_workspace_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_action_workspace_proto_rawDescData
}

var file_sandboxes_api_v1_action_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_sandboxes_api_v1_action_workspace_proto_goTypes = []any{
	(*GitLog)(nil),                                     // 0: sandboxes.api.v1.GitLog
	(*WorkspaceRepo)(nil),                              // 1: sandboxes.api.v1.WorkspaceRepo
	(*FetchReposAction)(nil),                           // 2: sandboxes.api.v1.FetchReposAction
	(*EnableProcessesAction)(nil),                      // 3: sandboxes.api.v1.EnableProcessesAction
	(*PrepareHomeSnapshotAction)(nil),                  // 4: sandboxes.api.v1.PrepareHomeSnapshotAction
	(*RunRepoTestAction)(nil),                          // 5: sandboxes.api.v1.RunRepoTestAction
	(*FetchRepoTestResultAction)(nil),                  // 6: sandboxes.api.v1.FetchRepoTestResultAction
	(*ConnectAuthorizeAction)(nil),                     // 7: sandboxes.api.v1.ConnectAuthorizeAction
	(*DisableRestriction)(nil),                         // 8: sandboxes.api.v1.DisableRestriction
	(*GitLog_Authoring)(nil),                           // 9: sandboxes.api.v1.GitLog.Authoring
	(*FetchReposAction_Result)(nil),                    // 10: sandboxes.api.v1.FetchReposAction.Result
	(*EnableProcessesAction_SpecificProcesses)(nil),    // 11: sandboxes.api.v1.EnableProcessesAction.SpecificProcesses
	(*EnableProcessesAction_AllProcesses)(nil),         // 12: sandboxes.api.v1.EnableProcessesAction.AllProcesses
	(*EnableProcessesAction_Result)(nil),               // 13: sandboxes.api.v1.EnableProcessesAction.Result
	(*EnableProcessesAction_Result_ProcessResult)(nil), // 14: sandboxes.api.v1.EnableProcessesAction.Result.ProcessResult
	(*PrepareHomeSnapshotAction_Result)(nil),           // 15: sandboxes.api.v1.PrepareHomeSnapshotAction.Result
	(*RunRepoTestAction_Result)(nil),                   // 16: sandboxes.api.v1.RunRepoTestAction.Result
	(*FetchRepoTestResultAction_Result)(nil),           // 17: sandboxes.api.v1.FetchRepoTestResultAction.Result
	(*ConnectAuthorizeAction_Result)(nil),              // 18: sandboxes.api.v1.ConnectAuthorizeAction.Result
	(*DisableRestriction_Result)(nil),                  // 19: sandboxes.api.v1.DisableRestriction.Result
	(*Repo_Manifest)(nil),                              // 20: sandboxes.api.v1.Repo.Manifest
	(*Process)(nil),                                    // 21: sandboxes.api.v1.Process
	(*timestamppb.Timestamp)(nil),                      // 22: google.protobuf.Timestamp
	(*ProcessRef)(nil),                                 // 23: sandboxes.api.v1.ProcessRef
	(ProcessRef_Kind)(0),                               // 24: sandboxes.api.v1.ProcessRef.Kind
	(*Error)(nil),                                      // 25: sandboxes.api.v1.Error
}
var file_sandboxes_api_v1_action_workspace_proto_depIdxs = []int32{
	9,  // 0: sandboxes.api.v1.GitLog.author:type_name -> sandboxes.api.v1.GitLog.Authoring
	9,  // 1: sandboxes.api.v1.GitLog.committer:type_name -> sandboxes.api.v1.GitLog.Authoring
	20, // 2: sandboxes.api.v1.WorkspaceRepo.manifest:type_name -> sandboxes.api.v1.Repo.Manifest
	21, // 3: sandboxes.api.v1.WorkspaceRepo.processes:type_name -> sandboxes.api.v1.Process
	0,  // 4: sandboxes.api.v1.WorkspaceRepo.last_commit:type_name -> sandboxes.api.v1.GitLog
	11, // 5: sandboxes.api.v1.EnableProcessesAction.specific:type_name -> sandboxes.api.v1.EnableProcessesAction.SpecificProcesses
	12, // 6: sandboxes.api.v1.EnableProcessesAction.all:type_name -> sandboxes.api.v1.EnableProcessesAction.AllProcesses
	22, // 7: sandboxes.api.v1.GitLog.Authoring.time:type_name -> google.protobuf.Timestamp
	1,  // 8: sandboxes.api.v1.FetchReposAction.Result.repos:type_name -> sandboxes.api.v1.WorkspaceRepo
	23, // 9: sandboxes.api.v1.EnableProcessesAction.SpecificProcesses.processes:type_name -> sandboxes.api.v1.ProcessRef
	24, // 10: sandboxes.api.v1.EnableProcessesAction.AllProcesses.kinds:type_name -> sandboxes.api.v1.ProcessRef.Kind
	14, // 11: sandboxes.api.v1.EnableProcessesAction.Result.processes:type_name -> sandboxes.api.v1.EnableProcessesAction.Result.ProcessResult
	21, // 12: sandboxes.api.v1.EnableProcessesAction.Result.ProcessResult.process:type_name -> sandboxes.api.v1.Process
	25, // 13: sandboxes.api.v1.EnableProcessesAction.Result.ProcessResult.error:type_name -> sandboxes.api.v1.Error
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_action_workspace_proto_init() }
func file_sandboxes_api_v1_action_workspace_proto_init() {
	if File_sandboxes_api_v1_action_workspace_proto != nil {
		return
	}
	file_sandboxes_api_v1_common_proto_init()
	file_sandboxes_api_v1_process_proto_init()
	file_sandboxes_api_v1_repo_proto_init()
	file_sandboxes_api_v1_workload_proto_init()
	file_sandboxes_api_v1_action_workspace_proto_msgTypes[3].OneofWrappers = []any{
		(*EnableProcessesAction_Specific)(nil),
		(*EnableProcessesAction_All)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_action_workspace_proto_rawDesc), len(file_sandboxes_api_v1_action_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_action_workspace_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_action_workspace_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_action_workspace_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_action_workspace_proto = out.File
	file_sandboxes_api_v1_action_workspace_proto_goTypes = nil
	file_sandboxes_api_v1_action_workspace_proto_depIdxs = nil
}
