// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/action_generic.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Restart the current workload.
// The operation stops the current running processes, containers, cleans up
// resources like mountpoints etc, and starts the L2 agent again.
// Persisted data is preserved.
// This action can be applied to workspaces, dependencies and containers.
type RestartWorkloadAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartWorkloadAction) Reset() {
	*x = RestartWorkloadAction{}
	mi := &file_sandboxes_api_v1_action_generic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartWorkloadAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartWorkloadAction) ProtoMessage() {}

func (x *RestartWorkloadAction) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_generic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartWorkloadAction.ProtoReflect.Descriptor instead.
func (*RestartWorkloadAction) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_generic_proto_rawDescGZIP(), []int{0}
}

type RestartWorkloadAction_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartWorkloadAction_Result) Reset() {
	*x = RestartWorkloadAction_Result{}
	mi := &file_sandboxes_api_v1_action_generic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartWorkloadAction_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartWorkloadAction_Result) ProtoMessage() {}

func (x *RestartWorkloadAction_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_action_generic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartWorkloadAction_Result.ProtoReflect.Descriptor instead.
func (*RestartWorkloadAction_Result) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_action_generic_proto_rawDescGZIP(), []int{0, 0}
}

var File_sandboxes_api_v1_action_generic_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_action_generic_proto_rawDesc = "" +
	"\n" +
	"%sandboxes/api/v1/action_generic.proto\x12\x10sandboxes.api.v1\"!\n" +
	"\x15RestartWorkloadAction\x1a\b\n" +
	"\x06ResultB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_action_generic_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_action_generic_proto_rawDescData []byte
)

func file_sandboxes_api_v1_action_generic_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_action_generic_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_action_generic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_action_generic_proto_rawDesc), len(file_sandboxes_api_v1_action_generic_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_action_generic_proto_rawDescData
}

var file_sandboxes_api_v1_action_generic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sandboxes_api_v1_action_generic_proto_goTypes = []any{
	(*RestartWorkloadAction)(nil),        // 0: sandboxes.api.v1.RestartWorkloadAction
	(*RestartWorkloadAction_Result)(nil), // 1: sandboxes.api.v1.RestartWorkloadAction.Result
}
var file_sandboxes_api_v1_action_generic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_action_generic_proto_init() }
func file_sandboxes_api_v1_action_generic_proto_init() {
	if File_sandboxes_api_v1_action_generic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_action_generic_proto_rawDesc), len(file_sandboxes_api_v1_action_generic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_action_generic_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_action_generic_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_action_generic_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_action_generic_proto = out.File
	file_sandboxes_api_v1_action_generic_proto_goTypes = nil
	file_sandboxes_api_v1_action_generic_proto_depIdxs = nil
}
