// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/infoservice.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Brief inforrmation about a sandbox.
type SandboxInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Composer      *SandboxInfo_Composer   `protobuf:"bytes,2,opt,name=composer,proto3" json:"composer,omitempty"`
	Endpoints     []*SandboxInfo_Endpoint `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	mi := &file_sandboxes_api_v1_infoservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_infoservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_infoservice_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SandboxInfo) GetComposer() *SandboxInfo_Composer {
	if x != nil {
		return x.Composer
	}
	return nil
}

func (x *SandboxInfo) GetEndpoints() []*SandboxInfo_Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type ListSandboxInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the org.
	Org           string `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxInfoRequest) Reset() {
	*x = ListSandboxInfoRequest{}
	mi := &file_sandboxes_api_v1_infoservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxInfoRequest) ProtoMessage() {}

func (x *ListSandboxInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_infoservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxInfoRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxInfoRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_infoservice_proto_rawDescGZIP(), []int{1}
}

func (x *ListSandboxInfoRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type ListSandboxInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*SandboxInfo         `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxInfoResponse) Reset() {
	*x = ListSandboxInfoResponse{}
	mi := &file_sandboxes_api_v1_infoservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxInfoResponse) ProtoMessage() {}

func (x *ListSandboxInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_infoservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxInfoResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxInfoResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_infoservice_proto_rawDescGZIP(), []int{2}
}

func (x *ListSandboxInfoResponse) GetSandboxes() []*SandboxInfo {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type SandboxInfo_Composer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to From:
	//
	//	*SandboxInfo_Composer_App
	From          isSandboxInfo_Composer_From `protobuf_oneof:"from"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxInfo_Composer) Reset() {
	*x = SandboxInfo_Composer{}
	mi := &file_sandboxes_api_v1_infoservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo_Composer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo_Composer) ProtoMessage() {}

func (x *SandboxInfo_Composer) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_infoservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo_Composer.ProtoReflect.Descriptor instead.
func (*SandboxInfo_Composer) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_infoservice_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SandboxInfo_Composer) GetFrom() isSandboxInfo_Composer_From {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SandboxInfo_Composer) GetApp() string {
	if x != nil {
		if x, ok := x.From.(*SandboxInfo_Composer_App); ok {
			return x.App
		}
	}
	return ""
}

type isSandboxInfo_Composer_From interface {
	isSandboxInfo_Composer_From()
}

type SandboxInfo_Composer_App struct {
	// Name of the app used to compose the sandbox.
	App string `protobuf:"bytes,1,opt,name=app,proto3,oneof"`
}

func (*SandboxInfo_Composer_App) isSandboxInfo_Composer_From() {}

type SandboxInfo_Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fqdn          string                 `protobuf:"bytes,2,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxInfo_Endpoint) Reset() {
	*x = SandboxInfo_Endpoint{}
	mi := &file_sandboxes_api_v1_infoservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo_Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo_Endpoint) ProtoMessage() {}

func (x *SandboxInfo_Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_infoservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo_Endpoint.ProtoReflect.Descriptor instead.
func (*SandboxInfo_Endpoint) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_infoservice_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SandboxInfo_Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SandboxInfo_Endpoint) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

var File_sandboxes_api_v1_infoservice_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_infoservice_proto_rawDesc = "" +
	"\n" +
	"\"sandboxes/api/v1/infoservice.proto\x12\x10sandboxes.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1asandboxes/api/v1/app.proto\x1a\x1asandboxes/api/v1/org.proto\x1a\x1fsandboxes/api/v1/resource.proto\x1a\x1esandboxes/api/v1/sandbox.proto\x1a\x1dsandboxes/api/v1/secret.proto\x1a\x1dsandboxes/api/v1/system.proto\x1a\x1bsandboxes/api/v1/user.proto\"\x87\x02\n" +
	"\vSandboxInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12B\n" +
	"\bcomposer\x18\x02 \x01(\v2&.sandboxes.api.v1.SandboxInfo.ComposerR\bcomposer\x12D\n" +
	"\tendpoints\x18\x03 \x03(\v2&.sandboxes.api.v1.SandboxInfo.EndpointR\tendpoints\x1a&\n" +
	"\bComposer\x12\x12\n" +
	"\x03app\x18\x01 \x01(\tH\x00R\x03appB\x06\n" +
	"\x04from\x1a2\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04fqdn\x18\x02 \x01(\tR\x04fqdn\"*\n" +
	"\x16ListSandboxInfoRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\"V\n" +
	"\x17ListSandboxInfoResponse\x12;\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x1d.sandboxes.api.v1.SandboxInfoR\tsandboxes2\xa4\x01\n" +
	"\x12InformationService\x12\x8d\x01\n" +
	"\x0fListSandboxInfo\x12(.sandboxes.api.v1.ListSandboxInfoRequest\x1a).sandboxes.api.v1.ListSandboxInfoResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/info/orgs/{org}/sandboxesB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_infoservice_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_infoservice_proto_rawDescData []byte
)

func file_sandboxes_api_v1_infoservice_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_infoservice_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_infoservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_infoservice_proto_rawDesc), len(file_sandboxes_api_v1_infoservice_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_infoservice_proto_rawDescData
}

var file_sandboxes_api_v1_infoservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sandboxes_api_v1_infoservice_proto_goTypes = []any{
	(*SandboxInfo)(nil),             // 0: sandboxes.api.v1.SandboxInfo
	(*ListSandboxInfoRequest)(nil),  // 1: sandboxes.api.v1.ListSandboxInfoRequest
	(*ListSandboxInfoResponse)(nil), // 2: sandboxes.api.v1.ListSandboxInfoResponse
	(*SandboxInfo_Composer)(nil),    // 3: sandboxes.api.v1.SandboxInfo.Composer
	(*SandboxInfo_Endpoint)(nil),    // 4: sandboxes.api.v1.SandboxInfo.Endpoint
}
var file_sandboxes_api_v1_infoservice_proto_depIdxs = []int32{
	3, // 0: sandboxes.api.v1.SandboxInfo.composer:type_name -> sandboxes.api.v1.SandboxInfo.Composer
	4, // 1: sandboxes.api.v1.SandboxInfo.endpoints:type_name -> sandboxes.api.v1.SandboxInfo.Endpoint
	0, // 2: sandboxes.api.v1.ListSandboxInfoResponse.sandboxes:type_name -> sandboxes.api.v1.SandboxInfo
	1, // 3: sandboxes.api.v1.InformationService.ListSandboxInfo:input_type -> sandboxes.api.v1.ListSandboxInfoRequest
	2, // 4: sandboxes.api.v1.InformationService.ListSandboxInfo:output_type -> sandboxes.api.v1.ListSandboxInfoResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_infoservice_proto_init() }
func file_sandboxes_api_v1_infoservice_proto_init() {
	if File_sandboxes_api_v1_infoservice_proto != nil {
		return
	}
	file_sandboxes_api_v1_app_proto_init()
	file_sandboxes_api_v1_org_proto_init()
	file_sandboxes_api_v1_resource_proto_init()
	file_sandboxes_api_v1_sandbox_proto_init()
	file_sandboxes_api_v1_secret_proto_init()
	file_sandboxes_api_v1_system_proto_init()
	file_sandboxes_api_v1_user_proto_init()
	file_sandboxes_api_v1_infoservice_proto_msgTypes[3].OneofWrappers = []any{
		(*SandboxInfo_Composer_App)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_infoservice_proto_rawDesc), len(file_sandboxes_api_v1_infoservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandboxes_api_v1_infoservice_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_infoservice_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_infoservice_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_infoservice_proto = out.File
	file_sandboxes_api_v1_infoservice_proto_goTypes = nil
	file_sandboxes_api_v1_infoservice_proto_depIdxs = nil
}
