// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/llmservice.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListLLMSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// The filter applied to the meta.
	MetaFilter *ObjectMetaFilter `protobuf:"bytes,2,opt,name=meta_filter,json=metaFilter,proto3" json:"meta_filter,omitempty"`
	// If specified, pagination will be enabled.
	Page *Pagination_Request `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	// Explicit filter for what sessions to return.
	// If specified, only sessions matching the filter will be returned.
	// Otherwise, all sessions are returned.
	Filter        *ListLLMSessionsRequest_Filter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLLMSessionsRequest) Reset() {
	*x = ListLLMSessionsRequest{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLLMSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLLMSessionsRequest) ProtoMessage() {}

func (x *ListLLMSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLLMSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListLLMSessionsRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{0}
}

func (x *ListLLMSessionsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ListLLMSessionsRequest) GetMetaFilter() *ObjectMetaFilter {
	if x != nil {
		return x.MetaFilter
	}
	return nil
}

func (x *ListLLMSessionsRequest) GetPage() *Pagination_Request {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListLLMSessionsRequest) GetFilter() *ListLLMSessionsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListLLMSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// They are ordered by updated_at, ascending (most recent one comes last).
	// They don't include messages, use QueryLLMSessionMessages for messages.
	Sessions      []*Resource          `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Page          *Pagination_Response `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLLMSessionsResponse) Reset() {
	*x = ListLLMSessionsResponse{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLLMSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLLMSessionsResponse) ProtoMessage() {}

func (x *ListLLMSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLLMSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListLLMSessionsResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{1}
}

func (x *ListLLMSessionsResponse) GetSessions() []*Resource {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListLLMSessionsResponse) GetPage() *Pagination_Response {
	if x != nil {
		return x.Page
	}
	return nil
}

type StartLLMSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// The optional name. If unspecified, a time based name is generated.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The start conversation. All roles of the messages must be "user".
	Conversation *LLMSession_Conversation `protobuf:"bytes,3,opt,name=conversation,proto3" json:"conversation,omitempty"`
	// The initial access control.
	AccessControl *LLMSession_AccessControl `protobuf:"bytes,4,opt,name=access_control,json=accessControl,proto3" json:"access_control,omitempty"`
	// Start the session as owned by the specified user.
	// It can be either user ID or email.
	Owner string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	// The parent session ID.
	// If specified, this is a sub session of the specified parent session.
	// The fields access_control and owner will be ignored.
	// Sub sessions are created asynchronously, the resource in response only contains name in meta even without id.
	ParentId      string `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLLMSessionRequest) Reset() {
	*x = StartLLMSessionRequest{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLLMSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLLMSessionRequest) ProtoMessage() {}

func (x *StartLLMSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLLMSessionRequest.ProtoReflect.Descriptor instead.
func (*StartLLMSessionRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{2}
}

func (x *StartLLMSessionRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *StartLLMSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartLLMSessionRequest) GetConversation() *LLMSession_Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *StartLLMSessionRequest) GetAccessControl() *LLMSession_AccessControl {
	if x != nil {
		return x.AccessControl
	}
	return nil
}

func (x *StartLLMSessionRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *StartLLMSessionRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type StartLLMSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For regular sessions, the full resource is returned.
	// For sub sessions, the resource only contains meta.name.
	Resource      *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLLMSessionResponse) Reset() {
	*x = StartLLMSessionResponse{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLLMSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLLMSessionResponse) ProtoMessage() {}

func (x *StartLLMSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLLMSessionResponse.ProtoReflect.Descriptor instead.
func (*StartLLMSessionResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{3}
}

func (x *StartLLMSessionResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ReplyLLMSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The LLMSession ID.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The version of the session to be updated.
	// If it doesn't match the latest version of the session,
	// update will be rejected as Conflict.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// If specified:
	//   - The conversation will be resumed by appending the new messages (role must be "user").
	//   - If it had an active cancellation, incomplete streaming fragments after the cancellation point
	//     are discarded. Unpaired trailing tool calls are also trimmed; user messages are preserved.
	//
	// This request requires the session to be in STOPPED state.
	// Placing a cancellation via this request is NOT supported, use the CancelLLMSession RPC instead.
	Conversation  *LLMSession_Conversation `protobuf:"bytes,3,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyLLMSessionRequest) Reset() {
	*x = ReplyLLMSessionRequest{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyLLMSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyLLMSessionRequest) ProtoMessage() {}

func (x *ReplyLLMSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyLLMSessionRequest.ProtoReflect.Descriptor instead.
func (*ReplyLLMSessionRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{4}
}

func (x *ReplyLLMSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplyLLMSessionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReplyLLMSessionRequest) GetConversation() *LLMSession_Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

type ReplyLLMSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyLLMSessionResponse) Reset() {
	*x = ReplyLLMSessionResponse{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyLLMSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyLLMSessionResponse) ProtoMessage() {}

func (x *ReplyLLMSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyLLMSessionResponse.ProtoReflect.Descriptor instead.
func (*ReplyLLMSessionResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{5}
}

func (x *ReplyLLMSessionResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type CancelLLMSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The LLMSession ID.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The version of the session to be updated.
	// If it doesn't match the latest version of the session,
	// update will be rejected as Conflict.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelLLMSessionRequest) Reset() {
	*x = CancelLLMSessionRequest{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLLMSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLLMSessionRequest) ProtoMessage() {}

func (x *CancelLLMSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLLMSessionRequest.ProtoReflect.Descriptor instead.
func (*CancelLLMSessionRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{6}
}

func (x *CancelLLMSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CancelLLMSessionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CancelLLMSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelLLMSessionResponse) Reset() {
	*x = CancelLLMSessionResponse{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLLMSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLLMSessionResponse) ProtoMessage() {}

func (x *CancelLLMSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLLMSessionResponse.ProtoReflect.Descriptor instead.
func (*CancelLLMSessionResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{7}
}

func (x *CancelLLMSessionResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type LLMSessionStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the existing session which will be accessed.
	// To start a new session, this should be unspecified.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// To start a new session, this must be specified and "id" MUST NOT be specified.
	StartRequest  *StartLLMSessionRequest `protobuf:"bytes,2,opt,name=start_request,json=startRequest,proto3" json:"start_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMSessionStreamRequest) Reset() {
	*x = LLMSessionStreamRequest{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMSessionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMSessionStreamRequest) ProtoMessage() {}

func (x *LLMSessionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMSessionStreamRequest.ProtoReflect.Descriptor instead.
func (*LLMSessionStreamRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{8}
}

func (x *LLMSessionStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LLMSessionStreamRequest) GetStartRequest() *StartLLMSessionRequest {
	if x != nil {
		return x.StartRequest
	}
	return nil
}

type LLMSessionStreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If not empty, the version of the LLMSession is updated which means the LLMSession itself is updated.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*LLMSessionStreamEvent_FullSync_
	//	*LLMSessionStreamEvent_AppendMessage_
	//	*LLMSessionStreamEvent_UpdateStatus_
	Event         isLLMSessionStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMSessionStreamEvent) Reset() {
	*x = LLMSessionStreamEvent{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMSessionStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMSessionStreamEvent) ProtoMessage() {}

func (x *LLMSessionStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMSessionStreamEvent.ProtoReflect.Descriptor instead.
func (*LLMSessionStreamEvent) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{9}
}

func (x *LLMSessionStreamEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LLMSessionStreamEvent) GetEvent() isLLMSessionStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *LLMSessionStreamEvent) GetFullSync() *LLMSessionStreamEvent_FullSync {
	if x != nil {
		if x, ok := x.Event.(*LLMSessionStreamEvent_FullSync_); ok {
			return x.FullSync
		}
	}
	return nil
}

func (x *LLMSessionStreamEvent) GetAppendMessage() *LLMSessionStreamEvent_AppendMessage {
	if x != nil {
		if x, ok := x.Event.(*LLMSessionStreamEvent_AppendMessage_); ok {
			return x.AppendMessage
		}
	}
	return nil
}

func (x *LLMSessionStreamEvent) GetUpdateStatus() *LLMSessionStreamEvent_UpdateStatus {
	if x != nil {
		if x, ok := x.Event.(*LLMSessionStreamEvent_UpdateStatus_); ok {
			return x.UpdateStatus
		}
	}
	return nil
}

type isLLMSessionStreamEvent_Event interface {
	isLLMSessionStreamEvent_Event()
}

type LLMSessionStreamEvent_FullSync_ struct {
	// This should be the first event after the streaming starts.
	FullSync *LLMSessionStreamEvent_FullSync `protobuf:"bytes,2,opt,name=full_sync,json=fullSync,proto3,oneof"`
}

type LLMSessionStreamEvent_AppendMessage_ struct {
	// Message is appended or partially streamed.
	AppendMessage *LLMSessionStreamEvent_AppendMessage `protobuf:"bytes,3,opt,name=append_message,json=appendMessage,proto3,oneof"`
}

type LLMSessionStreamEvent_UpdateStatus_ struct {
	// The status of the LLMSession is changed.
	UpdateStatus *LLMSessionStreamEvent_UpdateStatus `protobuf:"bytes,4,opt,name=update_status,json=updateStatus,proto3,oneof"`
}

func (*LLMSessionStreamEvent_FullSync_) isLLMSessionStreamEvent_Event() {}

func (*LLMSessionStreamEvent_AppendMessage_) isLLMSessionStreamEvent_Event() {}

func (*LLMSessionStreamEvent_UpdateStatus_) isLLMSessionStreamEvent_Event() {}

type QueryLLMSessionMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The LLMSession ID.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// If specified, exclude messages earlier than the value (inclusive).
	// Otherwise, query up to the oldest message.
	Since *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	// If specified, exclude messages no earlier than the value (exclusive).
	// Otherwise, query up to the most recent message.
	Before *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	// If specified, start returning messages after the specified message id.
	AfterMessageId string `protobuf:"bytes,4,opt,name=after_message_id,json=afterMessageId,proto3" json:"after_message_id,omitempty"`
	// If true, returning messages starting from "before", in the descending order of time, until reaching "since" or "limit".
	// Otherwise, messages are returned from "since", in the ascending order of time, until reaching "before" or "limit".
	Backward bool `protobuf:"varint,5,opt,name=backward,proto3" json:"backward,omitempty"`
	// Maximum number of messages to return.
	Limit         int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLLMSessionMessagesRequest) Reset() {
	*x = QueryLLMSessionMessagesRequest{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLLMSessionMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLLMSessionMessagesRequest) ProtoMessage() {}

func (x *QueryLLMSessionMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLLMSessionMessagesRequest.ProtoReflect.Descriptor instead.
func (*QueryLLMSessionMessagesRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{10}
}

func (x *QueryLLMSessionMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QueryLLMSessionMessagesRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *QueryLLMSessionMessagesRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *QueryLLMSessionMessagesRequest) GetAfterMessageId() string {
	if x != nil {
		return x.AfterMessageId
	}
	return ""
}

func (x *QueryLLMSessionMessagesRequest) GetBackward() bool {
	if x != nil {
		return x.Backward
	}
	return false
}

func (x *QueryLLMSessionMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryLLMSessionMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*LLMSession_Message  `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLLMSessionMessagesResponse) Reset() {
	*x = QueryLLMSessionMessagesResponse{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLLMSessionMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLLMSessionMessagesResponse) ProtoMessage() {}

func (x *QueryLLMSessionMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLLMSessionMessagesResponse.ProtoReflect.Descriptor instead.
func (*QueryLLMSessionMessagesResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{11}
}

func (x *QueryLLMSessionMessagesResponse) GetMessages() []*LLMSession_Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListLLMSessionsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, task-initiated sessions are returned.
	TaskInitiated bool `protobuf:"varint,1,opt,name=task_initiated,json=taskInitiated,proto3" json:"task_initiated,omitempty"`
	// If true, interactive sessions (not task-initiated) are returned.
	Interactive bool `protobuf:"varint,2,opt,name=interactive,proto3" json:"interactive,omitempty"`
	// If specified, all sessions matching current user's access level will be returned.
	Shared LLMSession_AccessControl_Level `protobuf:"varint,3,opt,name=shared,proto3,enum=sandboxes.api.v1.LLMSession_AccessControl_Level" json:"shared,omitempty"`
	// If unspecified, all sessions are returned without checking status.
	// If specified, only sessions matching the status will be returned.
	Status *ListLLMSessionsRequest_Filter_Status `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// If non-empty, list of parent IDs for querying child sessions.
	Parents       []string `protobuf:"bytes,5,rep,name=parents,proto3" json:"parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLLMSessionsRequest_Filter) Reset() {
	*x = ListLLMSessionsRequest_Filter{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLLMSessionsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLLMSessionsRequest_Filter) ProtoMessage() {}

func (x *ListLLMSessionsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLLMSessionsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListLLMSessionsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListLLMSessionsRequest_Filter) GetTaskInitiated() bool {
	if x != nil {
		return x.TaskInitiated
	}
	return false
}

func (x *ListLLMSessionsRequest_Filter) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *ListLLMSessionsRequest_Filter) GetShared() LLMSession_AccessControl_Level {
	if x != nil {
		return x.Shared
	}
	return LLMSession_AccessControl_NONE
}

func (x *ListLLMSessionsRequest_Filter) GetStatus() *ListLLMSessionsRequest_Filter_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListLLMSessionsRequest_Filter) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

type ListLLMSessionsRequest_Filter_Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Include running sessions.
	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	// Include stopped sessions with specified reasons.
	// If empty, no stopped sessions will be matched.
	StoppedFor []LLMSession_Stop_Reason `protobuf:"varint,2,rep,packed,name=stopped_for,json=stoppedFor,proto3,enum=sandboxes.api.v1.LLMSession_Stop_Reason" json:"stopped_for,omitempty"`
	// Include sessions with error, regardless of running/stopped state.
	WithError bool `protobuf:"varint,3,opt,name=with_error,json=withError,proto3" json:"with_error,omitempty"`
	// If true, archived sessions will be matched regardless of `stopped_for`.
	Archived      bool `protobuf:"varint,4,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLLMSessionsRequest_Filter_Status) Reset() {
	*x = ListLLMSessionsRequest_Filter_Status{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLLMSessionsRequest_Filter_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLLMSessionsRequest_Filter_Status) ProtoMessage() {}

func (x *ListLLMSessionsRequest_Filter_Status) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLLMSessionsRequest_Filter_Status.ProtoReflect.Descriptor instead.
func (*ListLLMSessionsRequest_Filter_Status) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ListLLMSessionsRequest_Filter_Status) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ListLLMSessionsRequest_Filter_Status) GetStoppedFor() []LLMSession_Stop_Reason {
	if x != nil {
		return x.StoppedFor
	}
	return nil
}

func (x *ListLLMSessionsRequest_Filter_Status) GetWithError() bool {
	if x != nil {
		return x.WithError
	}
	return false
}

func (x *ListLLMSessionsRequest_Filter_Status) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type LLMSessionStreamEvent_FullSync struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource content only contains client-visible fields which does NOT include
	// prompt_context, shared_state etc.
	Resource      *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMSessionStreamEvent_FullSync) Reset() {
	*x = LLMSessionStreamEvent_FullSync{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMSessionStreamEvent_FullSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMSessionStreamEvent_FullSync) ProtoMessage() {}

func (x *LLMSessionStreamEvent_FullSync) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMSessionStreamEvent_FullSync.ProtoReflect.Descriptor instead.
func (*LLMSessionStreamEvent_FullSync) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{9, 0}
}

func (x *LLMSessionStreamEvent_FullSync) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type LLMSessionStreamEvent_AppendMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message or a fragment of a message depending on "start"/"end" flag.
	// The client must use the message id to match the last message in the session's conversation.
	// Otherwise, the event should be ignored.
	// It's possible the message text is empty, for example when "end" is true to indicate the completion
	// of a streaming message.
	Message *LLMSession_Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Indicate this is the start of a message.
	// When this is set to true, the message can replace the last one in the session's conversation if id matches.
	Start bool `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	// Indicate this is the last fragment of a message.
	End           bool `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMSessionStreamEvent_AppendMessage) Reset() {
	*x = LLMSessionStreamEvent_AppendMessage{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMSessionStreamEvent_AppendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMSessionStreamEvent_AppendMessage) ProtoMessage() {}

func (x *LLMSessionStreamEvent_AppendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMSessionStreamEvent_AppendMessage.ProtoReflect.Descriptor instead.
func (*LLMSessionStreamEvent_AppendMessage) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{9, 1}
}

func (x *LLMSessionStreamEvent_AppendMessage) GetMessage() *LLMSession_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *LLMSessionStreamEvent_AppendMessage) GetStart() bool {
	if x != nil {
		return x.Start
	}
	return false
}

func (x *LLMSessionStreamEvent_AppendMessage) GetEnd() bool {
	if x != nil {
		return x.End
	}
	return false
}

type LLMSessionStreamEvent_UpdateStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The "session" only includes the fields related to status, e.g. "status" and "stop".
	Session       *LLMSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMSessionStreamEvent_UpdateStatus) Reset() {
	*x = LLMSessionStreamEvent_UpdateStatus{}
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMSessionStreamEvent_UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMSessionStreamEvent_UpdateStatus) ProtoMessage() {}

func (x *LLMSessionStreamEvent_UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_llmservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMSessionStreamEvent_UpdateStatus.ProtoReflect.Descriptor instead.
func (*LLMSessionStreamEvent_UpdateStatus) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_llmservice_proto_rawDescGZIP(), []int{9, 2}
}

func (x *LLMSessionStreamEvent_UpdateStatus) GetSession() *LLMSession {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_sandboxes_api_v1_llmservice_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_llmservice_proto_rawDesc = "" +
	"\n" +
	"!sandboxes/api/v1/llmservice.proto\x12\x10sandboxes.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dsandboxes/api/v1/common.proto\x1a\x1dsandboxes/api/v1/object.proto\x1a\x1fsandboxes/api/v1/resource.proto\x1a*sandboxes/api/v1/resource_llmsession.proto\"\xaa\x05\n" +
	"\x16ListLLMSessionsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12C\n" +
	"\vmeta_filter\x18\x02 \x01(\v2\".sandboxes.api.v1.ObjectMetaFilterR\n" +
	"metaFilter\x128\n" +
	"\x04page\x18\x03 \x01(\v2$.sandboxes.api.v1.Pagination.RequestR\x04page\x12G\n" +
	"\x06filter\x18\x04 \x01(\v2/.sandboxes.api.v1.ListLLMSessionsRequest.FilterR\x06filter\x1a\xb0\x03\n" +
	"\x06Filter\x12%\n" +
	"\x0etask_initiated\x18\x01 \x01(\bR\rtaskInitiated\x12 \n" +
	"\vinteractive\x18\x02 \x01(\bR\vinteractive\x12H\n" +
	"\x06shared\x18\x03 \x01(\x0e20.sandboxes.api.v1.LLMSession.AccessControl.LevelR\x06shared\x12N\n" +
	"\x06status\x18\x04 \x01(\v26.sandboxes.api.v1.ListLLMSessionsRequest.Filter.StatusR\x06status\x12\x18\n" +
	"\aparents\x18\x05 \x03(\tR\aparents\x1a\xa8\x01\n" +
	"\x06Status\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12I\n" +
	"\vstopped_for\x18\x02 \x03(\x0e2(.sandboxes.api.v1.LLMSession.Stop.ReasonR\n" +
	"stoppedFor\x12\x1d\n" +
	"\n" +
	"with_error\x18\x03 \x01(\bR\twithError\x12\x1a\n" +
	"\barchived\x18\x04 \x01(\bR\barchived\"\x8c\x01\n" +
	"\x17ListLLMSessionsResponse\x126\n" +
	"\bsessions\x18\x01 \x03(\v2\x1a.sandboxes.api.v1.ResourceR\bsessions\x129\n" +
	"\x04page\x18\x02 \x01(\v2%.sandboxes.api.v1.Pagination.ResponseR\x04page\"\x98\x02\n" +
	"\x16StartLLMSessionRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12M\n" +
	"\fconversation\x18\x03 \x01(\v2).sandboxes.api.v1.LLMSession.ConversationR\fconversation\x12Q\n" +
	"\x0eaccess_control\x18\x04 \x01(\v2*.sandboxes.api.v1.LLMSession.AccessControlR\raccessControl\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\tR\bparentId\"Q\n" +
	"\x17StartLLMSessionResponse\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.sandboxes.api.v1.ResourceR\bresource\"\xa0\x01\n" +
	"\x16ReplyLLMSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12M\n" +
	"\fconversation\x18\x03 \x01(\v2).sandboxes.api.v1.LLMSession.ConversationR\fconversation\"Q\n" +
	"\x17ReplyLLMSessionResponse\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.sandboxes.api.v1.ResourceR\bresource\"R\n" +
	"\x17CancelLLMSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"R\n" +
	"\x18CancelLLMSessionResponse\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.sandboxes.api.v1.ResourceR\bresource\"\x87\x01\n" +
	"\x17LLMSessionStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12M\n" +
	"\rstart_request\x18\x02 \x01(\v2(.sandboxes.api.v1.StartLLMSessionRequestR\fstartRequest\"\xcd\x04\n" +
	"\x15LLMSessionStreamEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12O\n" +
	"\tfull_sync\x18\x02 \x01(\v20.sandboxes.api.v1.LLMSessionStreamEvent.FullSyncH\x00R\bfullSync\x12^\n" +
	"\x0eappend_message\x18\x03 \x01(\v25.sandboxes.api.v1.LLMSessionStreamEvent.AppendMessageH\x00R\rappendMessage\x12[\n" +
	"\rupdate_status\x18\x04 \x01(\v24.sandboxes.api.v1.LLMSessionStreamEvent.UpdateStatusH\x00R\fupdateStatus\x1aB\n" +
	"\bFullSync\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.sandboxes.api.v1.ResourceR\bresource\x1aw\n" +
	"\rAppendMessage\x12>\n" +
	"\amessage\x18\x01 \x01(\v2$.sandboxes.api.v1.LLMSession.MessageR\amessage\x12\x14\n" +
	"\x05start\x18\x02 \x01(\bR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\bR\x03end\x1aF\n" +
	"\fUpdateStatus\x126\n" +
	"\asession\x18\x01 \x01(\v2\x1c.sandboxes.api.v1.LLMSessionR\asessionB\a\n" +
	"\x05event\"\x81\x02\n" +
	"\x1eQueryLLMSessionMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x122\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\x12(\n" +
	"\x10after_message_id\x18\x04 \x01(\tR\x0eafterMessageId\x12\x1a\n" +
	"\bbackward\x18\x05 \x01(\bR\bbackward\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"c\n" +
	"\x1fQueryLLMSessionMessagesResponse\x12@\n" +
	"\bmessages\x18\x01 \x03(\v2$.sandboxes.api.v1.LLMSession.MessageR\bmessages2\x99\x05\n" +
	"\n" +
	"LLMService\x12f\n" +
	"\x0fListLLMSessions\x12(.sandboxes.api.v1.ListLLMSessionsRequest\x1a).sandboxes.api.v1.ListLLMSessionsResponse\x12f\n" +
	"\x0fStartLLMSession\x12(.sandboxes.api.v1.StartLLMSessionRequest\x1a).sandboxes.api.v1.StartLLMSessionResponse\x12f\n" +
	"\x0fReplyLLMSession\x12(.sandboxes.api.v1.ReplyLLMSessionRequest\x1a).sandboxes.api.v1.ReplyLLMSessionResponse\x12i\n" +
	"\x10CancelLLMSession\x12).sandboxes.api.v1.CancelLLMSessionRequest\x1a*.sandboxes.api.v1.CancelLLMSessionResponse\x12h\n" +
	"\x10StreamLLMSession\x12).sandboxes.api.v1.LLMSessionStreamRequest\x1a'.sandboxes.api.v1.LLMSessionStreamEvent0\x01\x12~\n" +
	"\x17QueryLLMSessionMessages\x120.sandboxes.api.v1.QueryLLMSessionMessagesRequest\x1a1.sandboxes.api.v1.QueryLLMSessionMessagesResponseB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_llmservice_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_llmservice_proto_rawDescData []byte
)

func file_sandboxes_api_v1_llmservice_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_llmservice_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_llmservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_llmservice_proto_rawDesc), len(file_sandboxes_api_v1_llmservice_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_llmservice_proto_rawDescData
}

var file_sandboxes_api_v1_llmservice_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_sandboxes_api_v1_llmservice_proto_goTypes = []any{
	(*ListLLMSessionsRequest)(nil),               // 0: sandboxes.api.v1.ListLLMSessionsRequest
	(*ListLLMSessionsResponse)(nil),              // 1: sandboxes.api.v1.ListLLMSessionsResponse
	(*StartLLMSessionRequest)(nil),               // 2: sandboxes.api.v1.StartLLMSessionRequest
	(*StartLLMSessionResponse)(nil),              // 3: sandboxes.api.v1.StartLLMSessionResponse
	(*ReplyLLMSessionRequest)(nil),               // 4: sandboxes.api.v1.ReplyLLMSessionRequest
	(*ReplyLLMSessionResponse)(nil),              // 5: sandboxes.api.v1.ReplyLLMSessionResponse
	(*CancelLLMSessionRequest)(nil),              // 6: sandboxes.api.v1.CancelLLMSessionRequest
	(*CancelLLMSessionResponse)(nil),             // 7: sandboxes.api.v1.CancelLLMSessionResponse
	(*LLMSessionStreamRequest)(nil),              // 8: sandboxes.api.v1.LLMSessionStreamRequest
	(*LLMSessionStreamEvent)(nil),                // 9: sandboxes.api.v1.LLMSessionStreamEvent
	(*QueryLLMSessionMessagesRequest)(nil),       // 10: sandboxes.api.v1.QueryLLMSessionMessagesRequest
	(*QueryLLMSessionMessagesResponse)(nil),      // 11: sandboxes.api.v1.QueryLLMSessionMessagesResponse
	(*ListLLMSessionsRequest_Filter)(nil),        // 12: sandboxes.api.v1.ListLLMSessionsRequest.Filter
	(*ListLLMSessionsRequest_Filter_Status)(nil), // 13: sandboxes.api.v1.ListLLMSessionsRequest.Filter.Status
	(*LLMSessionStreamEvent_FullSync)(nil),       // 14: sandboxes.api.v1.LLMSessionStreamEvent.FullSync
	(*LLMSessionStreamEvent_AppendMessage)(nil),  // 15: sandboxes.api.v1.LLMSessionStreamEvent.AppendMessage
	(*LLMSessionStreamEvent_UpdateStatus)(nil),   // 16: sandboxes.api.v1.LLMSessionStreamEvent.UpdateStatus
	(*ObjectMetaFilter)(nil),                     // 17: sandboxes.api.v1.ObjectMetaFilter
	(*Pagination_Request)(nil),                   // 18: sandboxes.api.v1.Pagination.Request
	(*Resource)(nil),                             // 19: sandboxes.api.v1.Resource
	(*Pagination_Response)(nil),                  // 20: sandboxes.api.v1.Pagination.Response
	(*LLMSession_Conversation)(nil),              // 21: sandboxes.api.v1.LLMSession.Conversation
	(*LLMSession_AccessControl)(nil),             // 22: sandboxes.api.v1.LLMSession.AccessControl
	(*timestamppb.Timestamp)(nil),                // 23: google.protobuf.Timestamp
	(*LLMSession_Message)(nil),                   // 24: sandboxes.api.v1.LLMSession.Message
	(LLMSession_AccessControl_Level)(0),          // 25: sandboxes.api.v1.LLMSession.AccessControl.Level
	(LLMSession_Stop_Reason)(0),                  // 26: sandboxes.api.v1.LLMSession.Stop.Reason
	(*LLMSession)(nil),                           // 27: sandboxes.api.v1.LLMSession
}
var file_sandboxes_api_v1_llmservice_proto_depIdxs = []int32{
	17, // 0: sandboxes.api.v1.ListLLMSessionsRequest.meta_filter:type_name -> sandboxes.api.v1.ObjectMetaFilter
	18, // 1: sandboxes.api.v1.ListLLMSessionsRequest.page:type_name -> sandboxes.api.v1.Pagination.Request
	12, // 2: sandboxes.api.v1.ListLLMSessionsRequest.filter:type_name -> sandboxes.api.v1.ListLLMSessionsRequest.Filter
	19, // 3: sandboxes.api.v1.ListLLMSessionsResponse.sessions:type_name -> sandboxes.api.v1.Resource
	20, // 4: sandboxes.api.v1.ListLLMSessionsResponse.page:type_name -> sandboxes.api.v1.Pagination.Response
	21, // 5: sandboxes.api.v1.StartLLMSessionRequest.conversation:type_name -> sandboxes.api.v1.LLMSession.Conversation
	22, // 6: sandboxes.api.v1.StartLLMSessionRequest.access_control:type_name -> sandboxes.api.v1.LLMSession.AccessControl
	19, // 7: sandboxes.api.v1.StartLLMSessionResponse.resource:type_name -> sandboxes.api.v1.Resource
	21, // 8: sandboxes.api.v1.ReplyLLMSessionRequest.conversation:type_name -> sandboxes.api.v1.LLMSession.Conversation
	19, // 9: sandboxes.api.v1.ReplyLLMSessionResponse.resource:type_name -> sandboxes.api.v1.Resource
	19, // 10: sandboxes.api.v1.CancelLLMSessionResponse.resource:type_name -> sandboxes.api.v1.Resource
	2,  // 11: sandboxes.api.v1.LLMSessionStreamRequest.start_request:type_name -> sandboxes.api.v1.StartLLMSessionRequest
	14, // 12: sandboxes.api.v1.LLMSessionStreamEvent.full_sync:type_name -> sandboxes.api.v1.LLMSessionStreamEvent.FullSync
	15, // 13: sandboxes.api.v1.LLMSessionStreamEvent.append_message:type_name -> sandboxes.api.v1.LLMSessionStreamEvent.AppendMessage
	16, // 14: sandboxes.api.v1.LLMSessionStreamEvent.update_status:type_name -> sandboxes.api.v1.LLMSessionStreamEvent.UpdateStatus
	23, // 15: sandboxes.api.v1.QueryLLMSessionMessagesRequest.since:type_name -> google.protobuf.Timestamp
	23, // 16: sandboxes.api.v1.QueryLLMSessionMessagesRequest.before:type_name -> google.protobuf.Timestamp
	24, // 17: sandboxes.api.v1.QueryLLMSessionMessagesResponse.messages:type_name -> sandboxes.api.v1.LLMSession.Message
	25, // 18: sandboxes.api.v1.ListLLMSessionsRequest.Filter.shared:type_name -> sandboxes.api.v1.LLMSession.AccessControl.Level
	13, // 19: sandboxes.api.v1.ListLLMSessionsRequest.Filter.status:type_name -> sandboxes.api.v1.ListLLMSessionsRequest.Filter.Status
	26, // 20: sandboxes.api.v1.ListLLMSessionsRequest.Filter.Status.stopped_for:type_name -> sandboxes.api.v1.LLMSession.Stop.Reason
	19, // 21: sandboxes.api.v1.LLMSessionStreamEvent.FullSync.resource:type_name -> sandboxes.api.v1.Resource
	24, // 22: sandboxes.api.v1.LLMSessionStreamEvent.AppendMessage.message:type_name -> sandboxes.api.v1.LLMSession.Message
	27, // 23: sandboxes.api.v1.LLMSessionStreamEvent.UpdateStatus.session:type_name -> sandboxes.api.v1.LLMSession
	0,  // 24: sandboxes.api.v1.LLMService.ListLLMSessions:input_type -> sandboxes.api.v1.ListLLMSessionsRequest
	2,  // 25: sandboxes.api.v1.LLMService.StartLLMSession:input_type -> sandboxes.api.v1.StartLLMSessionRequest
	4,  // 26: sandboxes.api.v1.LLMService.ReplyLLMSession:input_type -> sandboxes.api.v1.ReplyLLMSessionRequest
	6,  // 27: sandboxes.api.v1.LLMService.CancelLLMSession:input_type -> sandboxes.api.v1.CancelLLMSessionRequest
	8,  // 28: sandboxes.api.v1.LLMService.StreamLLMSession:input_type -> sandboxes.api.v1.LLMSessionStreamRequest
	10, // 29: sandboxes.api.v1.LLMService.QueryLLMSessionMessages:input_type -> sandboxes.api.v1.QueryLLMSessionMessagesRequest
	1,  // 30: sandboxes.api.v1.LLMService.ListLLMSessions:output_type -> sandboxes.api.v1.ListLLMSessionsResponse
	3,  // 31: sandboxes.api.v1.LLMService.StartLLMSession:output_type -> sandboxes.api.v1.StartLLMSessionResponse
	5,  // 32: sandboxes.api.v1.LLMService.ReplyLLMSession:output_type -> sandboxes.api.v1.ReplyLLMSessionResponse
	7,  // 33: sandboxes.api.v1.LLMService.CancelLLMSession:output_type -> sandboxes.api.v1.CancelLLMSessionResponse
	9,  // 34: sandboxes.api.v1.LLMService.StreamLLMSession:output_type -> sandboxes.api.v1.LLMSessionStreamEvent
	11, // 35: sandboxes.api.v1.LLMService.QueryLLMSessionMessages:output_type -> sandboxes.api.v1.QueryLLMSessionMessagesResponse
	30, // [30:36] is the sub-list for method output_type
	24, // [24:30] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_llmservice_proto_init() }
func file_sandboxes_api_v1_llmservice_proto_init() {
	if File_sandboxes_api_v1_llmservice_proto != nil {
		return
	}
	file_sandboxes_api_v1_common_proto_init()
	file_sandboxes_api_v1_object_proto_init()
	file_sandboxes_api_v1_resource_proto_init()
	file_sandboxes_api_v1_resource_llmsession_proto_init()
	file_sandboxes_api_v1_llmservice_proto_msgTypes[9].OneofWrappers = []any{
		(*LLMSessionStreamEvent_FullSync_)(nil),
		(*LLMSessionStreamEvent_AppendMessage_)(nil),
		(*LLMSessionStreamEvent_UpdateStatus_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_llmservice_proto_rawDesc), len(file_sandboxes_api_v1_llmservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandboxes_api_v1_llmservice_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_llmservice_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_llmservice_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_llmservice_proto = out.File
	file_sandboxes_api_v1_llmservice_proto_goTypes = nil
	file_sandboxes_api_v1_llmservice_proto_depIdxs = nil
}
