// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/log_query.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextLogQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// logsource_id is another representation of the combination of workload and log_ref.
	// For one query, there are multiple log sources requested. To differenciate the queried logs,
	// this value will be used to uniquely reference the target log source.
	// This value can be any string as long as the client side can track it down to the workload and log.
	LogsourceId   string           `protobuf:"bytes,1,opt,name=logsource_id,json=logsourceId,proto3" json:"logsource_id,omitempty"`
	Workload      *WorkloadRef     `protobuf:"bytes,2,opt,name=workload,proto3" json:"workload,omitempty"`
	Log           *LogRef          `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Indexed       *IndexedLogQuery `protobuf:"bytes,4,opt,name=indexed,proto3" json:"indexed,omitempty"`
	Limit         int32            `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextLogQuery) Reset() {
	*x = TextLogQuery{}
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextLogQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextLogQuery) ProtoMessage() {}

func (x *TextLogQuery) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextLogQuery.ProtoReflect.Descriptor instead.
func (*TextLogQuery) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_log_query_proto_rawDescGZIP(), []int{0}
}

func (x *TextLogQuery) GetLogsourceId() string {
	if x != nil {
		return x.LogsourceId
	}
	return ""
}

func (x *TextLogQuery) GetWorkload() *WorkloadRef {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *TextLogQuery) GetLog() *LogRef {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *TextLogQuery) GetIndexed() *IndexedLogQuery {
	if x != nil {
		return x.Indexed
	}
	return nil
}

func (x *TextLogQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MergedTextLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogsourceId   string                 `protobuf:"bytes,1,opt,name=logsource_id,json=logsourceId,proto3" json:"logsource_id,omitempty"`
	Entry         *IndexedLogEntry       `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergedTextLogEntry) Reset() {
	*x = MergedTextLogEntry{}
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergedTextLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergedTextLogEntry) ProtoMessage() {}

func (x *MergedTextLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergedTextLogEntry.ProtoReflect.Descriptor instead.
func (*MergedTextLogEntry) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_log_query_proto_rawDescGZIP(), []int{1}
}

func (x *MergedTextLogEntry) GetLogsourceId() string {
	if x != nil {
		return x.LogsourceId
	}
	return ""
}

func (x *MergedTextLogEntry) GetEntry() *IndexedLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type TextLogQueries struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Queries []*TextLogQuery        `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	// If merge.limit is not 0, the queried result include the merged result.
	Merge         *TextLogQueries_Merge `protobuf:"bytes,2,opt,name=merge,proto3" json:"merge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextLogQueries) Reset() {
	*x = TextLogQueries{}
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextLogQueries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextLogQueries) ProtoMessage() {}

func (x *TextLogQueries) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextLogQueries.ProtoReflect.Descriptor instead.
func (*TextLogQueries) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_log_query_proto_rawDescGZIP(), []int{2}
}

func (x *TextLogQueries) GetQueries() []*TextLogQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *TextLogQueries) GetMerge() *TextLogQueries_Merge {
	if x != nil {
		return x.Merge
	}
	return nil
}

type TextLogBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field matches TextLogQuery.logsource_id.
	LogsourceId   string             `protobuf:"bytes,1,opt,name=logsource_id,json=logsourceId,proto3" json:"logsource_id,omitempty"`
	LogEntry      []*IndexedLogEntry `protobuf:"bytes,2,rep,name=log_entry,json=logEntry,proto3" json:"log_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextLogBatch) Reset() {
	*x = TextLogBatch{}
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextLogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextLogBatch) ProtoMessage() {}

func (x *TextLogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextLogBatch.ProtoReflect.Descriptor instead.
func (*TextLogBatch) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_log_query_proto_rawDescGZIP(), []int{3}
}

func (x *TextLogBatch) GetLogsourceId() string {
	if x != nil {
		return x.LogsourceId
	}
	return ""
}

func (x *TextLogBatch) GetLogEntry() []*IndexedLogEntry {
	if x != nil {
		return x.LogEntry
	}
	return nil
}

type TextLogBatches struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Batches []*TextLogBatch        `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	// If TextLogQueries.limit is not zero, this field includes the merged result.
	MergedEntries []*MergedTextLogEntry `protobuf:"bytes,2,rep,name=merged_entries,json=mergedEntries,proto3" json:"merged_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextLogBatches) Reset() {
	*x = TextLogBatches{}
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextLogBatches) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextLogBatches) ProtoMessage() {}

func (x *TextLogBatches) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextLogBatches.ProtoReflect.Descriptor instead.
func (*TextLogBatches) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_log_query_proto_rawDescGZIP(), []int{4}
}

func (x *TextLogBatches) GetBatches() []*TextLogBatch {
	if x != nil {
		return x.Batches
	}
	return nil
}

func (x *TextLogBatches) GetMergedEntries() []*MergedTextLogEntry {
	if x != nil {
		return x.MergedEntries
	}
	return nil
}

type LogQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*LogQueryRequest_TextLogQueries
	Content       isLogQueryRequest_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogQueryRequest) Reset() {
	*x = LogQueryRequest{}
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogQueryRequest) ProtoMessage() {}

func (x *LogQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogQueryRequest.ProtoReflect.Descriptor instead.
func (*LogQueryRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_log_query_proto_rawDescGZIP(), []int{5}
}

func (x *LogQueryRequest) GetContent() isLogQueryRequest_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *LogQueryRequest) GetTextLogQueries() *TextLogQueries {
	if x != nil {
		if x, ok := x.Content.(*LogQueryRequest_TextLogQueries); ok {
			return x.TextLogQueries
		}
	}
	return nil
}

type isLogQueryRequest_Content interface {
	isLogQueryRequest_Content()
}

type LogQueryRequest_TextLogQueries struct {
	TextLogQueries *TextLogQueries `protobuf:"bytes,1,opt,name=text_log_queries,json=textLogQueries,proto3,oneof"`
}

func (*LogQueryRequest_TextLogQueries) isLogQueryRequest_Content() {}

type LogQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*LogQueryResponse_TextLogBatches
	Content       isLogQueryResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogQueryResponse) Reset() {
	*x = LogQueryResponse{}
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogQueryResponse) ProtoMessage() {}

func (x *LogQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogQueryResponse.ProtoReflect.Descriptor instead.
func (*LogQueryResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_log_query_proto_rawDescGZIP(), []int{6}
}

func (x *LogQueryResponse) GetContent() isLogQueryResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *LogQueryResponse) GetTextLogBatches() *TextLogBatches {
	if x != nil {
		if x, ok := x.Content.(*LogQueryResponse_TextLogBatches); ok {
			return x.TextLogBatches
		}
	}
	return nil
}

type isLogQueryResponse_Content interface {
	isLogQueryResponse_Content()
}

type LogQueryResponse_TextLogBatches struct {
	TextLogBatches *TextLogBatches `protobuf:"bytes,1,opt,name=text_log_batches,json=textLogBatches,proto3,oneof"`
}

func (*LogQueryResponse_TextLogBatches) isLogQueryResponse_Content() {}

type TextLogQueries_Merge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextLogQueries_Merge) Reset() {
	*x = TextLogQueries_Merge{}
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextLogQueries_Merge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextLogQueries_Merge) ProtoMessage() {}

func (x *TextLogQueries_Merge) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_log_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextLogQueries_Merge.ProtoReflect.Descriptor instead.
func (*TextLogQueries_Merge) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_log_query_proto_rawDescGZIP(), []int{2, 0}
}

func (x *TextLogQueries_Merge) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_sandboxes_api_v1_log_query_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_log_query_proto_rawDesc = "" +
	"\n" +
	" sandboxes/api/v1/log_query.proto\x12\x10sandboxes.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\x1a\x1fsandboxes/api/v1/workload.proto\x1a&sandboxes/api/v1/workloadservice.proto\"\xeb\x01\n" +
	"\fTextLogQuery\x12!\n" +
	"\flogsource_id\x18\x01 \x01(\tR\vlogsourceId\x129\n" +
	"\bworkload\x18\x02 \x01(\v2\x1d.sandboxes.api.v1.WorkloadRefR\bworkload\x12*\n" +
	"\x03log\x18\x03 \x01(\v2\x18.sandboxes.api.v1.LogRefR\x03log\x12;\n" +
	"\aindexed\x18\x04 \x01(\v2!.sandboxes.api.v1.IndexedLogQueryR\aindexed\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"p\n" +
	"\x12MergedTextLogEntry\x12!\n" +
	"\flogsource_id\x18\x01 \x01(\tR\vlogsourceId\x127\n" +
	"\x05entry\x18\x02 \x01(\v2!.sandboxes.api.v1.IndexedLogEntryR\x05entry\"\xa7\x01\n" +
	"\x0eTextLogQueries\x128\n" +
	"\aqueries\x18\x01 \x03(\v2\x1e.sandboxes.api.v1.TextLogQueryR\aqueries\x12<\n" +
	"\x05merge\x18\x02 \x01(\v2&.sandboxes.api.v1.TextLogQueries.MergeR\x05merge\x1a\x1d\n" +
	"\x05Merge\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"q\n" +
	"\fTextLogBatch\x12!\n" +
	"\flogsource_id\x18\x01 \x01(\tR\vlogsourceId\x12>\n" +
	"\tlog_entry\x18\x02 \x03(\v2!.sandboxes.api.v1.IndexedLogEntryR\blogEntry\"\x97\x01\n" +
	"\x0eTextLogBatches\x128\n" +
	"\abatches\x18\x01 \x03(\v2\x1e.sandboxes.api.v1.TextLogBatchR\abatches\x12K\n" +
	"\x0emerged_entries\x18\x02 \x03(\v2$.sandboxes.api.v1.MergedTextLogEntryR\rmergedEntries\"j\n" +
	"\x0fLogQueryRequest\x12L\n" +
	"\x10text_log_queries\x18\x01 \x01(\v2 .sandboxes.api.v1.TextLogQueriesH\x00R\x0etextLogQueriesB\t\n" +
	"\acontent\"k\n" +
	"\x10LogQueryResponse\x12L\n" +
	"\x10text_log_batches\x18\x01 \x01(\v2 .sandboxes.api.v1.TextLogBatchesH\x00R\x0etextLogBatchesB\t\n" +
	"\acontentB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_log_query_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_log_query_proto_rawDescData []byte
)

func file_sandboxes_api_v1_log_query_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_log_query_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_log_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_log_query_proto_rawDesc), len(file_sandboxes_api_v1_log_query_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_log_query_proto_rawDescData
}

var file_sandboxes_api_v1_log_query_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sandboxes_api_v1_log_query_proto_goTypes = []any{
	(*TextLogQuery)(nil),         // 0: sandboxes.api.v1.TextLogQuery
	(*MergedTextLogEntry)(nil),   // 1: sandboxes.api.v1.MergedTextLogEntry
	(*TextLogQueries)(nil),       // 2: sandboxes.api.v1.TextLogQueries
	(*TextLogBatch)(nil),         // 3: sandboxes.api.v1.TextLogBatch
	(*TextLogBatches)(nil),       // 4: sandboxes.api.v1.TextLogBatches
	(*LogQueryRequest)(nil),      // 5: sandboxes.api.v1.LogQueryRequest
	(*LogQueryResponse)(nil),     // 6: sandboxes.api.v1.LogQueryResponse
	(*TextLogQueries_Merge)(nil), // 7: sandboxes.api.v1.TextLogQueries.Merge
	(*WorkloadRef)(nil),          // 8: sandboxes.api.v1.WorkloadRef
	(*LogRef)(nil),               // 9: sandboxes.api.v1.LogRef
	(*IndexedLogQuery)(nil),      // 10: sandboxes.api.v1.IndexedLogQuery
	(*IndexedLogEntry)(nil),      // 11: sandboxes.api.v1.IndexedLogEntry
}
var file_sandboxes_api_v1_log_query_proto_depIdxs = []int32{
	8,  // 0: sandboxes.api.v1.TextLogQuery.workload:type_name -> sandboxes.api.v1.WorkloadRef
	9,  // 1: sandboxes.api.v1.TextLogQuery.log:type_name -> sandboxes.api.v1.LogRef
	10, // 2: sandboxes.api.v1.TextLogQuery.indexed:type_name -> sandboxes.api.v1.IndexedLogQuery
	11, // 3: sandboxes.api.v1.MergedTextLogEntry.entry:type_name -> sandboxes.api.v1.IndexedLogEntry
	0,  // 4: sandboxes.api.v1.TextLogQueries.queries:type_name -> sandboxes.api.v1.TextLogQuery
	7,  // 5: sandboxes.api.v1.TextLogQueries.merge:type_name -> sandboxes.api.v1.TextLogQueries.Merge
	11, // 6: sandboxes.api.v1.TextLogBatch.log_entry:type_name -> sandboxes.api.v1.IndexedLogEntry
	3,  // 7: sandboxes.api.v1.TextLogBatches.batches:type_name -> sandboxes.api.v1.TextLogBatch
	1,  // 8: sandboxes.api.v1.TextLogBatches.merged_entries:type_name -> sandboxes.api.v1.MergedTextLogEntry
	2,  // 9: sandboxes.api.v1.LogQueryRequest.text_log_queries:type_name -> sandboxes.api.v1.TextLogQueries
	4,  // 10: sandboxes.api.v1.LogQueryResponse.text_log_batches:type_name -> sandboxes.api.v1.TextLogBatches
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_log_query_proto_init() }
func file_sandboxes_api_v1_log_query_proto_init() {
	if File_sandboxes_api_v1_log_query_proto != nil {
		return
	}
	file_sandboxes_api_v1_workload_proto_init()
	file_sandboxes_api_v1_workloadservice_proto_init()
	file_sandboxes_api_v1_log_query_proto_msgTypes[5].OneofWrappers = []any{
		(*LogQueryRequest_TextLogQueries)(nil),
	}
	file_sandboxes_api_v1_log_query_proto_msgTypes[6].OneofWrappers = []any{
		(*LogQueryResponse_TextLogBatches)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_log_query_proto_rawDesc), len(file_sandboxes_api_v1_log_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_log_query_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_log_query_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_log_query_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_log_query_proto = out.File
	file_sandboxes_api_v1_log_query_proto_goTypes = nil
	file_sandboxes_api_v1_log_query_proto_depIdxs = nil
}
