// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/process.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Process_RestartPolicy_Strategy int32

const (
	Process_RestartPolicy_DEFAULT Process_RestartPolicy_Strategy = 0 // Always restart
	Process_RestartPolicy_NEVER   Process_RestartPolicy_Strategy = 1 // Never restart
	Process_RestartPolicy_FAILED  Process_RestartPolicy_Strategy = 2 // Only when failed
)

// Enum value maps for Process_RestartPolicy_Strategy.
var (
	Process_RestartPolicy_Strategy_name = map[int32]string{
		0: "DEFAULT",
		1: "NEVER",
		2: "FAILED",
	}
	Process_RestartPolicy_Strategy_value = map[string]int32{
		"DEFAULT": 0,
		"NEVER":   1,
		"FAILED":  2,
	}
)

func (x Process_RestartPolicy_Strategy) Enum() *Process_RestartPolicy_Strategy {
	p := new(Process_RestartPolicy_Strategy)
	*p = x
	return p
}

func (x Process_RestartPolicy_Strategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Process_RestartPolicy_Strategy) Descriptor() protoreflect.EnumDescriptor {
	return file_sandboxes_api_v1_process_proto_enumTypes[0].Descriptor()
}

func (Process_RestartPolicy_Strategy) Type() protoreflect.EnumType {
	return &file_sandboxes_api_v1_process_proto_enumTypes[0]
}

func (x Process_RestartPolicy_Strategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Process_RestartPolicy_Strategy.Descriptor instead.
func (Process_RestartPolicy_Strategy) EnumDescriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_process_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Process_Status_State int32

const (
	Process_Status_UNKNOWN Process_Status_State = 0
	Process_Status_RUNNING Process_Status_State = 1
	Process_Status_STOPPED Process_Status_State = 2
)

// Enum value maps for Process_Status_State.
var (
	Process_Status_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "RUNNING",
		2: "STOPPED",
	}
	Process_Status_State_value = map[string]int32{
		"UNKNOWN": 0,
		"RUNNING": 1,
		"STOPPED": 2,
	}
)

func (x Process_Status_State) Enum() *Process_Status_State {
	p := new(Process_Status_State)
	*p = x
	return p
}

func (x Process_Status_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Process_Status_State) Descriptor() protoreflect.EnumDescriptor {
	return file_sandboxes_api_v1_process_proto_enumTypes[1].Descriptor()
}

func (Process_Status_State) Type() protoreflect.EnumType {
	return &file_sandboxes_api_v1_process_proto_enumTypes[1]
}

func (x Process_Status_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Process_Status_State.Descriptor instead.
func (Process_Status_State) EnumDescriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_process_proto_rawDescGZIP(), []int{0, 3, 0}
}

type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *Process_Spec          `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *Process_Status        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_process_proto_rawDescGZIP(), []int{0}
}

func (x *Process) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Process) GetSpec() *Process_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Process) GetStatus() *Process_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ProcessCtl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Ctl:
	//
	//	*ProcessCtl_Signal_
	//	*ProcessCtl_WindowSize_
	Ctl           isProcessCtl_Ctl `protobuf_oneof:"ctl"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCtl) Reset() {
	*x = ProcessCtl{}
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCtl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCtl) ProtoMessage() {}

func (x *ProcessCtl) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCtl.ProtoReflect.Descriptor instead.
func (*ProcessCtl) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_process_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessCtl) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessCtl) GetCtl() isProcessCtl_Ctl {
	if x != nil {
		return x.Ctl
	}
	return nil
}

func (x *ProcessCtl) GetSignal() *ProcessCtl_Signal {
	if x != nil {
		if x, ok := x.Ctl.(*ProcessCtl_Signal_); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *ProcessCtl) GetWindowSize() *ProcessCtl_WindowSize {
	if x != nil {
		if x, ok := x.Ctl.(*ProcessCtl_WindowSize_); ok {
			return x.WindowSize
		}
	}
	return nil
}

type isProcessCtl_Ctl interface {
	isProcessCtl_Ctl()
}

type ProcessCtl_Signal_ struct {
	Signal *ProcessCtl_Signal `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

type ProcessCtl_WindowSize_ struct {
	WindowSize *ProcessCtl_WindowSize `protobuf:"bytes,3,opt,name=window_size,json=windowSize,proto3,oneof"`
}

func (*ProcessCtl_Signal_) isProcessCtl_Ctl() {}

func (*ProcessCtl_WindowSize_) isProcessCtl_Ctl() {}

type Process_Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process_Identity) Reset() {
	*x = Process_Identity{}
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process_Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_Identity) ProtoMessage() {}

func (x *Process_Identity) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_Identity.ProtoReflect.Descriptor instead.
func (*Process_Identity) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_process_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Process_Identity) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Process_RestartPolicy struct {
	state    protoimpl.MessageState         `protogen:"open.v1"`
	Strategy Process_RestartPolicy_Strategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=sandboxes.api.v1.Process_RestartPolicy_Strategy" json:"strategy,omitempty"`
	// Restart delay.
	RestartDelay *durationpb.Duration `protobuf:"bytes,2,opt,name=restart_delay,json=restartDelay,proto3" json:"restart_delay,omitempty"`
	// If positive, set the maximum count of restarts.
	RestartLimit  int32 `protobuf:"varint,3,opt,name=restart_limit,json=restartLimit,proto3" json:"restart_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process_RestartPolicy) Reset() {
	*x = Process_RestartPolicy{}
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process_RestartPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_RestartPolicy) ProtoMessage() {}

func (x *Process_RestartPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_RestartPolicy.ProtoReflect.Descriptor instead.
func (*Process_RestartPolicy) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_process_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Process_RestartPolicy) GetStrategy() Process_RestartPolicy_Strategy {
	if x != nil {
		return x.Strategy
	}
	return Process_RestartPolicy_DEFAULT
}

func (x *Process_RestartPolicy) GetRestartDelay() *durationpb.Duration {
	if x != nil {
		return x.RestartDelay
	}
	return nil
}

func (x *Process_RestartPolicy) GetRestartLimit() int32 {
	if x != nil {
		return x.RestartLimit
	}
	return 0
}

type Process_Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The argv used in execv syscall.
	Argv []string `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	// List of environment variables, each entry is KEY=VALUE.
	Env []string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty"`
	// Working directory.
	WorkingDir string `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// User ID to run the process.
	Identity      *Process_Identity      `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	RestartPolicy *Process_RestartPolicy `protobuf:"bytes,5,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	// Graceful period to wait before forcible kill.
	// If unspecified, the default value will be used.
	// If zero, the process will be killed immediately (sent SIGKILL without SIGTERM).
	StopGracefulPeriod *durationpb.Duration `protobuf:"bytes,6,opt,name=stop_graceful_period,json=stopGracefulPeriod,proto3" json:"stop_graceful_period,omitempty"`
	// The cron schedule. If set this is a job,
	// and restart_policy.strategy is ignored (always DEFAULT).
	Schedule string `protobuf:"bytes,7,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// If false, the process will be stopped (job unscheduled).
	Enabled bool `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Allocate a TTY for the process.
	// The process management may ignore this field.
	Tty           bool `protobuf:"varint,9,opt,name=tty,proto3" json:"tty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process_Spec) Reset() {
	*x = Process_Spec{}
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_Spec) ProtoMessage() {}

func (x *Process_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_Spec.ProtoReflect.Descriptor instead.
func (*Process_Spec) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_process_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Process_Spec) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *Process_Spec) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Process_Spec) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *Process_Spec) GetIdentity() *Process_Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Process_Spec) GetRestartPolicy() *Process_RestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return nil
}

func (x *Process_Spec) GetStopGracefulPeriod() *durationpb.Duration {
	if x != nil {
		return x.StopGracefulPeriod
	}
	return nil
}

func (x *Process_Spec) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *Process_Spec) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Process_Spec) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

type Process_Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State Process_Status_State   `protobuf:"varint,1,opt,name=state,proto3,enum=sandboxes.api.v1.Process_Status_State" json:"state,omitempty"`
	// The process ID, only available when state is RUNNING.
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// The actual working directory.
	Cwd string `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// The actual UID.
	Uid uint32 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	// The actual GID.
	Gid uint32 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	// The time when the process is created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The last time when start is attempted.
	LastStartedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_started_at,json=lastStartedAt,proto3" json:"last_started_at,omitempty"`
	// The last time when the process exited.
	LastExitedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_exited_at,json=lastExitedAt,proto3" json:"last_exited_at,omitempty"`
	// Detailed error if last start attempt failed.
	StartError *Error `protobuf:"bytes,9,opt,name=start_error,json=startError,proto3" json:"start_error,omitempty"`
	// Count of restart attempts.
	RestartCount int32 `protobuf:"varint,10,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	// The exit status when the last time process exited.
	ExitStatus    uint32 `protobuf:"varint,11,opt,name=exit_status,json=exitStatus,proto3" json:"exit_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process_Status) Reset() {
	*x = Process_Status{}
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_Status) ProtoMessage() {}

func (x *Process_Status) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_Status.ProtoReflect.Descriptor instead.
func (*Process_Status) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_process_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Process_Status) GetState() Process_Status_State {
	if x != nil {
		return x.State
	}
	return Process_Status_UNKNOWN
}

func (x *Process_Status) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process_Status) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Process_Status) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Process_Status) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Process_Status) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Process_Status) GetLastStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStartedAt
	}
	return nil
}

func (x *Process_Status) GetLastExitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastExitedAt
	}
	return nil
}

func (x *Process_Status) GetStartError() *Error {
	if x != nil {
		return x.StartError
	}
	return nil
}

func (x *Process_Status) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *Process_Status) GetExitStatus() uint32 {
	if x != nil {
		return x.ExitStatus
	}
	return 0
}

type ProcessCtl_Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        uint32                 `protobuf:"varint,1,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCtl_Signal) Reset() {
	*x = ProcessCtl_Signal{}
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCtl_Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCtl_Signal) ProtoMessage() {}

func (x *ProcessCtl_Signal) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCtl_Signal.ProtoReflect.Descriptor instead.
func (*ProcessCtl_Signal) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_process_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ProcessCtl_Signal) GetSignal() uint32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type ProcessCtl_WindowSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          int32                  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	XPixel        int32                  `protobuf:"varint,3,opt,name=x_pixel,json=xPixel,proto3" json:"x_pixel,omitempty"` // Width in pixels.
	YPixel        int32                  `protobuf:"varint,4,opt,name=y_pixel,json=yPixel,proto3" json:"y_pixel,omitempty"` // Height in pixels.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCtl_WindowSize) Reset() {
	*x = ProcessCtl_WindowSize{}
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCtl_WindowSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCtl_WindowSize) ProtoMessage() {}

func (x *ProcessCtl_WindowSize) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_process_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCtl_WindowSize.ProtoReflect.Descriptor instead.
func (*ProcessCtl_WindowSize) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_process_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ProcessCtl_WindowSize) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ProcessCtl_WindowSize) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ProcessCtl_WindowSize) GetXPixel() int32 {
	if x != nil {
		return x.XPixel
	}
	return 0
}

func (x *ProcessCtl_WindowSize) GetYPixel() int32 {
	if x != nil {
		return x.YPixel
	}
	return 0
}

var File_sandboxes_api_v1_process_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_process_proto_rawDesc = "" +
	"\n" +
	"\x1esandboxes/api/v1/process.proto\x12\x10sandboxes.api.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dsandboxes/api/v1/common.proto\"\x95\n" +
	"\n" +
	"\aProcess\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x04spec\x18\x02 \x01(\v2\x1e.sandboxes.api.v1.Process.SpecR\x04spec\x128\n" +
	"\x06status\x18\x03 \x01(\v2 .sandboxes.api.v1.Process.StatusR\x06status\x1a\x1c\n" +
	"\bIdentity\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x1a\xf2\x01\n" +
	"\rRestartPolicy\x12L\n" +
	"\bstrategy\x18\x01 \x01(\x0e20.sandboxes.api.v1.Process.RestartPolicy.StrategyR\bstrategy\x12>\n" +
	"\rrestart_delay\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\frestartDelay\x12#\n" +
	"\rrestart_limit\x18\x03 \x01(\x05R\frestartLimit\".\n" +
	"\bStrategy\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\t\n" +
	"\x05NEVER\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x1a\xf2\x02\n" +
	"\x04Spec\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12\x10\n" +
	"\x03env\x18\x02 \x03(\tR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12>\n" +
	"\bidentity\x18\x04 \x01(\v2\".sandboxes.api.v1.Process.IdentityR\bidentity\x12N\n" +
	"\x0erestart_policy\x18\x05 \x01(\v2'.sandboxes.api.v1.Process.RestartPolicyR\rrestartPolicy\x12K\n" +
	"\x14stop_graceful_period\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x12stopGracefulPeriod\x12\x1a\n" +
	"\bschedule\x18\a \x01(\tR\bschedule\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12\x10\n" +
	"\x03tty\x18\t \x01(\bR\x03tty\x1a\xff\x03\n" +
	"\x06Status\x12<\n" +
	"\x05state\x18\x01 \x01(\x0e2&.sandboxes.api.v1.Process.Status.StateR\x05state\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\x0flast_started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastStartedAt\x12@\n" +
	"\x0elast_exited_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\flastExitedAt\x128\n" +
	"\vstart_error\x18\t \x01(\v2\x17.sandboxes.api.v1.ErrorR\n" +
	"startError\x12#\n" +
	"\rrestart_count\x18\n" +
	" \x01(\x05R\frestartCount\x12\x1f\n" +
	"\vexit_status\x18\v \x01(\rR\n" +
	"exitStatus\".\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\v\n" +
	"\aSTOPPED\x10\x02\"\xbc\x02\n" +
	"\n" +
	"ProcessCtl\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\x06signal\x18\x02 \x01(\v2#.sandboxes.api.v1.ProcessCtl.SignalH\x00R\x06signal\x12J\n" +
	"\vwindow_size\x18\x03 \x01(\v2'.sandboxes.api.v1.ProcessCtl.WindowSizeH\x00R\n" +
	"windowSize\x1a \n" +
	"\x06Signal\x12\x16\n" +
	"\x06signal\x18\x01 \x01(\rR\x06signal\x1af\n" +
	"\n" +
	"WindowSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x17\n" +
	"\ax_pixel\x18\x03 \x01(\x05R\x06xPixel\x12\x17\n" +
	"\ay_pixel\x18\x04 \x01(\x05R\x06yPixelB\x05\n" +
	"\x03ctlB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_process_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_process_proto_rawDescData []byte
)

func file_sandboxes_api_v1_process_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_process_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_process_proto_rawDesc), len(file_sandboxes_api_v1_process_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_process_proto_rawDescData
}

var file_sandboxes_api_v1_process_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sandboxes_api_v1_process_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sandboxes_api_v1_process_proto_goTypes = []any{
	(Process_RestartPolicy_Strategy)(0), // 0: sandboxes.api.v1.Process.RestartPolicy.Strategy
	(Process_Status_State)(0),           // 1: sandboxes.api.v1.Process.Status.State
	(*Process)(nil),                     // 2: sandboxes.api.v1.Process
	(*ProcessCtl)(nil),                  // 3: sandboxes.api.v1.ProcessCtl
	(*Process_Identity)(nil),            // 4: sandboxes.api.v1.Process.Identity
	(*Process_RestartPolicy)(nil),       // 5: sandboxes.api.v1.Process.RestartPolicy
	(*Process_Spec)(nil),                // 6: sandboxes.api.v1.Process.Spec
	(*Process_Status)(nil),              // 7: sandboxes.api.v1.Process.Status
	(*ProcessCtl_Signal)(nil),           // 8: sandboxes.api.v1.ProcessCtl.Signal
	(*ProcessCtl_WindowSize)(nil),       // 9: sandboxes.api.v1.ProcessCtl.WindowSize
	(*durationpb.Duration)(nil),         // 10: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
	(*Error)(nil),                       // 12: sandboxes.api.v1.Error
}
var file_sandboxes_api_v1_process_proto_depIdxs = []int32{
	6,  // 0: sandboxes.api.v1.Process.spec:type_name -> sandboxes.api.v1.Process.Spec
	7,  // 1: sandboxes.api.v1.Process.status:type_name -> sandboxes.api.v1.Process.Status
	8,  // 2: sandboxes.api.v1.ProcessCtl.signal:type_name -> sandboxes.api.v1.ProcessCtl.Signal
	9,  // 3: sandboxes.api.v1.ProcessCtl.window_size:type_name -> sandboxes.api.v1.ProcessCtl.WindowSize
	0,  // 4: sandboxes.api.v1.Process.RestartPolicy.strategy:type_name -> sandboxes.api.v1.Process.RestartPolicy.Strategy
	10, // 5: sandboxes.api.v1.Process.RestartPolicy.restart_delay:type_name -> google.protobuf.Duration
	4,  // 6: sandboxes.api.v1.Process.Spec.identity:type_name -> sandboxes.api.v1.Process.Identity
	5,  // 7: sandboxes.api.v1.Process.Spec.restart_policy:type_name -> sandboxes.api.v1.Process.RestartPolicy
	10, // 8: sandboxes.api.v1.Process.Spec.stop_graceful_period:type_name -> google.protobuf.Duration
	1,  // 9: sandboxes.api.v1.Process.Status.state:type_name -> sandboxes.api.v1.Process.Status.State
	11, // 10: sandboxes.api.v1.Process.Status.created_at:type_name -> google.protobuf.Timestamp
	11, // 11: sandboxes.api.v1.Process.Status.last_started_at:type_name -> google.protobuf.Timestamp
	11, // 12: sandboxes.api.v1.Process.Status.last_exited_at:type_name -> google.protobuf.Timestamp
	12, // 13: sandboxes.api.v1.Process.Status.start_error:type_name -> sandboxes.api.v1.Error
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_process_proto_init() }
func file_sandboxes_api_v1_process_proto_init() {
	if File_sandboxes_api_v1_process_proto != nil {
		return
	}
	file_sandboxes_api_v1_common_proto_init()
	file_sandboxes_api_v1_process_proto_msgTypes[1].OneofWrappers = []any{
		(*ProcessCtl_Signal_)(nil),
		(*ProcessCtl_WindowSize_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_process_proto_rawDesc), len(file_sandboxes_api_v1_process_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_process_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_process_proto_depIdxs,
		EnumInfos:         file_sandboxes_api_v1_process_proto_enumTypes,
		MessageInfos:      file_sandboxes_api_v1_process_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_process_proto = out.File
	file_sandboxes_api_v1_process_proto_goTypes = nil
	file_sandboxes_api_v1_process_proto_depIdxs = nil
}
