// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/resource.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic resource object.
// A Resource is an opaque container wrap content of certain type which is
// specified in content.type_url (when processing, only the part after the
// last "/" is respected, the prefixing URL like "http://types.googapis.com/"
// is ignored and discarded.)
// A Resource may have one of the following scopes:
// - Org-level: when org_id is specified, it's an org-level resource;
// - System-level: when org_id is empty and meta.owner unspecified, it's an system-level resource;
// - User-level: when org_id is empty, meta.owner is specified.
// The scope of a resource always contains the type of the resource, e.g.
// - resources/RESOURCE-TYPE/orgs/ORG-ID: an org-level resource;
// - resources/RESOURCE-TYPE: a system-level resource;
// - resources/RESOURCE-TYPE/users/USER-ID: a user-level resource.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *ObjectMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// DEPRECATED, use meta.hierarchy.
	// If specified, it's an org-level resource.
	// Otherwise, it's a system-level resource if meta.owner is unspecified,
	// or user-level if meta.owner is specified.
	OrgId   string     `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Content *anypb.Any `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// The runtime status which is not persisted.
	Status        *anypb.Any `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_sandboxes_api_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Resource) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Resource) GetContent() *anypb.Any {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Resource) GetStatus() *anypb.Any {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_sandboxes_api_v1_resource_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x1fsandboxes/api/v1/resource.proto\x12\x10sandboxes.api.v1\x1a\x19google/protobuf/any.proto\x1a\x1dsandboxes/api/v1/object.proto\"\xb1\x01\n" +
	"\bResource\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.sandboxes.api.v1.ObjectMetaR\x04meta\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12.\n" +
	"\acontent\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\acontent\x12,\n" +
	"\x06status\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x06statusB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_resource_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_resource_proto_rawDescData []byte
)

func file_sandboxes_api_v1_resource_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_resource_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_proto_rawDesc), len(file_sandboxes_api_v1_resource_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_resource_proto_rawDescData
}

var file_sandboxes_api_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sandboxes_api_v1_resource_proto_goTypes = []any{
	(*Resource)(nil),   // 0: sandboxes.api.v1.Resource
	(*ObjectMeta)(nil), // 1: sandboxes.api.v1.ObjectMeta
	(*anypb.Any)(nil),  // 2: google.protobuf.Any
}
var file_sandboxes_api_v1_resource_proto_depIdxs = []int32{
	1, // 0: sandboxes.api.v1.Resource.meta:type_name -> sandboxes.api.v1.ObjectMeta
	2, // 1: sandboxes.api.v1.Resource.content:type_name -> google.protobuf.Any
	2, // 2: sandboxes.api.v1.Resource.status:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_resource_proto_init() }
func file_sandboxes_api_v1_resource_proto_init() {
	if File_sandboxes_api_v1_resource_proto != nil {
		return
	}
	file_sandboxes_api_v1_object_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_proto_rawDesc), len(file_sandboxes_api_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_resource_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_resource_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_resource_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_resource_proto = out.File
	file_sandboxes_api_v1_resource_proto_goTypes = nil
	file_sandboxes_api_v1_resource_proto_depIdxs = nil
}
