// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/resource_connectedinfra.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A connected infrastructure that the sandbox system have access to.
// A user is able to connect an infrastructure to the sandbox system and leverage
// extensive development features.
type ConnectedInfra struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Auth  *ConnectedInfra_Auth   `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	// Types that are valid to be assigned to Infra:
	//
	//	*ConnectedInfra_KubernetesCluster_
	Infra         isConnectedInfra_Infra `protobuf_oneof:"infra"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectedInfra) Reset() {
	*x = ConnectedInfra{}
	mi := &file_sandboxes_api_v1_resource_connectedinfra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedInfra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedInfra) ProtoMessage() {}

func (x *ConnectedInfra) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_connectedinfra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedInfra.ProtoReflect.Descriptor instead.
func (*ConnectedInfra) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_connectedinfra_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectedInfra) GetAuth() *ConnectedInfra_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ConnectedInfra) GetInfra() isConnectedInfra_Infra {
	if x != nil {
		return x.Infra
	}
	return nil
}

func (x *ConnectedInfra) GetKubernetesCluster() *ConnectedInfra_KubernetesCluster {
	if x != nil {
		if x, ok := x.Infra.(*ConnectedInfra_KubernetesCluster_); ok {
			return x.KubernetesCluster
		}
	}
	return nil
}

type isConnectedInfra_Infra interface {
	isConnectedInfra_Infra()
}

type ConnectedInfra_KubernetesCluster_ struct {
	KubernetesCluster *ConnectedInfra_KubernetesCluster `protobuf:"bytes,10,opt,name=kubernetes_cluster,json=kubernetesCluster,proto3,oneof"`
}

func (*ConnectedInfra_KubernetesCluster_) isConnectedInfra_Infra() {}

type ConnectedInfra_Auth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the keypair used by the connector to issue the initial
	// token for requesting a certificate for connection.
	// Unsetting the public key revokes the access of the connector, and the
	// bridge service may also actively terminates active connections if the
	// access of the corresponding infra is revoked.
	ConnectorPublicKey string `protobuf:"bytes,1,opt,name=connector_public_key,json=connectorPublicKey,proto3" json:"connector_public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConnectedInfra_Auth) Reset() {
	*x = ConnectedInfra_Auth{}
	mi := &file_sandboxes_api_v1_resource_connectedinfra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedInfra_Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedInfra_Auth) ProtoMessage() {}

func (x *ConnectedInfra_Auth) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_connectedinfra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedInfra_Auth.ProtoReflect.Descriptor instead.
func (*ConnectedInfra_Auth) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_connectedinfra_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ConnectedInfra_Auth) GetConnectorPublicKey() string {
	if x != nil {
		return x.ConnectorPublicKey
	}
	return ""
}

type ConnectedInfra_KubernetesCluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectedInfra_KubernetesCluster) Reset() {
	*x = ConnectedInfra_KubernetesCluster{}
	mi := &file_sandboxes_api_v1_resource_connectedinfra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedInfra_KubernetesCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedInfra_KubernetesCluster) ProtoMessage() {}

func (x *ConnectedInfra_KubernetesCluster) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_connectedinfra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedInfra_KubernetesCluster.ProtoReflect.Descriptor instead.
func (*ConnectedInfra_KubernetesCluster) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_connectedinfra_proto_rawDescGZIP(), []int{0, 1}
}

var File_sandboxes_api_v1_resource_connectedinfra_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_resource_connectedinfra_proto_rawDesc = "" +
	"\n" +
	".sandboxes/api/v1/resource_connectedinfra.proto\x12\x10sandboxes.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x02\n" +
	"\x0eConnectedInfra\x129\n" +
	"\x04auth\x18\x01 \x01(\v2%.sandboxes.api.v1.ConnectedInfra.AuthR\x04auth\x12c\n" +
	"\x12kubernetes_cluster\x18\n" +
	" \x01(\v22.sandboxes.api.v1.ConnectedInfra.KubernetesClusterH\x00R\x11kubernetesCluster\x1a8\n" +
	"\x04Auth\x120\n" +
	"\x14connector_public_key\x18\x01 \x01(\tR\x12connectorPublicKey\x1a\x13\n" +
	"\x11KubernetesClusterB\a\n" +
	"\x05infraB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_resource_connectedinfra_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_resource_connectedinfra_proto_rawDescData []byte
)

func file_sandboxes_api_v1_resource_connectedinfra_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_resource_connectedinfra_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_resource_connectedinfra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_connectedinfra_proto_rawDesc), len(file_sandboxes_api_v1_resource_connectedinfra_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_resource_connectedinfra_proto_rawDescData
}

var file_sandboxes_api_v1_resource_connectedinfra_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sandboxes_api_v1_resource_connectedinfra_proto_goTypes = []any{
	(*ConnectedInfra)(nil),                   // 0: sandboxes.api.v1.ConnectedInfra
	(*ConnectedInfra_Auth)(nil),              // 1: sandboxes.api.v1.ConnectedInfra.Auth
	(*ConnectedInfra_KubernetesCluster)(nil), // 2: sandboxes.api.v1.ConnectedInfra.KubernetesCluster
}
var file_sandboxes_api_v1_resource_connectedinfra_proto_depIdxs = []int32{
	1, // 0: sandboxes.api.v1.ConnectedInfra.auth:type_name -> sandboxes.api.v1.ConnectedInfra.Auth
	2, // 1: sandboxes.api.v1.ConnectedInfra.kubernetes_cluster:type_name -> sandboxes.api.v1.ConnectedInfra.KubernetesCluster
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_resource_connectedinfra_proto_init() }
func file_sandboxes_api_v1_resource_connectedinfra_proto_init() {
	if File_sandboxes_api_v1_resource_connectedinfra_proto != nil {
		return
	}
	file_sandboxes_api_v1_resource_connectedinfra_proto_msgTypes[0].OneofWrappers = []any{
		(*ConnectedInfra_KubernetesCluster_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_connectedinfra_proto_rawDesc), len(file_sandboxes_api_v1_resource_connectedinfra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_resource_connectedinfra_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_resource_connectedinfra_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_resource_connectedinfra_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_resource_connectedinfra_proto = out.File
	file_sandboxes_api_v1_resource_connectedinfra_proto_goTypes = nil
	file_sandboxes_api_v1_resource_connectedinfra_proto_depIdxs = nil
}
