// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/resource_quotacontroller.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuotaController struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An allocation is a pair of <objectID, units>.
	Allocations map[string]int32 `protobuf:"bytes,1,rep,name=allocations,proto3" json:"allocations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Depending on the actual controller the value of limit can be used
	// to control the allocation or for other purposes.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaController) Reset() {
	*x = QuotaController{}
	mi := &file_sandboxes_api_v1_resource_quotacontroller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaController) ProtoMessage() {}

func (x *QuotaController) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_quotacontroller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaController.ProtoReflect.Descriptor instead.
func (*QuotaController) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_quotacontroller_proto_rawDescGZIP(), []int{0}
}

func (x *QuotaController) GetAllocations() map[string]int32 {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *QuotaController) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_sandboxes_api_v1_resource_quotacontroller_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_resource_quotacontroller_proto_rawDesc = "" +
	"\n" +
	"/sandboxes/api/v1/resource_quotacontroller.proto\x12\x10sandboxes.api.v1\"\xbd\x01\n" +
	"\x0fQuotaController\x12T\n" +
	"\vallocations\x18\x01 \x03(\v22.sandboxes.api.v1.QuotaController.AllocationsEntryR\vallocations\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x1a>\n" +
	"\x10AllocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_resource_quotacontroller_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_resource_quotacontroller_proto_rawDescData []byte
)

func file_sandboxes_api_v1_resource_quotacontroller_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_resource_quotacontroller_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_resource_quotacontroller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_quotacontroller_proto_rawDesc), len(file_sandboxes_api_v1_resource_quotacontroller_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_resource_quotacontroller_proto_rawDescData
}

var file_sandboxes_api_v1_resource_quotacontroller_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sandboxes_api_v1_resource_quotacontroller_proto_goTypes = []any{
	(*QuotaController)(nil), // 0: sandboxes.api.v1.QuotaController
	nil,                     // 1: sandboxes.api.v1.QuotaController.AllocationsEntry
}
var file_sandboxes_api_v1_resource_quotacontroller_proto_depIdxs = []int32{
	1, // 0: sandboxes.api.v1.QuotaController.allocations:type_name -> sandboxes.api.v1.QuotaController.AllocationsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_resource_quotacontroller_proto_init() }
func file_sandboxes_api_v1_resource_quotacontroller_proto_init() {
	if File_sandboxes_api_v1_resource_quotacontroller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_quotacontroller_proto_rawDesc), len(file_sandboxes_api_v1_resource_quotacontroller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_resource_quotacontroller_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_resource_quotacontroller_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_resource_quotacontroller_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_resource_quotacontroller_proto = out.File
	file_sandboxes_api_v1_resource_quotacontroller_proto_goTypes = nil
	file_sandboxes_api_v1_resource_quotacontroller_proto_depIdxs = nil
}
