// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/resource_loginprovider.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Controls how to pass client_id and client_secret.
type LoginProvider_OAuth2_AuthStyle int32

const (
	// Auto detect.
	LoginProvider_OAuth2_AUTO LoginProvider_OAuth2_AuthStyle = 0
	// Use POST body as application/x-www-form-urlencoded.
	LoginProvider_OAuth2_PARAMS LoginProvider_OAuth2_AuthStyle = 1
	// Use Authorization: Basic BASE64(client_id:client_secret).
	LoginProvider_OAuth2_HEADER LoginProvider_OAuth2_AuthStyle = 2
)

// Enum value maps for LoginProvider_OAuth2_AuthStyle.
var (
	LoginProvider_OAuth2_AuthStyle_name = map[int32]string{
		0: "AUTO",
		1: "PARAMS",
		2: "HEADER",
	}
	LoginProvider_OAuth2_AuthStyle_value = map[string]int32{
		"AUTO":   0,
		"PARAMS": 1,
		"HEADER": 2,
	}
)

func (x LoginProvider_OAuth2_AuthStyle) Enum() *LoginProvider_OAuth2_AuthStyle {
	p := new(LoginProvider_OAuth2_AuthStyle)
	*p = x
	return p
}

func (x LoginProvider_OAuth2_AuthStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginProvider_OAuth2_AuthStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_sandboxes_api_v1_resource_loginprovider_proto_enumTypes[0].Descriptor()
}

func (LoginProvider_OAuth2_AuthStyle) Type() protoreflect.EnumType {
	return &file_sandboxes_api_v1_resource_loginprovider_proto_enumTypes[0]
}

func (x LoginProvider_OAuth2_AuthStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginProvider_OAuth2_AuthStyle.Descriptor instead.
func (LoginProvider_OAuth2_AuthStyle) EnumDescriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 0, 0}
}

type LoginProvider_OAuth2_AccessType int32

const (
	LoginProvider_OAuth2_UNSPECIFIED LoginProvider_OAuth2_AccessType = 0
	LoginProvider_OAuth2_ONLINE      LoginProvider_OAuth2_AccessType = 1
	LoginProvider_OAuth2_OFFLINE     LoginProvider_OAuth2_AccessType = 2
)

// Enum value maps for LoginProvider_OAuth2_AccessType.
var (
	LoginProvider_OAuth2_AccessType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ONLINE",
		2: "OFFLINE",
	}
	LoginProvider_OAuth2_AccessType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ONLINE":      1,
		"OFFLINE":     2,
	}
)

func (x LoginProvider_OAuth2_AccessType) Enum() *LoginProvider_OAuth2_AccessType {
	p := new(LoginProvider_OAuth2_AccessType)
	*p = x
	return p
}

func (x LoginProvider_OAuth2_AccessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginProvider_OAuth2_AccessType) Descriptor() protoreflect.EnumDescriptor {
	return file_sandboxes_api_v1_resource_loginprovider_proto_enumTypes[1].Descriptor()
}

func (LoginProvider_OAuth2_AccessType) Type() protoreflect.EnumType {
	return &file_sandboxes_api_v1_resource_loginprovider_proto_enumTypes[1]
}

func (x LoginProvider_OAuth2_AccessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginProvider_OAuth2_AccessType.Descriptor instead.
func (LoginProvider_OAuth2_AccessType) EnumDescriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 0, 1}
}

type LoginProvider_OAuth2_PKCE_Method int32

const (
	// PKCE is disabled.
	LoginProvider_OAuth2_PKCE_NONE LoginProvider_OAuth2_PKCE_Method = 0
	LoginProvider_OAuth2_PKCE_S256 LoginProvider_OAuth2_PKCE_Method = 1
)

// Enum value maps for LoginProvider_OAuth2_PKCE_Method.
var (
	LoginProvider_OAuth2_PKCE_Method_name = map[int32]string{
		0: "NONE",
		1: "S256",
	}
	LoginProvider_OAuth2_PKCE_Method_value = map[string]int32{
		"NONE": 0,
		"S256": 1,
	}
)

func (x LoginProvider_OAuth2_PKCE_Method) Enum() *LoginProvider_OAuth2_PKCE_Method {
	p := new(LoginProvider_OAuth2_PKCE_Method)
	*p = x
	return p
}

func (x LoginProvider_OAuth2_PKCE_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginProvider_OAuth2_PKCE_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_sandboxes_api_v1_resource_loginprovider_proto_enumTypes[2].Descriptor()
}

func (LoginProvider_OAuth2_PKCE_Method) Type() protoreflect.EnumType {
	return &file_sandboxes_api_v1_resource_loginprovider_proto_enumTypes[2]
}

func (x LoginProvider_OAuth2_PKCE_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginProvider_OAuth2_PKCE_Method.Descriptor instead.
func (LoginProvider_OAuth2_PKCE_Method) EnumDescriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

// A third-party login service that a user can use to obtain a managed access token (a Secret of type Token).
type LoginProvider struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Provider      *LoginProvider_Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Policy        *LoginProvider_Policy   `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	State         *LoginProvider_State    `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProvider) Reset() {
	*x = LoginProvider{}
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProvider) ProtoMessage() {}

func (x *LoginProvider) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProvider.ProtoReflect.Descriptor instead.
func (*LoginProvider) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0}
}

func (x *LoginProvider) GetProvider() *LoginProvider_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *LoginProvider) GetPolicy() *LoginProvider_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *LoginProvider) GetState() *LoginProvider_State {
	if x != nil {
		return x.State
	}
	return nil
}

// A general OAuth2 provider.
type LoginProvider_OAuth2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client ID from the provider.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The client secret from the provider.
	// It can be "secret:NAME" to use a secret.
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// The authentication URL (aka login URL).
	AuthUrl string `protobuf:"bytes,3,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	// The URL for tokens.
	TokenUrl  string                         `protobuf:"bytes,4,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	AuthStyle LoginProvider_OAuth2_AuthStyle `protobuf:"varint,5,opt,name=auth_style,json=authStyle,proto3,enum=sandboxes.api.v1.LoginProvider_OAuth2_AuthStyle" json:"auth_style,omitempty"`
	// The scopes for login.
	Scopes []string `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// The PKCE configuration.
	Pkce *LoginProvider_OAuth2_PKCE `protobuf:"bytes,7,opt,name=pkce,proto3" json:"pkce,omitempty"`
	// If specified, this provider must be logged in using a CLI.
	// From Web UI, it should display the CLI for login rather than start the web-based login flow.
	Callback *LoginProvider_OAuth2_Callback `protobuf:"bytes,8,opt,name=callback,proto3" json:"callback,omitempty"`
	// If specified, parameter "access_type" is generated.
	AccessType LoginProvider_OAuth2_AccessType `protobuf:"varint,9,opt,name=access_type,json=accessType,proto3,enum=sandboxes.api.v1.LoginProvider_OAuth2_AccessType" json:"access_type,omitempty"`
	// Additional (query) parameters to append.
	// Each item is in the form of key=val without encoding.
	// If no "=" is present, the whole item will be used as a single parameter.
	Params        []string `protobuf:"bytes,10,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProvider_OAuth2) Reset() {
	*x = LoginProvider_OAuth2{}
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProvider_OAuth2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProvider_OAuth2) ProtoMessage() {}

func (x *LoginProvider_OAuth2) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProvider_OAuth2.ProtoReflect.Descriptor instead.
func (*LoginProvider_OAuth2) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LoginProvider_OAuth2) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LoginProvider_OAuth2) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *LoginProvider_OAuth2) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *LoginProvider_OAuth2) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *LoginProvider_OAuth2) GetAuthStyle() LoginProvider_OAuth2_AuthStyle {
	if x != nil {
		return x.AuthStyle
	}
	return LoginProvider_OAuth2_AUTO
}

func (x *LoginProvider_OAuth2) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *LoginProvider_OAuth2) GetPkce() *LoginProvider_OAuth2_PKCE {
	if x != nil {
		return x.Pkce
	}
	return nil
}

func (x *LoginProvider_OAuth2) GetCallback() *LoginProvider_OAuth2_Callback {
	if x != nil {
		return x.Callback
	}
	return nil
}

func (x *LoginProvider_OAuth2) GetAccessType() LoginProvider_OAuth2_AccessType {
	if x != nil {
		return x.AccessType
	}
	return LoginProvider_OAuth2_UNSPECIFIED
}

func (x *LoginProvider_OAuth2) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type LoginProvider_OAuthRelay struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ProviderName string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Override scopes.
	// If append_scopes is true, these are appended after the default ones.
	// Otherwise use the specified scopes as-is.
	Scopes []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// If true, append the "scopes" to the default ones.
	AppendScopes  bool `protobuf:"varint,3,opt,name=append_scopes,json=appendScopes,proto3" json:"append_scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProvider_OAuthRelay) Reset() {
	*x = LoginProvider_OAuthRelay{}
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProvider_OAuthRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProvider_OAuthRelay) ProtoMessage() {}

func (x *LoginProvider_OAuthRelay) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProvider_OAuthRelay.ProtoReflect.Descriptor instead.
func (*LoginProvider_OAuthRelay) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LoginProvider_OAuthRelay) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *LoginProvider_OAuthRelay) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *LoginProvider_OAuthRelay) GetAppendScopes() bool {
	if x != nil {
		return x.AppendScopes
	}
	return false
}

type LoginProvider_Provider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Provider:
	//
	//	*LoginProvider_Provider_Oauth2
	//	*LoginProvider_Provider_OauthRelay
	Provider      isLoginProvider_Provider_Provider `protobuf_oneof:"provider"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProvider_Provider) Reset() {
	*x = LoginProvider_Provider{}
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProvider_Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProvider_Provider) ProtoMessage() {}

func (x *LoginProvider_Provider) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProvider_Provider.ProtoReflect.Descriptor instead.
func (*LoginProvider_Provider) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 2}
}

func (x *LoginProvider_Provider) GetProvider() isLoginProvider_Provider_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *LoginProvider_Provider) GetOauth2() *LoginProvider_OAuth2 {
	if x != nil {
		if x, ok := x.Provider.(*LoginProvider_Provider_Oauth2); ok {
			return x.Oauth2
		}
	}
	return nil
}

func (x *LoginProvider_Provider) GetOauthRelay() *LoginProvider_OAuthRelay {
	if x != nil {
		if x, ok := x.Provider.(*LoginProvider_Provider_OauthRelay); ok {
			return x.OauthRelay
		}
	}
	return nil
}

type isLoginProvider_Provider_Provider interface {
	isLoginProvider_Provider_Provider()
}

type LoginProvider_Provider_Oauth2 struct {
	Oauth2 *LoginProvider_OAuth2 `protobuf:"bytes,1,opt,name=oauth2,proto3,oneof"`
}

type LoginProvider_Provider_OauthRelay struct {
	OauthRelay *LoginProvider_OAuthRelay `protobuf:"bytes,2,opt,name=oauth_relay,json=oauthRelay,proto3,oneof"`
}

func (*LoginProvider_Provider_Oauth2) isLoginProvider_Provider_Provider() {}

func (*LoginProvider_Provider_OauthRelay) isLoginProvider_Provider_Provider() {}

type LoginProvider_Policy struct {
	state            protoimpl.MessageState                 `protogen:"open.v1"`
	AutoRefreshToken *LoginProvider_Policy_AutoRefreshToken `protobuf:"bytes,1,opt,name=auto_refresh_token,json=autoRefreshToken,proto3" json:"auto_refresh_token,omitempty"`
	TokenValidity    *LoginProvider_Policy_TokenValidity    `protobuf:"bytes,2,opt,name=token_validity,json=tokenValidity,proto3" json:"token_validity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginProvider_Policy) Reset() {
	*x = LoginProvider_Policy{}
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProvider_Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProvider_Policy) ProtoMessage() {}

func (x *LoginProvider_Policy) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProvider_Policy.ProtoReflect.Descriptor instead.
func (*LoginProvider_Policy) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 3}
}

func (x *LoginProvider_Policy) GetAutoRefreshToken() *LoginProvider_Policy_AutoRefreshToken {
	if x != nil {
		return x.AutoRefreshToken
	}
	return nil
}

func (x *LoginProvider_Policy) GetTokenValidity() *LoginProvider_Policy_TokenValidity {
	if x != nil {
		return x.TokenValidity
	}
	return nil
}

type LoginProvider_State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, the provider is disabled (not visible for login),
	// and all issued tokens are inaccessible, with auto-refresh paused (so they may expire).
	Disabled bool `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Detailed error if any.
	Error         *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProvider_State) Reset() {
	*x = LoginProvider_State{}
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProvider_State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProvider_State) ProtoMessage() {}

func (x *LoginProvider_State) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProvider_State.ProtoReflect.Descriptor instead.
func (*LoginProvider_State) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 4}
}

func (x *LoginProvider_State) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *LoginProvider_State) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Proof-Key-for-Code-Exchange (https://www.rfc-editor.org/rfc/rfc7636).
type LoginProvider_OAuth2_PKCE struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The code challenge method.
	Method        LoginProvider_OAuth2_PKCE_Method `protobuf:"varint,1,opt,name=method,proto3,enum=sandboxes.api.v1.LoginProvider_OAuth2_PKCE_Method" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProvider_OAuth2_PKCE) Reset() {
	*x = LoginProvider_OAuth2_PKCE{}
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProvider_OAuth2_PKCE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProvider_OAuth2_PKCE) ProtoMessage() {}

func (x *LoginProvider_OAuth2_PKCE) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProvider_OAuth2_PKCE.ProtoReflect.Descriptor instead.
func (*LoginProvider_OAuth2_PKCE) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *LoginProvider_OAuth2_PKCE) GetMethod() LoginProvider_OAuth2_PKCE_Method {
	if x != nil {
		return x.Method
	}
	return LoginProvider_OAuth2_PKCE_NONE
}

// Special configuration for callback.
type LoginProvider_OAuth2_Callback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The callback host.
	// It must be `localhost` (use any available port) or `localhost:PORT` (use PORT when possible).
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// When port is specified in `host`, only that port can be used.
	// The login will fail if that port is not available.
	// Otherwise, the client may choose an alternative port to serve the callback.
	RestrictPort bool `protobuf:"varint,2,opt,name=restrict_port,json=restrictPort,proto3" json:"restrict_port,omitempty"`
	// If specified, the value must start with "/", and can't be "/", "/login" or "/success".
	// The client callback must use the path strictly.
	// Otherwise, a default callback path "/callback" will be used.
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProvider_OAuth2_Callback) Reset() {
	*x = LoginProvider_OAuth2_Callback{}
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProvider_OAuth2_Callback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProvider_OAuth2_Callback) ProtoMessage() {}

func (x *LoginProvider_OAuth2_Callback) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProvider_OAuth2_Callback.ProtoReflect.Descriptor instead.
func (*LoginProvider_OAuth2_Callback) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *LoginProvider_OAuth2_Callback) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *LoginProvider_OAuth2_Callback) GetRestrictPort() bool {
	if x != nil {
		return x.RestrictPort
	}
	return false
}

func (x *LoginProvider_OAuth2_Callback) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type LoginProvider_Policy_AutoRefreshToken struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// It's only valid if positive,
	// to limit the max number of times a token can be auto-refreshed.
	MaxCount      int32 `protobuf:"varint,2,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProvider_Policy_AutoRefreshToken) Reset() {
	*x = LoginProvider_Policy_AutoRefreshToken{}
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProvider_Policy_AutoRefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProvider_Policy_AutoRefreshToken) ProtoMessage() {}

func (x *LoginProvider_Policy_AutoRefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProvider_Policy_AutoRefreshToken.ProtoReflect.Descriptor instead.
func (*LoginProvider_Policy_AutoRefreshToken) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *LoginProvider_Policy_AutoRefreshToken) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *LoginProvider_Policy_AutoRefreshToken) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

type LoginProvider_Policy_TokenValidity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The max duration a token can be valid/accessible.
	// This valid is independent from the validity of the actual token issued,
	// and the system will pick the shorter value.
	MaxDuration   *durationpb.Duration `protobuf:"bytes,1,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProvider_Policy_TokenValidity) Reset() {
	*x = LoginProvider_Policy_TokenValidity{}
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProvider_Policy_TokenValidity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProvider_Policy_TokenValidity) ProtoMessage() {}

func (x *LoginProvider_Policy_TokenValidity) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProvider_Policy_TokenValidity.ProtoReflect.Descriptor instead.
func (*LoginProvider_Policy_TokenValidity) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (x *LoginProvider_Policy_TokenValidity) GetMaxDuration() *durationpb.Duration {
	if x != nil {
		return x.MaxDuration
	}
	return nil
}

var File_sandboxes_api_v1_resource_loginprovider_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_resource_loginprovider_proto_rawDesc = "" +
	"\n" +
	"-sandboxes/api/v1/resource_loginprovider.proto\x12\x10sandboxes.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1dsandboxes/api/v1/common.proto\"\xc3\r\n" +
	"\rLoginProvider\x12D\n" +
	"\bprovider\x18\x01 \x01(\v2(.sandboxes.api.v1.LoginProvider.ProviderR\bprovider\x12>\n" +
	"\x06policy\x18\x02 \x01(\v2&.sandboxes.api.v1.LoginProvider.PolicyR\x06policy\x12;\n" +
	"\x05state\x18\x03 \x01(\v2%.sandboxes.api.v1.LoginProvider.StateR\x05state\x1a\x97\x06\n" +
	"\x06OAuth2\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x19\n" +
	"\bauth_url\x18\x03 \x01(\tR\aauthUrl\x12\x1b\n" +
	"\ttoken_url\x18\x04 \x01(\tR\btokenUrl\x12O\n" +
	"\n" +
	"auth_style\x18\x05 \x01(\x0e20.sandboxes.api.v1.LoginProvider.OAuth2.AuthStyleR\tauthStyle\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\x12?\n" +
	"\x04pkce\x18\a \x01(\v2+.sandboxes.api.v1.LoginProvider.OAuth2.PKCER\x04pkce\x12K\n" +
	"\bcallback\x18\b \x01(\v2/.sandboxes.api.v1.LoginProvider.OAuth2.CallbackR\bcallback\x12R\n" +
	"\vaccess_type\x18\t \x01(\x0e21.sandboxes.api.v1.LoginProvider.OAuth2.AccessTypeR\n" +
	"accessType\x12\x16\n" +
	"\x06params\x18\n" +
	" \x03(\tR\x06params\x1ap\n" +
	"\x04PKCE\x12J\n" +
	"\x06method\x18\x01 \x01(\x0e22.sandboxes.api.v1.LoginProvider.OAuth2.PKCE.MethodR\x06method\"\x1c\n" +
	"\x06Method\x12\b\n" +
	"\x04NONE\x10\x00\x12\b\n" +
	"\x04S256\x10\x01\x1aW\n" +
	"\bCallback\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12#\n" +
	"\rrestrict_port\x18\x02 \x01(\bR\frestrictPort\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"-\n" +
	"\tAuthStyle\x12\b\n" +
	"\x04AUTO\x10\x00\x12\n" +
	"\n" +
	"\x06PARAMS\x10\x01\x12\n" +
	"\n" +
	"\x06HEADER\x10\x02\"6\n" +
	"\n" +
	"AccessType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\x12\v\n" +
	"\aOFFLINE\x10\x02\x1an\n" +
	"\n" +
	"OAuthRelay\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\x12#\n" +
	"\rappend_scopes\x18\x03 \x01(\bR\fappendScopes\x1a\xa7\x01\n" +
	"\bProvider\x12@\n" +
	"\x06oauth2\x18\x01 \x01(\v2&.sandboxes.api.v1.LoginProvider.OAuth2H\x00R\x06oauth2\x12M\n" +
	"\voauth_relay\x18\x02 \x01(\v2*.sandboxes.api.v1.LoginProvider.OAuthRelayH\x00R\n" +
	"oauthRelayB\n" +
	"\n" +
	"\bprovider\x1a\xe6\x02\n" +
	"\x06Policy\x12e\n" +
	"\x12auto_refresh_token\x18\x01 \x01(\v27.sandboxes.api.v1.LoginProvider.Policy.AutoRefreshTokenR\x10autoRefreshToken\x12[\n" +
	"\x0etoken_validity\x18\x02 \x01(\v24.sandboxes.api.v1.LoginProvider.Policy.TokenValidityR\rtokenValidity\x1aI\n" +
	"\x10AutoRefreshToken\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1b\n" +
	"\tmax_count\x18\x02 \x01(\x05R\bmaxCount\x1aM\n" +
	"\rTokenValidity\x12<\n" +
	"\fmax_duration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\vmaxDuration\x1aR\n" +
	"\x05State\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x17.sandboxes.api.v1.ErrorR\x05errorB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_resource_loginprovider_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_resource_loginprovider_proto_rawDescData []byte
)

func file_sandboxes_api_v1_resource_loginprovider_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_resource_loginprovider_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_resource_loginprovider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_loginprovider_proto_rawDesc), len(file_sandboxes_api_v1_resource_loginprovider_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_resource_loginprovider_proto_rawDescData
}

var file_sandboxes_api_v1_resource_loginprovider_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sandboxes_api_v1_resource_loginprovider_proto_goTypes = []any{
	(LoginProvider_OAuth2_AuthStyle)(0),           // 0: sandboxes.api.v1.LoginProvider.OAuth2.AuthStyle
	(LoginProvider_OAuth2_AccessType)(0),          // 1: sandboxes.api.v1.LoginProvider.OAuth2.AccessType
	(LoginProvider_OAuth2_PKCE_Method)(0),         // 2: sandboxes.api.v1.LoginProvider.OAuth2.PKCE.Method
	(*LoginProvider)(nil),                         // 3: sandboxes.api.v1.LoginProvider
	(*LoginProvider_OAuth2)(nil),                  // 4: sandboxes.api.v1.LoginProvider.OAuth2
	(*LoginProvider_OAuthRelay)(nil),              // 5: sandboxes.api.v1.LoginProvider.OAuthRelay
	(*LoginProvider_Provider)(nil),                // 6: sandboxes.api.v1.LoginProvider.Provider
	(*LoginProvider_Policy)(nil),                  // 7: sandboxes.api.v1.LoginProvider.Policy
	(*LoginProvider_State)(nil),                   // 8: sandboxes.api.v1.LoginProvider.State
	(*LoginProvider_OAuth2_PKCE)(nil),             // 9: sandboxes.api.v1.LoginProvider.OAuth2.PKCE
	(*LoginProvider_OAuth2_Callback)(nil),         // 10: sandboxes.api.v1.LoginProvider.OAuth2.Callback
	(*LoginProvider_Policy_AutoRefreshToken)(nil), // 11: sandboxes.api.v1.LoginProvider.Policy.AutoRefreshToken
	(*LoginProvider_Policy_TokenValidity)(nil),    // 12: sandboxes.api.v1.LoginProvider.Policy.TokenValidity
	(*Error)(nil),               // 13: sandboxes.api.v1.Error
	(*durationpb.Duration)(nil), // 14: google.protobuf.Duration
}
var file_sandboxes_api_v1_resource_loginprovider_proto_depIdxs = []int32{
	6,  // 0: sandboxes.api.v1.LoginProvider.provider:type_name -> sandboxes.api.v1.LoginProvider.Provider
	7,  // 1: sandboxes.api.v1.LoginProvider.policy:type_name -> sandboxes.api.v1.LoginProvider.Policy
	8,  // 2: sandboxes.api.v1.LoginProvider.state:type_name -> sandboxes.api.v1.LoginProvider.State
	0,  // 3: sandboxes.api.v1.LoginProvider.OAuth2.auth_style:type_name -> sandboxes.api.v1.LoginProvider.OAuth2.AuthStyle
	9,  // 4: sandboxes.api.v1.LoginProvider.OAuth2.pkce:type_name -> sandboxes.api.v1.LoginProvider.OAuth2.PKCE
	10, // 5: sandboxes.api.v1.LoginProvider.OAuth2.callback:type_name -> sandboxes.api.v1.LoginProvider.OAuth2.Callback
	1,  // 6: sandboxes.api.v1.LoginProvider.OAuth2.access_type:type_name -> sandboxes.api.v1.LoginProvider.OAuth2.AccessType
	4,  // 7: sandboxes.api.v1.LoginProvider.Provider.oauth2:type_name -> sandboxes.api.v1.LoginProvider.OAuth2
	5,  // 8: sandboxes.api.v1.LoginProvider.Provider.oauth_relay:type_name -> sandboxes.api.v1.LoginProvider.OAuthRelay
	11, // 9: sandboxes.api.v1.LoginProvider.Policy.auto_refresh_token:type_name -> sandboxes.api.v1.LoginProvider.Policy.AutoRefreshToken
	12, // 10: sandboxes.api.v1.LoginProvider.Policy.token_validity:type_name -> sandboxes.api.v1.LoginProvider.Policy.TokenValidity
	13, // 11: sandboxes.api.v1.LoginProvider.State.error:type_name -> sandboxes.api.v1.Error
	2,  // 12: sandboxes.api.v1.LoginProvider.OAuth2.PKCE.method:type_name -> sandboxes.api.v1.LoginProvider.OAuth2.PKCE.Method
	14, // 13: sandboxes.api.v1.LoginProvider.Policy.TokenValidity.max_duration:type_name -> google.protobuf.Duration
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_resource_loginprovider_proto_init() }
func file_sandboxes_api_v1_resource_loginprovider_proto_init() {
	if File_sandboxes_api_v1_resource_loginprovider_proto != nil {
		return
	}
	file_sandboxes_api_v1_common_proto_init()
	file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes[3].OneofWrappers = []any{
		(*LoginProvider_Provider_Oauth2)(nil),
		(*LoginProvider_Provider_OauthRelay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_loginprovider_proto_rawDesc), len(file_sandboxes_api_v1_resource_loginprovider_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_resource_loginprovider_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_resource_loginprovider_proto_depIdxs,
		EnumInfos:         file_sandboxes_api_v1_resource_loginprovider_proto_enumTypes,
		MessageInfos:      file_sandboxes_api_v1_resource_loginprovider_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_resource_loginprovider_proto = out.File
	file_sandboxes_api_v1_resource_loginprovider_proto_goTypes = nil
	file_sandboxes_api_v1_resource_loginprovider_proto_depIdxs = nil
}
