// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/resource_nodepool.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type K8SNodePool_EKS_CapacityType int32

const (
	K8SNodePool_EKS_DEFAULT K8SNodePool_EKS_CapacityType = 0 // ON_DEMAND
	K8SNodePool_EKS_SPOT    K8SNodePool_EKS_CapacityType = 1
)

// Enum value maps for K8SNodePool_EKS_CapacityType.
var (
	K8SNodePool_EKS_CapacityType_name = map[int32]string{
		0: "DEFAULT",
		1: "SPOT",
	}
	K8SNodePool_EKS_CapacityType_value = map[string]int32{
		"DEFAULT": 0,
		"SPOT":    1,
	}
)

func (x K8SNodePool_EKS_CapacityType) Enum() *K8SNodePool_EKS_CapacityType {
	p := new(K8SNodePool_EKS_CapacityType)
	*p = x
	return p
}

func (x K8SNodePool_EKS_CapacityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (K8SNodePool_EKS_CapacityType) Descriptor() protoreflect.EnumDescriptor {
	return file_sandboxes_api_v1_resource_nodepool_proto_enumTypes[0].Descriptor()
}

func (K8SNodePool_EKS_CapacityType) Type() protoreflect.EnumType {
	return &file_sandboxes_api_v1_resource_nodepool_proto_enumTypes[0]
}

func (x K8SNodePool_EKS_CapacityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use K8SNodePool_EKS_CapacityType.Descriptor instead.
func (K8SNodePool_EKS_CapacityType) EnumDescriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 6, 0}
}

// https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengmanagingcapacitytypes.htm
// reserved capacity is not supported at this stage.
type K8SNodePool_OKE_CapacityType int32

const (
	K8SNodePool_OKE_DEFAULT     K8SNodePool_OKE_CapacityType = 0 // ON_DEMAND
	K8SNodePool_OKE_PREEMPTIBLE K8SNodePool_OKE_CapacityType = 1
)

// Enum value maps for K8SNodePool_OKE_CapacityType.
var (
	K8SNodePool_OKE_CapacityType_name = map[int32]string{
		0: "DEFAULT",
		1: "PREEMPTIBLE",
	}
	K8SNodePool_OKE_CapacityType_value = map[string]int32{
		"DEFAULT":     0,
		"PREEMPTIBLE": 1,
	}
)

func (x K8SNodePool_OKE_CapacityType) Enum() *K8SNodePool_OKE_CapacityType {
	p := new(K8SNodePool_OKE_CapacityType)
	*p = x
	return p
}

func (x K8SNodePool_OKE_CapacityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (K8SNodePool_OKE_CapacityType) Descriptor() protoreflect.EnumDescriptor {
	return file_sandboxes_api_v1_resource_nodepool_proto_enumTypes[1].Descriptor()
}

func (K8SNodePool_OKE_CapacityType) Type() protoreflect.EnumType {
	return &file_sandboxes_api_v1_resource_nodepool_proto_enumTypes[1]
}

func (x K8SNodePool_OKE_CapacityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use K8SNodePool_OKE_CapacityType.Descriptor instead.
func (K8SNodePool_OKE_CapacityType) EnumDescriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 8, 0}
}

type K8SNodePool_Scale_Condition_Combination_Op int32

const (
	K8SNodePool_Scale_Condition_Combination_AND K8SNodePool_Scale_Condition_Combination_Op = 0
	K8SNodePool_Scale_Condition_Combination_OR  K8SNodePool_Scale_Condition_Combination_Op = 1
	K8SNodePool_Scale_Condition_Combination_NOT K8SNodePool_Scale_Condition_Combination_Op = 2
)

// Enum value maps for K8SNodePool_Scale_Condition_Combination_Op.
var (
	K8SNodePool_Scale_Condition_Combination_Op_name = map[int32]string{
		0: "AND",
		1: "OR",
		2: "NOT",
	}
	K8SNodePool_Scale_Condition_Combination_Op_value = map[string]int32{
		"AND": 0,
		"OR":  1,
		"NOT": 2,
	}
)

func (x K8SNodePool_Scale_Condition_Combination_Op) Enum() *K8SNodePool_Scale_Condition_Combination_Op {
	p := new(K8SNodePool_Scale_Condition_Combination_Op)
	*p = x
	return p
}

func (x K8SNodePool_Scale_Condition_Combination_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (K8SNodePool_Scale_Condition_Combination_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_sandboxes_api_v1_resource_nodepool_proto_enumTypes[2].Descriptor()
}

func (K8SNodePool_Scale_Condition_Combination_Op) Type() protoreflect.EnumType {
	return &file_sandboxes_api_v1_resource_nodepool_proto_enumTypes[2]
}

func (x K8SNodePool_Scale_Condition_Combination_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use K8SNodePool_Scale_Condition_Combination_Op.Descriptor instead.
func (K8SNodePool_Scale_Condition_Combination_Op) EnumDescriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 9, 0, 0, 0}
}

type K8SNodePoolStatus_State int32

const (
	K8SNodePoolStatus_UNKNOWN  K8SNodePoolStatus_State = 0 // State unavailable
	K8SNodePoolStatus_CREATING K8SNodePoolStatus_State = 1 // Node Pool is being created.
	K8SNodePoolStatus_ACTIVE   K8SNodePoolStatus_State = 2 // Node Pool is active and running.
	K8SNodePoolStatus_UPDATING K8SNodePoolStatus_State = 3 // Node pool is being updated.
	K8SNodePoolStatus_ERROR    K8SNodePoolStatus_State = 4 // Something goes wrong with the node pool.
)

// Enum value maps for K8SNodePoolStatus_State.
var (
	K8SNodePoolStatus_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATING",
		2: "ACTIVE",
		3: "UPDATING",
		4: "ERROR",
	}
	K8SNodePoolStatus_State_value = map[string]int32{
		"UNKNOWN":  0,
		"CREATING": 1,
		"ACTIVE":   2,
		"UPDATING": 3,
		"ERROR":    4,
	}
)

func (x K8SNodePoolStatus_State) Enum() *K8SNodePoolStatus_State {
	p := new(K8SNodePoolStatus_State)
	*p = x
	return p
}

func (x K8SNodePoolStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (K8SNodePoolStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_sandboxes_api_v1_resource_nodepool_proto_enumTypes[3].Descriptor()
}

func (K8SNodePoolStatus_State) Type() protoreflect.EnumType {
	return &file_sandboxes_api_v1_resource_nodepool_proto_enumTypes[3]
}

func (x K8SNodePoolStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use K8SNodePoolStatus_State.Descriptor instead.
func (K8SNodePoolStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{1, 0}
}

type K8SNodePool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The provision and scale configuration of this node pool.
	Config *K8SNodePool_Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The region of this node pool.
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// The flag indicate this node pool is an unmanaged one.
	// For unmanaged node pool, only config.scale is respected.
	// Sandbox system should not interact with this node pool for any other spec modification.
	// Sandbox system should still check the node pool to ensure it is managed internally, in case of misconfiguratin, neither of spec and scale should be respected.
	Unmanaged     bool `protobuf:"varint,3,opt,name=unmanaged,proto3" json:"unmanaged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool) Reset() {
	*x = K8SNodePool{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool) ProtoMessage() {}

func (x *K8SNodePool) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool.ProtoReflect.Descriptor instead.
func (*K8SNodePool) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0}
}

func (x *K8SNodePool) GetConfig() *K8SNodePool_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *K8SNodePool) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *K8SNodePool) GetUnmanaged() bool {
	if x != nil {
		return x.Unmanaged
	}
	return false
}

// K8sNodePoolStatus represents the ephermeral status of the k8s node pool.
// It should be populated in the corresponding resource's status.
type K8SNodePoolStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state of this k8s node pool.
	// This state only reflects the running state from the individual cloud provider or the provision reconciler.
	// Regardless of the state, status should be inspected as well to get the full view of the node pool status.
	State K8SNodePoolStatus_State `protobuf:"varint,1,opt,name=state,proto3,enum=sandboxes.api.v1.K8SNodePoolStatus_State" json:"state,omitempty"`
	// The runtime status of this node pool. The state of which is always set to UNKNOWN.
	// For each reconciler, this status should be reported separately.
	// - provision reconciler
	// - scaling reconciler
	// For the entire node pool. Different RuntimeStatus should be merged and generate an aggregated view.
	Status *RuntimeStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// The desired node count, which is configured and retrived from the cloud provider.
	DesiredCount int64 `protobuf:"varint,3,opt,name=desired_count,json=desiredCount,proto3" json:"desired_count,omitempty"`
	// The actual node count.
	ActualCount   int64 `protobuf:"varint,4,opt,name=actual_count,json=actualCount,proto3" json:"actual_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePoolStatus) Reset() {
	*x = K8SNodePoolStatus{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePoolStatus) ProtoMessage() {}

func (x *K8SNodePoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePoolStatus.ProtoReflect.Descriptor instead.
func (*K8SNodePoolStatus) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{1}
}

func (x *K8SNodePoolStatus) GetState() K8SNodePoolStatus_State {
	if x != nil {
		return x.State
	}
	return K8SNodePoolStatus_UNKNOWN
}

func (x *K8SNodePoolStatus) GetStatus() *RuntimeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *K8SNodePoolStatus) GetDesiredCount() int64 {
	if x != nil {
		return x.DesiredCount
	}
	return 0
}

func (x *K8SNodePoolStatus) GetActualCount() int64 {
	if x != nil {
		return x.ActualCount
	}
	return 0
}

// Config defines the user-face schema for the K8S node pool.
type K8SNodePool_Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The selector names of the node pool. Selector name is used to schedule a sandbox.
	// There is a special selector name called `default`. If `default` presents, it should be the only select name.
	// `default` node pool can be used to schedule workloads that do not have custom schedule spec.
	SelectorNames []string `protobuf:"bytes,1,rep,name=selector_names,json=selectorNames,proto3" json:"selector_names,omitempty"`
	// The kinds of workloads to be scheduled on the node pool.
	// The currently defined values are:
	// - svc: dependencies and containers
	// - ws: workspaces
	WorkloadKinds []string `protobuf:"bytes,2,rep,name=workload_kinds,json=workloadKinds,proto3" json:"workload_kinds,omitempty"`
	// All these labels would be applied to the underlying nodes.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// All these taints would be applied to the underlying nodes.
	// The individual taint must be in format of "key=value:EFFECT".
	Taints []string `protobuf:"bytes,4,rep,name=taints,proto3" json:"taints,omitempty"`
	// The disk size in GB.
	DiskSize int64 `protobuf:"varint,7,opt,name=disk_size,json=diskSize,proto3" json:"disk_size,omitempty"`
	// The swap configuration.
	Swap *K8SNodePool_Swap `protobuf:"bytes,8,opt,name=swap,proto3" json:"swap,omitempty"`
	// The custom configuration for specific provider.
	Provider *K8SNodePool_Provider `protobuf:"bytes,9,opt,name=provider,proto3" json:"provider,omitempty"`
	// The scaling configuration.
	Scale *K8SNodePool_Scale `protobuf:"bytes,10,opt,name=scale,proto3" json:"scale,omitempty"`
	// The GPU configuration.
	// If not specified, the GPUs is not enabled in this node pool.
	// If specified, additional validation would be taken to ensure the GPU resources are available in the
	Gpu *K8SNodePool_GPU `protobuf:"bytes,11,opt,name=gpu,proto3" json:"gpu,omitempty"`
	// The max workloads allowed per node in this node pool.
	// This value must not be negative and will be reported and reflected in the following places in the corresponding nodes:
	// - resource-control.sandbox/max-workloads-per-node.
	// If this value is not specified or empty, the limitation should be inferred from the sources from below (for the minimal one):
	// - resource profile (deprecated): if this profile exists, it should be respected (till it is being fully removed).
	// - provider specific workload limiation labels. e.g. for GCP, it is cloud.google.com/gke-max-pods-per-node.
	// - the value from status.capacity.pod.
	// - a global constant, which could be any postive number.
	MaxWorkloadsPerNode int32 `protobuf:"varint,12,opt,name=max_workloads_per_node,json=maxWorkloadsPerNode,proto3" json:"max_workloads_per_node,omitempty"`
	// Optional. The minimum amount of memory in MB to reserve from the node's total physical memory.
	// If specified, hostd will compute an additional capacity estimate as:
	//
	//	physical_memory - min_memory_reserve
	//
	// and use the minimum of this value and its existing calculated capacity as the final memory capacity.
	// This is useful when daemon sets or other system components are expected to consume memory on the node.
	MinMemoryReserveMb int64 `protobuf:"varint,13,opt,name=min_memory_reserve_mb,json=minMemoryReserveMb,proto3" json:"min_memory_reserve_mb,omitempty"`
	// Optional. flag indicates whether the nested virtualization should be enabled.
	// If the nested virtualization is not supported but enabled in the node pool, the provisioning will fail.
	NestedVirtualization bool `protobuf:"varint,14,opt,name=nested_virtualization,json=nestedVirtualization,proto3" json:"nested_virtualization,omitempty"`
	// Optional. The special storage servers to connect.
	Storage       *K8SNodePool_Storage `protobuf:"bytes,15,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_Config) Reset() {
	*x = K8SNodePool_Config{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Config) ProtoMessage() {}

func (x *K8SNodePool_Config) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Config.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Config) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 0}
}

func (x *K8SNodePool_Config) GetSelectorNames() []string {
	if x != nil {
		return x.SelectorNames
	}
	return nil
}

func (x *K8SNodePool_Config) GetWorkloadKinds() []string {
	if x != nil {
		return x.WorkloadKinds
	}
	return nil
}

func (x *K8SNodePool_Config) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *K8SNodePool_Config) GetTaints() []string {
	if x != nil {
		return x.Taints
	}
	return nil
}

func (x *K8SNodePool_Config) GetDiskSize() int64 {
	if x != nil {
		return x.DiskSize
	}
	return 0
}

func (x *K8SNodePool_Config) GetSwap() *K8SNodePool_Swap {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *K8SNodePool_Config) GetProvider() *K8SNodePool_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *K8SNodePool_Config) GetScale() *K8SNodePool_Scale {
	if x != nil {
		return x.Scale
	}
	return nil
}

func (x *K8SNodePool_Config) GetGpu() *K8SNodePool_GPU {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *K8SNodePool_Config) GetMaxWorkloadsPerNode() int32 {
	if x != nil {
		return x.MaxWorkloadsPerNode
	}
	return 0
}

func (x *K8SNodePool_Config) GetMinMemoryReserveMb() int64 {
	if x != nil {
		return x.MinMemoryReserveMb
	}
	return 0
}

func (x *K8SNodePool_Config) GetNestedVirtualization() bool {
	if x != nil {
		return x.NestedVirtualization
	}
	return false
}

func (x *K8SNodePool_Config) GetStorage() *K8SNodePool_Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

type K8SNodePool_GPU struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Provider:
	//
	//	*K8SNodePool_GPU_Nvidia_
	Provider      isK8SNodePool_GPU_Provider `protobuf_oneof:"provider"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_GPU) Reset() {
	*x = K8SNodePool_GPU{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_GPU) ProtoMessage() {}

func (x *K8SNodePool_GPU) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_GPU.ProtoReflect.Descriptor instead.
func (*K8SNodePool_GPU) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 1}
}

func (x *K8SNodePool_GPU) GetProvider() isK8SNodePool_GPU_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *K8SNodePool_GPU) GetNvidia() *K8SNodePool_GPU_Nvidia {
	if x != nil {
		if x, ok := x.Provider.(*K8SNodePool_GPU_Nvidia_); ok {
			return x.Nvidia
		}
	}
	return nil
}

type isK8SNodePool_GPU_Provider interface {
	isK8SNodePool_GPU_Provider()
}

type K8SNodePool_GPU_Nvidia_ struct {
	Nvidia *K8SNodePool_GPU_Nvidia `protobuf:"bytes,1,opt,name=nvidia,proto3,oneof"`
}

func (*K8SNodePool_GPU_Nvidia_) isK8SNodePool_GPU_Provider() {}

type K8SNodePool_Swap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The size of swap file in GB.
	FileSize int64 `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	// Specify the swap devices (for local NVME case).
	Devices       []string `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_Swap) Reset() {
	*x = K8SNodePool_Swap{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Swap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Swap) ProtoMessage() {}

func (x *K8SNodePool_Swap) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Swap.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Swap) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 2}
}

func (x *K8SNodePool_Swap) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *K8SNodePool_Swap) GetDevices() []string {
	if x != nil {
		return x.Devices
	}
	return nil
}

type K8SNodePool_Storage struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Servers       []*K8SNodePool_Storage_Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_Storage) Reset() {
	*x = K8SNodePool_Storage{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Storage) ProtoMessage() {}

func (x *K8SNodePool_Storage) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Storage.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Storage) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 3}
}

func (x *K8SNodePool_Storage) GetServers() []*K8SNodePool_Storage_Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type K8SNodePool_Provider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Provider:
	//
	//	*K8SNodePool_Provider_Gke
	//	*K8SNodePool_Provider_Eks
	//	*K8SNodePool_Provider_Aks
	//	*K8SNodePool_Provider_Oke
	Provider      isK8SNodePool_Provider_Provider `protobuf_oneof:"provider"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_Provider) Reset() {
	*x = K8SNodePool_Provider{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Provider) ProtoMessage() {}

func (x *K8SNodePool_Provider) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Provider.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Provider) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 4}
}

func (x *K8SNodePool_Provider) GetProvider() isK8SNodePool_Provider_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *K8SNodePool_Provider) GetGke() *K8SNodePool_GKE {
	if x != nil {
		if x, ok := x.Provider.(*K8SNodePool_Provider_Gke); ok {
			return x.Gke
		}
	}
	return nil
}

func (x *K8SNodePool_Provider) GetEks() *K8SNodePool_EKS {
	if x != nil {
		if x, ok := x.Provider.(*K8SNodePool_Provider_Eks); ok {
			return x.Eks
		}
	}
	return nil
}

func (x *K8SNodePool_Provider) GetAks() *K8SNodePool_AKS {
	if x != nil {
		if x, ok := x.Provider.(*K8SNodePool_Provider_Aks); ok {
			return x.Aks
		}
	}
	return nil
}

func (x *K8SNodePool_Provider) GetOke() *K8SNodePool_OKE {
	if x != nil {
		if x, ok := x.Provider.(*K8SNodePool_Provider_Oke); ok {
			return x.Oke
		}
	}
	return nil
}

type isK8SNodePool_Provider_Provider interface {
	isK8SNodePool_Provider_Provider()
}

type K8SNodePool_Provider_Gke struct {
	Gke *K8SNodePool_GKE `protobuf:"bytes,1,opt,name=gke,proto3,oneof"`
}

type K8SNodePool_Provider_Eks struct {
	Eks *K8SNodePool_EKS `protobuf:"bytes,2,opt,name=eks,proto3,oneof"`
}

type K8SNodePool_Provider_Aks struct {
	Aks *K8SNodePool_AKS `protobuf:"bytes,3,opt,name=aks,proto3,oneof"`
}

type K8SNodePool_Provider_Oke struct {
	Oke *K8SNodePool_OKE `protobuf:"bytes,4,opt,name=oke,proto3,oneof"`
}

func (*K8SNodePool_Provider_Gke) isK8SNodePool_Provider_Provider() {}

func (*K8SNodePool_Provider_Eks) isK8SNodePool_Provider_Provider() {}

func (*K8SNodePool_Provider_Aks) isK8SNodePool_Provider_Provider() {}

func (*K8SNodePool_Provider_Oke) isK8SNodePool_Provider_Provider() {}

type K8SNodePool_GKE struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional, custom service account to be used in this node pool.
	// If not provided, the default value would be used.
	ServiceAccount string `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// Optional, custom machine type to used in the node pool.
	// If not provided, the default value would be used.
	MachineType string `protobuf:"bytes,2,opt,name=machine_type,json=machineType,proto3" json:"machine_type,omitempty"`
	// Optional, custom disk type to be used in the node pool.
	// If not provided, the default value would be used.
	DiskType string `protobuf:"bytes,3,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"`
	// This field is kept for backward compatibility purpose, if true, it will override the global flag.
	NestedVirtualization bool `protobuf:"varint,4,opt,name=nested_virtualization,json=nestedVirtualization,proto3" json:"nested_virtualization,omitempty"`
	// Optional, minimal CPU platofrm that the node should use.
	MinCpuPlatform string `protobuf:"bytes,5,opt,name=min_cpu_platform,json=minCpuPlatform,proto3" json:"min_cpu_platform,omitempty"`
	// Optional, the guest accelators for the node pool.
	// For now, at most one accelerator is supported, more might be supported in the future.
	// e.g. If GPU sharing is enabled, a GPU specific accelator must be specified here.
	// Refer to https://cloud.google.com/compute/docs/gpus for all the supported GPU accelerators.
	Accelerators []*K8SNodePool_GKE_Accelerator `protobuf:"bytes,6,rep,name=accelerators,proto3" json:"accelerators,omitempty"`
	// Optional, enable the confidential storage.
	// For some specific combinations of disk type and machine type, this flag should be set to true to make it work.
	EnableConfidentialStorage bool `protobuf:"varint,7,opt,name=enable_confidential_storage,json=enableConfidentialStorage,proto3" json:"enable_confidential_storage,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *K8SNodePool_GKE) Reset() {
	*x = K8SNodePool_GKE{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_GKE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_GKE) ProtoMessage() {}

func (x *K8SNodePool_GKE) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_GKE.ProtoReflect.Descriptor instead.
func (*K8SNodePool_GKE) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 5}
}

func (x *K8SNodePool_GKE) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

func (x *K8SNodePool_GKE) GetMachineType() string {
	if x != nil {
		return x.MachineType
	}
	return ""
}

func (x *K8SNodePool_GKE) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

func (x *K8SNodePool_GKE) GetNestedVirtualization() bool {
	if x != nil {
		return x.NestedVirtualization
	}
	return false
}

func (x *K8SNodePool_GKE) GetMinCpuPlatform() string {
	if x != nil {
		return x.MinCpuPlatform
	}
	return ""
}

func (x *K8SNodePool_GKE) GetAccelerators() []*K8SNodePool_GKE_Accelerator {
	if x != nil {
		return x.Accelerators
	}
	return nil
}

func (x *K8SNodePool_GKE) GetEnableConfidentialStorage() bool {
	if x != nil {
		return x.EnableConfidentialStorage
	}
	return false
}

// EKS includes a partial set of CreateNodegroupInput.
// https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/eks#CreateNodegroupInput
type K8SNodePool_EKS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specify the instance types for a node group.
	InstanceTypes []string `protobuf:"bytes,1,rep,name=instance_types,json=instanceTypes,proto3" json:"instance_types,omitempty"`
	// Optional. The AMI type for your node group.
	AmiType string `protobuf:"bytes,2,opt,name=ami_type,json=amiType,proto3" json:"ami_type,omitempty"`
	// Optional. The ID of the image which would be used to create the launch template.
	// If not provided, it is up to the AWS to determine which image would be used based on ami type.
	ImageId string `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// Metadata that assists with categorization and organization.
	Tags map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The indexes of the availability zone. It is used to specify the subnets associated with this node pool.
	// In EKS cluster, there would be multiple subnets for node groups. The multiple subnets are associated with different AZs.
	// Due to the persistent volume attachment limitation, one and only one subnet is supported in a single node group, at this stage.
	// If not specified, it would be default to [0], which means the first subnet would be used.
	// At this stage, if more than 1 subnet are specified, validation would fail.
	Subnets *K8SNodePool_EKS_SubnetSelector `protobuf:"bytes,5,opt,name=subnets,proto3" json:"subnets,omitempty"`
	// Configuration for locally attached volume storage.
	// Defined as a list to allow future expansion.
	// Currently, this list must be either empty or contain exactly one entry.
	LocalAttachedVolumes []*K8SNodePool_EKS_LocalAttachedVolume `protobuf:"bytes,6,rep,name=local_attached_volumes,json=localAttachedVolumes,proto3" json:"local_attached_volumes,omitempty"`
	// The capcity type of this node group.
	// The default value is ON_DEMAND.
	CapacityType  K8SNodePool_EKS_CapacityType `protobuf:"varint,7,opt,name=capacity_type,json=capacityType,proto3,enum=sandboxes.api.v1.K8SNodePool_EKS_CapacityType" json:"capacity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_EKS) Reset() {
	*x = K8SNodePool_EKS{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_EKS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_EKS) ProtoMessage() {}

func (x *K8SNodePool_EKS) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_EKS.ProtoReflect.Descriptor instead.
func (*K8SNodePool_EKS) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 6}
}

func (x *K8SNodePool_EKS) GetInstanceTypes() []string {
	if x != nil {
		return x.InstanceTypes
	}
	return nil
}

func (x *K8SNodePool_EKS) GetAmiType() string {
	if x != nil {
		return x.AmiType
	}
	return ""
}

func (x *K8SNodePool_EKS) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *K8SNodePool_EKS) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *K8SNodePool_EKS) GetSubnets() *K8SNodePool_EKS_SubnetSelector {
	if x != nil {
		return x.Subnets
	}
	return nil
}

func (x *K8SNodePool_EKS) GetLocalAttachedVolumes() []*K8SNodePool_EKS_LocalAttachedVolume {
	if x != nil {
		return x.LocalAttachedVolumes
	}
	return nil
}

func (x *K8SNodePool_EKS) GetCapacityType() K8SNodePool_EKS_CapacityType {
	if x != nil {
		return x.CapacityType
	}
	return K8SNodePool_EKS_DEFAULT
}

type K8SNodePool_AKS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specify the virtual machine size for a node pool.
	VmSize string `protobuf:"bytes,1,opt,name=vm_size,json=vmSize,proto3" json:"vm_size,omitempty"`
	// Hidden in the UI. Whether to enable UltraSSD.
	// https://learn.microsoft.com/en-us/azure/aks/use-ultra-disks
	EnableUltraSsd bool `protobuf:"varint,2,opt,name=enable_ultra_ssd,json=enableUltraSsd,proto3" json:"enable_ultra_ssd,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *K8SNodePool_AKS) Reset() {
	*x = K8SNodePool_AKS{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_AKS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_AKS) ProtoMessage() {}

func (x *K8SNodePool_AKS) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_AKS.ProtoReflect.Descriptor instead.
func (*K8SNodePool_AKS) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 7}
}

func (x *K8SNodePool_AKS) GetVmSize() string {
	if x != nil {
		return x.VmSize
	}
	return ""
}

func (x *K8SNodePool_AKS) GetEnableUltraSsd() bool {
	if x != nil {
		return x.EnableUltraSsd
	}
	return false
}

// OKE includes a partial set of CreateNodePoolDetails.
// https://docs.oracle.com/en-us/iaas/api/#/en/containerengine/20180222/datatypes/CreateNodePoolDetails
type K8SNodePool_OKE struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specify the node shape for the node pool.
	NodeShape string `protobuf:"bytes,1,opt,name=node_shape,json=nodeShape,proto3" json:"node_shape,omitempty"`
	// Optional. Additional node shape config if the node shape is flexible.
	NodeShapeConfig *K8SNodePool_OKE_NodeShapeConfig `protobuf:"bytes,2,opt,name=node_shape_config,json=nodeShapeConfig,proto3" json:"node_shape_config,omitempty"`
	// The ID of the image which would be used for the node.
	ImageId string `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// The capcity type of this node group.
	// The default value is ON_DEMAND.
	// If PREEMPTIBLE capacity type is used, the node shape must be validated.
	CapacityType  K8SNodePool_OKE_CapacityType `protobuf:"varint,4,opt,name=capacity_type,json=capacityType,proto3,enum=sandboxes.api.v1.K8SNodePool_OKE_CapacityType" json:"capacity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_OKE) Reset() {
	*x = K8SNodePool_OKE{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_OKE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_OKE) ProtoMessage() {}

func (x *K8SNodePool_OKE) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_OKE.ProtoReflect.Descriptor instead.
func (*K8SNodePool_OKE) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 8}
}

func (x *K8SNodePool_OKE) GetNodeShape() string {
	if x != nil {
		return x.NodeShape
	}
	return ""
}

func (x *K8SNodePool_OKE) GetNodeShapeConfig() *K8SNodePool_OKE_NodeShapeConfig {
	if x != nil {
		return x.NodeShapeConfig
	}
	return nil
}

func (x *K8SNodePool_OKE) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *K8SNodePool_OKE) GetCapacityType() K8SNodePool_OKE_CapacityType {
	if x != nil {
		return x.CapacityType
	}
	return K8SNodePool_OKE_DEFAULT
}

type K8SNodePool_Scale struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A flag indicates if the scaling config should be enabled.
	// If enabled, rules would be inspected, the first matched rule should be respected.
	// If disabled, fixed_size should be respected.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// If auto scaling is disabled, this value must be respected, together with node pool's min and max cap.
	NodeCount int32 `protobuf:"varint,2,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	// A list of scaling rules, which are checked in the order of definition, if auto scaling is enabled.
	// If any rule matches, it would skip the following rules (if any) and use the matched one to determine the scale strategy.
	Rules []*K8SNodePool_Scale_Rule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	// The max node count allowed in this node pool, when the auto scaling is enabled.
	// This value must be greater than or equal to the min_count, and must be greater than or equal to 0.
	// If max_count is not specified, it would be default to 0, which means the node pool is empty.
	MaxCount int32 `protobuf:"varint,4,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	// The min node count in the node pool, when the auto scaling is enabled.
	// This value must be less than or equal to the max_count.
	MinCount      int32 `protobuf:"varint,5,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_Scale) Reset() {
	*x = K8SNodePool_Scale{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Scale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Scale) ProtoMessage() {}

func (x *K8SNodePool_Scale) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Scale.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Scale) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 9}
}

func (x *K8SNodePool_Scale) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *K8SNodePool_Scale) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *K8SNodePool_Scale) GetRules() []*K8SNodePool_Scale_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *K8SNodePool_Scale) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *K8SNodePool_Scale) GetMinCount() int32 {
	if x != nil {
		return x.MinCount
	}
	return 0
}

// NVIDIA specific sharing configuration.
type K8SNodePool_GPU_Nvidia struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If sharing is not specified, the whole GPU will be exclusively used by a single workspace.
	//
	// Types that are valid to be assigned to Sharing:
	//
	//	*K8SNodePool_GPU_Nvidia_TimeSlicing_
	Sharing       isK8SNodePool_GPU_Nvidia_Sharing `protobuf_oneof:"sharing"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_GPU_Nvidia) Reset() {
	*x = K8SNodePool_GPU_Nvidia{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_GPU_Nvidia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_GPU_Nvidia) ProtoMessage() {}

func (x *K8SNodePool_GPU_Nvidia) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_GPU_Nvidia.ProtoReflect.Descriptor instead.
func (*K8SNodePool_GPU_Nvidia) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *K8SNodePool_GPU_Nvidia) GetSharing() isK8SNodePool_GPU_Nvidia_Sharing {
	if x != nil {
		return x.Sharing
	}
	return nil
}

func (x *K8SNodePool_GPU_Nvidia) GetTimeSlicing() *K8SNodePool_GPU_Nvidia_TimeSlicing {
	if x != nil {
		if x, ok := x.Sharing.(*K8SNodePool_GPU_Nvidia_TimeSlicing_); ok {
			return x.TimeSlicing
		}
	}
	return nil
}

type isK8SNodePool_GPU_Nvidia_Sharing interface {
	isK8SNodePool_GPU_Nvidia_Sharing()
}

type K8SNodePool_GPU_Nvidia_TimeSlicing_ struct {
	TimeSlicing *K8SNodePool_GPU_Nvidia_TimeSlicing `protobuf:"bytes,1,opt,name=time_slicing,json=timeSlicing,proto3,oneof"`
}

func (*K8SNodePool_GPU_Nvidia_TimeSlicing_) isK8SNodePool_GPU_Nvidia_Sharing() {}

// GPU sharing enabled by time slicing.
// Refer to https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-sharing.html for full info.
type K8SNodePool_GPU_Nvidia_TimeSlicing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time slicing replicas. The total available GPUs are calculated based on this replicas.
	// e.g. if there are 2 nodes in one group, each node has 2 GPU. The replicas is configured as 4. The total available GPUs are 2 * 2 * 4 = 16.
	Replicas      int32 `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_GPU_Nvidia_TimeSlicing) Reset() {
	*x = K8SNodePool_GPU_Nvidia_TimeSlicing{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_GPU_Nvidia_TimeSlicing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_GPU_Nvidia_TimeSlicing) ProtoMessage() {}

func (x *K8SNodePool_GPU_Nvidia_TimeSlicing) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_GPU_Nvidia_TimeSlicing.ProtoReflect.Descriptor instead.
func (*K8SNodePool_GPU_Nvidia_TimeSlicing) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

func (x *K8SNodePool_GPU_Nvidia_TimeSlicing) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type K8SNodePool_Storage_Server struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MountOptions []string               `protobuf:"bytes,2,rep,name=mount_options,json=mountOptions,proto3" json:"mount_options,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*K8SNodePool_Storage_Server_Uri
	Source        isK8SNodePool_Storage_Server_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_Storage_Server) Reset() {
	*x = K8SNodePool_Storage_Server{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Storage_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Storage_Server) ProtoMessage() {}

func (x *K8SNodePool_Storage_Server) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Storage_Server.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Storage_Server) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *K8SNodePool_Storage_Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *K8SNodePool_Storage_Server) GetMountOptions() []string {
	if x != nil {
		return x.MountOptions
	}
	return nil
}

func (x *K8SNodePool_Storage_Server) GetSource() isK8SNodePool_Storage_Server_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *K8SNodePool_Storage_Server) GetUri() string {
	if x != nil {
		if x, ok := x.Source.(*K8SNodePool_Storage_Server_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

type isK8SNodePool_Storage_Server_Source interface {
	isK8SNodePool_Storage_Server_Source()
}

type K8SNodePool_Storage_Server_Uri struct {
	Uri string `protobuf:"bytes,3,opt,name=uri,proto3,oneof"`
}

func (*K8SNodePool_Storage_Server_Uri) isK8SNodePool_Storage_Server_Source() {}

type K8SNodePool_GKE_Accelerator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The accelerator type resource to expose to the nodes in the pool.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The number of the guest accelerator cards exposed to the nodes in the pool.
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Optional, the GPU driver version.
	// It is used to configure the mode for how the GPU driver is installed.
	// It is mapped to GPUDriverInstallationConfig.GpuDriverVersion in Google's API.
	// Refer to https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig#gpudriverversion for the full list.
	GpuDriverVersion string `protobuf:"bytes,3,opt,name=gpu_driver_version,json=gpuDriverVersion,proto3" json:"gpu_driver_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *K8SNodePool_GKE_Accelerator) Reset() {
	*x = K8SNodePool_GKE_Accelerator{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_GKE_Accelerator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_GKE_Accelerator) ProtoMessage() {}

func (x *K8SNodePool_GKE_Accelerator) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_GKE_Accelerator.ProtoReflect.Descriptor instead.
func (*K8SNodePool_GKE_Accelerator) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 5, 0}
}

func (x *K8SNodePool_GKE_Accelerator) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *K8SNodePool_GKE_Accelerator) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *K8SNodePool_GKE_Accelerator) GetGpuDriverVersion() string {
	if x != nil {
		return x.GpuDriverVersion
	}
	return ""
}

type K8SNodePool_EKS_SubnetSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A group of indexes to all the subnets.
	Indices       []int32 `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_EKS_SubnetSelector) Reset() {
	*x = K8SNodePool_EKS_SubnetSelector{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_EKS_SubnetSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_EKS_SubnetSelector) ProtoMessage() {}

func (x *K8SNodePool_EKS_SubnetSelector) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_EKS_SubnetSelector.ProtoReflect.Descriptor instead.
func (*K8SNodePool_EKS_SubnetSelector) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 6, 0}
}

func (x *K8SNodePool_EKS_SubnetSelector) GetIndices() []int32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

type K8SNodePool_EKS_LocalAttachedVolume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The local device to attach for a specific use case.
	// Currently, only NVMe devices are supported.
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// Filesystem type for the target device.
	// Defaults to "ext4" if not specified.
	Filesystem    string `protobuf:"bytes,2,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_EKS_LocalAttachedVolume) Reset() {
	*x = K8SNodePool_EKS_LocalAttachedVolume{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_EKS_LocalAttachedVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_EKS_LocalAttachedVolume) ProtoMessage() {}

func (x *K8SNodePool_EKS_LocalAttachedVolume) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_EKS_LocalAttachedVolume.ProtoReflect.Descriptor instead.
func (*K8SNodePool_EKS_LocalAttachedVolume) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 6, 1}
}

func (x *K8SNodePool_EKS_LocalAttachedVolume) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *K8SNodePool_EKS_LocalAttachedVolume) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

type K8SNodePool_OKE_NodeShapeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The total number of OCPUs available to each node in the node pool.
	Cpus int32 `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	// The total amount of memory available to each node, in GB.
	MemorySizeGb  int64 `protobuf:"varint,2,opt,name=memory_size_gb,json=memorySizeGb,proto3" json:"memory_size_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_OKE_NodeShapeConfig) Reset() {
	*x = K8SNodePool_OKE_NodeShapeConfig{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_OKE_NodeShapeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_OKE_NodeShapeConfig) ProtoMessage() {}

func (x *K8SNodePool_OKE_NodeShapeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_OKE_NodeShapeConfig.ProtoReflect.Descriptor instead.
func (*K8SNodePool_OKE_NodeShapeConfig) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 8, 0}
}

func (x *K8SNodePool_OKE_NodeShapeConfig) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *K8SNodePool_OKE_NodeShapeConfig) GetMemorySizeGb() int64 {
	if x != nil {
		return x.MemorySizeGb
	}
	return 0
}

type K8SNodePool_Scale_Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Condition:
	//
	//	*K8SNodePool_Scale_Condition_WeeklyTimeWindow
	//	*K8SNodePool_Scale_Condition_Combination_
	Condition     isK8SNodePool_Scale_Condition_Condition `protobuf_oneof:"condition"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_Scale_Condition) Reset() {
	*x = K8SNodePool_Scale_Condition{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Scale_Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Scale_Condition) ProtoMessage() {}

func (x *K8SNodePool_Scale_Condition) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Scale_Condition.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Scale_Condition) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 9, 0}
}

func (x *K8SNodePool_Scale_Condition) GetCondition() isK8SNodePool_Scale_Condition_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *K8SNodePool_Scale_Condition) GetWeeklyTimeWindow() *WeeklyTimeWindow {
	if x != nil {
		if x, ok := x.Condition.(*K8SNodePool_Scale_Condition_WeeklyTimeWindow); ok {
			return x.WeeklyTimeWindow
		}
	}
	return nil
}

func (x *K8SNodePool_Scale_Condition) GetCombination() *K8SNodePool_Scale_Condition_Combination {
	if x != nil {
		if x, ok := x.Condition.(*K8SNodePool_Scale_Condition_Combination_); ok {
			return x.Combination
		}
	}
	return nil
}

type isK8SNodePool_Scale_Condition_Condition interface {
	isK8SNodePool_Scale_Condition_Condition()
}

type K8SNodePool_Scale_Condition_WeeklyTimeWindow struct {
	// Only the weekly time window is evaluated.
	WeeklyTimeWindow *WeeklyTimeWindow `protobuf:"bytes,1,opt,name=weekly_time_window,json=weeklyTimeWindow,proto3,oneof"`
}

type K8SNodePool_Scale_Condition_Combination_ struct {
	// A more flexible and complex combination of conditions.
	Combination *K8SNodePool_Scale_Condition_Combination `protobuf:"bytes,2,opt,name=combination,proto3,oneof"`
}

func (*K8SNodePool_Scale_Condition_WeeklyTimeWindow) isK8SNodePool_Scale_Condition_Condition() {}

func (*K8SNodePool_Scale_Condition_Combination_) isK8SNodePool_Scale_Condition_Condition() {}

type K8SNodePool_Scale_Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The minimal nodes should be provisioned in the policy.
	MinNodes int32 `protobuf:"varint,1,opt,name=min_nodes,json=minNodes,proto3" json:"min_nodes,omitempty"`
	// The available workloads config.
	// If not provided, a default count config would be used:
	// - min = 1;
	// - max = 1;
	AvailableWorkloads *K8SNodePool_Scale_Policy_AvailableWorkloads `protobuf:"bytes,2,opt,name=available_workloads,json=availableWorkloads,proto3" json:"available_workloads,omitempty"`
	// Flag indicates if the scale-in should be disabled.
	DisableScaleIn bool `protobuf:"varint,3,opt,name=disable_scale_in,json=disableScaleIn,proto3" json:"disable_scale_in,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *K8SNodePool_Scale_Policy) Reset() {
	*x = K8SNodePool_Scale_Policy{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Scale_Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Scale_Policy) ProtoMessage() {}

func (x *K8SNodePool_Scale_Policy) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Scale_Policy.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Scale_Policy) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 9, 1}
}

func (x *K8SNodePool_Scale_Policy) GetMinNodes() int32 {
	if x != nil {
		return x.MinNodes
	}
	return 0
}

func (x *K8SNodePool_Scale_Policy) GetAvailableWorkloads() *K8SNodePool_Scale_Policy_AvailableWorkloads {
	if x != nil {
		return x.AvailableWorkloads
	}
	return nil
}

func (x *K8SNodePool_Scale_Policy) GetDisableScaleIn() bool {
	if x != nil {
		return x.DisableScaleIn
	}
	return false
}

type K8SNodePool_Scale_Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The condition of the rule.
	// The associated policy would only be respected if the condition is met.
	Condition *K8SNodePool_Scale_Condition `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	// The policy of the rule.
	// Policy defines the behaviors of the rule, if the condition is met.
	Policy        *K8SNodePool_Scale_Policy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_Scale_Rule) Reset() {
	*x = K8SNodePool_Scale_Rule{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Scale_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Scale_Rule) ProtoMessage() {}

func (x *K8SNodePool_Scale_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Scale_Rule.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Scale_Rule) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 9, 2}
}

func (x *K8SNodePool_Scale_Rule) GetCondition() *K8SNodePool_Scale_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *K8SNodePool_Scale_Rule) GetPolicy() *K8SNodePool_Scale_Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type K8SNodePool_Scale_Condition_Combination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The operator of this condition.
	Op K8SNodePool_Scale_Condition_Combination_Op `protobuf:"varint,1,opt,name=op,proto3,enum=sandboxes.api.v1.K8SNodePool_Scale_Condition_Combination_Op" json:"op,omitempty"`
	// The collection of conditions that should be applied with operator.
	// For NOT operator, the size of the conditions must be 1.
	// conditions must not be empty.
	Conditions    []*K8SNodePool_Scale_Condition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_Scale_Condition_Combination) Reset() {
	*x = K8SNodePool_Scale_Condition_Combination{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Scale_Condition_Combination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Scale_Condition_Combination) ProtoMessage() {}

func (x *K8SNodePool_Scale_Condition_Combination) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Scale_Condition_Combination.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Scale_Condition_Combination) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 9, 0, 0}
}

func (x *K8SNodePool_Scale_Condition_Combination) GetOp() K8SNodePool_Scale_Condition_Combination_Op {
	if x != nil {
		return x.Op
	}
	return K8SNodePool_Scale_Condition_Combination_AND
}

func (x *K8SNodePool_Scale_Condition_Combination) GetConditions() []*K8SNodePool_Scale_Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type K8SNodePool_Scale_Policy_AvailableWorkloads struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The min available workloads.
	// If the current available workloads is less than this value, a scale-out may be triggered.
	Min int32 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	// Deprecated. To be removed in the future's release.
	// This was used to control the timing of scale-in, but it is not necessary as it can be the same as the min.
	Max           int32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SNodePool_Scale_Policy_AvailableWorkloads) Reset() {
	*x = K8SNodePool_Scale_Policy_AvailableWorkloads{}
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SNodePool_Scale_Policy_AvailableWorkloads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNodePool_Scale_Policy_AvailableWorkloads) ProtoMessage() {}

func (x *K8SNodePool_Scale_Policy_AvailableWorkloads) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNodePool_Scale_Policy_AvailableWorkloads.ProtoReflect.Descriptor instead.
func (*K8SNodePool_Scale_Policy_AvailableWorkloads) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP(), []int{0, 9, 1, 0}
}

func (x *K8SNodePool_Scale_Policy_AvailableWorkloads) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *K8SNodePool_Scale_Policy_AvailableWorkloads) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_sandboxes_api_v1_resource_nodepool_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_resource_nodepool_proto_rawDesc = "" +
	"\n" +
	"(sandboxes/api/v1/resource_nodepool.proto\x12\x10sandboxes.api.v1\x1a\x1dsandboxes/api/v1/common.proto\"\xbd \n" +
	"\vK8sNodePool\x12<\n" +
	"\x06config\x18\x01 \x01(\v2$.sandboxes.api.v1.K8sNodePool.ConfigR\x06config\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tunmanaged\x18\x03 \x01(\bR\tunmanaged\x1a\xda\x05\n" +
	"\x06Config\x12%\n" +
	"\x0eselector_names\x18\x01 \x03(\tR\rselectorNames\x12%\n" +
	"\x0eworkload_kinds\x18\x02 \x03(\tR\rworkloadKinds\x12H\n" +
	"\x06labels\x18\x03 \x03(\v20.sandboxes.api.v1.K8sNodePool.Config.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06taints\x18\x04 \x03(\tR\x06taints\x12\x1b\n" +
	"\tdisk_size\x18\a \x01(\x03R\bdiskSize\x126\n" +
	"\x04swap\x18\b \x01(\v2\".sandboxes.api.v1.K8sNodePool.SwapR\x04swap\x12B\n" +
	"\bprovider\x18\t \x01(\v2&.sandboxes.api.v1.K8sNodePool.ProviderR\bprovider\x129\n" +
	"\x05scale\x18\n" +
	" \x01(\v2#.sandboxes.api.v1.K8sNodePool.ScaleR\x05scale\x123\n" +
	"\x03gpu\x18\v \x01(\v2!.sandboxes.api.v1.K8sNodePool.GPUR\x03gpu\x123\n" +
	"\x16max_workloads_per_node\x18\f \x01(\x05R\x13maxWorkloadsPerNode\x121\n" +
	"\x15min_memory_reserve_mb\x18\r \x01(\x03R\x12minMemoryReserveMb\x123\n" +
	"\x15nested_virtualization\x18\x0e \x01(\bR\x14nestedVirtualization\x12?\n" +
	"\astorage\x18\x0f \x01(\v2%.sandboxes.api.v1.K8sNodePool.StorageR\astorage\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xf1\x01\n" +
	"\x03GPU\x12B\n" +
	"\x06nvidia\x18\x01 \x01(\v2(.sandboxes.api.v1.K8sNodePool.GPU.NvidiaH\x00R\x06nvidia\x1a\x99\x01\n" +
	"\x06Nvidia\x12Y\n" +
	"\ftime_slicing\x18\x01 \x01(\v24.sandboxes.api.v1.K8sNodePool.GPU.Nvidia.TimeSlicingH\x00R\vtimeSlicing\x1a)\n" +
	"\vTimeSlicing\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicasB\t\n" +
	"\asharingB\n" +
	"\n" +
	"\bprovider\x1a=\n" +
	"\x04Swap\x12\x1b\n" +
	"\tfile_size\x18\x01 \x01(\x03R\bfileSize\x12\x18\n" +
	"\adevices\x18\x02 \x03(\tR\adevices\x1a\xb2\x01\n" +
	"\aStorage\x12F\n" +
	"\aservers\x18\x01 \x03(\v2,.sandboxes.api.v1.K8sNodePool.Storage.ServerR\aservers\x1a_\n" +
	"\x06Server\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rmount_options\x18\x02 \x03(\tR\fmountOptions\x12\x12\n" +
	"\x03uri\x18\x03 \x01(\tH\x00R\x03uriB\b\n" +
	"\x06source\x1a\xf2\x01\n" +
	"\bProvider\x125\n" +
	"\x03gke\x18\x01 \x01(\v2!.sandboxes.api.v1.K8sNodePool.GKEH\x00R\x03gke\x125\n" +
	"\x03eks\x18\x02 \x01(\v2!.sandboxes.api.v1.K8sNodePool.EKSH\x00R\x03eks\x125\n" +
	"\x03aks\x18\x03 \x01(\v2!.sandboxes.api.v1.K8sNodePool.AKSH\x00R\x03aks\x125\n" +
	"\x03oke\x18\x04 \x01(\v2!.sandboxes.api.v1.K8sNodePool.OKEH\x00R\x03okeB\n" +
	"\n" +
	"\bprovider\x1a\xc7\x03\n" +
	"\x03GKE\x12'\n" +
	"\x0fservice_account\x18\x01 \x01(\tR\x0eserviceAccount\x12!\n" +
	"\fmachine_type\x18\x02 \x01(\tR\vmachineType\x12\x1b\n" +
	"\tdisk_type\x18\x03 \x01(\tR\bdiskType\x123\n" +
	"\x15nested_virtualization\x18\x04 \x01(\bR\x14nestedVirtualization\x12(\n" +
	"\x10min_cpu_platform\x18\x05 \x01(\tR\x0eminCpuPlatform\x12Q\n" +
	"\faccelerators\x18\x06 \x03(\v2-.sandboxes.api.v1.K8sNodePool.GKE.AcceleratorR\faccelerators\x12>\n" +
	"\x1benable_confidential_storage\x18\a \x01(\bR\x19enableConfidentialStorage\x1ae\n" +
	"\vAccelerator\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12,\n" +
	"\x12gpu_driver_version\x18\x03 \x01(\tR\x10gpuDriverVersion\x1a\x8c\x05\n" +
	"\x03EKS\x12%\n" +
	"\x0einstance_types\x18\x01 \x03(\tR\rinstanceTypes\x12\x19\n" +
	"\bami_type\x18\x02 \x01(\tR\aamiType\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12?\n" +
	"\x04tags\x18\x04 \x03(\v2+.sandboxes.api.v1.K8sNodePool.EKS.TagsEntryR\x04tags\x12J\n" +
	"\asubnets\x18\x05 \x01(\v20.sandboxes.api.v1.K8sNodePool.EKS.SubnetSelectorR\asubnets\x12k\n" +
	"\x16local_attached_volumes\x18\x06 \x03(\v25.sandboxes.api.v1.K8sNodePool.EKS.LocalAttachedVolumeR\x14localAttachedVolumes\x12S\n" +
	"\rcapacity_type\x18\a \x01(\x0e2..sandboxes.api.v1.K8sNodePool.EKS.CapacityTypeR\fcapacityType\x1a*\n" +
	"\x0eSubnetSelector\x12\x18\n" +
	"\aindices\x18\x01 \x03(\x05R\aindices\x1aM\n" +
	"\x13LocalAttachedVolume\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x02 \x01(\tR\n" +
	"filesystem\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\fCapacityType\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\b\n" +
	"\x04SPOT\x10\x01\x1aH\n" +
	"\x03AKS\x12\x17\n" +
	"\avm_size\x18\x01 \x01(\tR\x06vmSize\x12(\n" +
	"\x10enable_ultra_ssd\x18\x02 \x01(\bR\x0eenableUltraSsd\x1a\xee\x02\n" +
	"\x03OKE\x12\x1d\n" +
	"\n" +
	"node_shape\x18\x01 \x01(\tR\tnodeShape\x12]\n" +
	"\x11node_shape_config\x18\x02 \x01(\v21.sandboxes.api.v1.K8sNodePool.OKE.NodeShapeConfigR\x0fnodeShapeConfig\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12S\n" +
	"\rcapacity_type\x18\x04 \x01(\x0e2..sandboxes.api.v1.K8sNodePool.OKE.CapacityTypeR\fcapacityType\x1aK\n" +
	"\x0fNodeShapeConfig\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\x05R\x04cpus\x12$\n" +
	"\x0ememory_size_gb\x18\x02 \x01(\x03R\fmemorySizeGb\",\n" +
	"\fCapacityType\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\x0f\n" +
	"\vPREEMPTIBLE\x10\x01\x1a\xeb\a\n" +
	"\x05Scale\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"node_count\x18\x02 \x01(\x05R\tnodeCount\x12>\n" +
	"\x05rules\x18\x03 \x03(\v2(.sandboxes.api.v1.K8sNodePool.Scale.RuleR\x05rules\x12\x1b\n" +
	"\tmax_count\x18\x04 \x01(\x05R\bmaxCount\x12\x1b\n" +
	"\tmin_count\x18\x05 \x01(\x05R\bminCount\x1a\x98\x03\n" +
	"\tCondition\x12R\n" +
	"\x12weekly_time_window\x18\x01 \x01(\v2\".sandboxes.api.v1.WeeklyTimeWindowH\x00R\x10weeklyTimeWindow\x12]\n" +
	"\vcombination\x18\x02 \x01(\v29.sandboxes.api.v1.K8sNodePool.Scale.Condition.CombinationH\x00R\vcombination\x1a\xca\x01\n" +
	"\vCombination\x12L\n" +
	"\x02op\x18\x01 \x01(\x0e2<.sandboxes.api.v1.K8sNodePool.Scale.Condition.Combination.OpR\x02op\x12M\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v2-.sandboxes.api.v1.K8sNodePool.Scale.ConditionR\n" +
	"conditions\"\x1e\n" +
	"\x02Op\x12\a\n" +
	"\x03AND\x10\x00\x12\x06\n" +
	"\x02OR\x10\x01\x12\a\n" +
	"\x03NOT\x10\x02B\v\n" +
	"\tcondition\x1a\xf9\x01\n" +
	"\x06Policy\x12\x1b\n" +
	"\tmin_nodes\x18\x01 \x01(\x05R\bminNodes\x12n\n" +
	"\x13available_workloads\x18\x02 \x01(\v2=.sandboxes.api.v1.K8sNodePool.Scale.Policy.AvailableWorkloadsR\x12availableWorkloads\x12(\n" +
	"\x10disable_scale_in\x18\x03 \x01(\bR\x0edisableScaleIn\x1a8\n" +
	"\x12AvailableWorkloads\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\x1a\x97\x01\n" +
	"\x04Rule\x12K\n" +
	"\tcondition\x18\x01 \x01(\v2-.sandboxes.api.v1.K8sNodePool.Scale.ConditionR\tcondition\x12B\n" +
	"\x06policy\x18\x02 \x01(\v2*.sandboxes.api.v1.K8sNodePool.Scale.PolicyR\x06policy\"\x9e\x02\n" +
	"\x11K8sNodePoolStatus\x12?\n" +
	"\x05state\x18\x01 \x01(\x0e2).sandboxes.api.v1.K8sNodePoolStatus.StateR\x05state\x127\n" +
	"\x06status\x18\x02 \x01(\v2\x1f.sandboxes.api.v1.RuntimeStatusR\x06status\x12#\n" +
	"\rdesired_count\x18\x03 \x01(\x03R\fdesiredCount\x12!\n" +
	"\factual_count\x18\x04 \x01(\x03R\vactualCount\"G\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bCREATING\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\f\n" +
	"\bUPDATING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04B?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_resource_nodepool_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_resource_nodepool_proto_rawDescData []byte
)

func file_sandboxes_api_v1_resource_nodepool_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_resource_nodepool_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_resource_nodepool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_nodepool_proto_rawDesc), len(file_sandboxes_api_v1_resource_nodepool_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_resource_nodepool_proto_rawDescData
}

var file_sandboxes_api_v1_resource_nodepool_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_sandboxes_api_v1_resource_nodepool_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_sandboxes_api_v1_resource_nodepool_proto_goTypes = []any{
	(K8SNodePool_EKS_CapacityType)(0),               // 0: sandboxes.api.v1.K8sNodePool.EKS.CapacityType
	(K8SNodePool_OKE_CapacityType)(0),               // 1: sandboxes.api.v1.K8sNodePool.OKE.CapacityType
	(K8SNodePool_Scale_Condition_Combination_Op)(0), // 2: sandboxes.api.v1.K8sNodePool.Scale.Condition.Combination.Op
	(K8SNodePoolStatus_State)(0),                    // 3: sandboxes.api.v1.K8sNodePoolStatus.State
	(*K8SNodePool)(nil),                             // 4: sandboxes.api.v1.K8sNodePool
	(*K8SNodePoolStatus)(nil),                       // 5: sandboxes.api.v1.K8sNodePoolStatus
	(*K8SNodePool_Config)(nil),                      // 6: sandboxes.api.v1.K8sNodePool.Config
	(*K8SNodePool_GPU)(nil),                         // 7: sandboxes.api.v1.K8sNodePool.GPU
	(*K8SNodePool_Swap)(nil),                        // 8: sandboxes.api.v1.K8sNodePool.Swap
	(*K8SNodePool_Storage)(nil),                     // 9: sandboxes.api.v1.K8sNodePool.Storage
	(*K8SNodePool_Provider)(nil),                    // 10: sandboxes.api.v1.K8sNodePool.Provider
	(*K8SNodePool_GKE)(nil),                         // 11: sandboxes.api.v1.K8sNodePool.GKE
	(*K8SNodePool_EKS)(nil),                         // 12: sandboxes.api.v1.K8sNodePool.EKS
	(*K8SNodePool_AKS)(nil),                         // 13: sandboxes.api.v1.K8sNodePool.AKS
	(*K8SNodePool_OKE)(nil),                         // 14: sandboxes.api.v1.K8sNodePool.OKE
	(*K8SNodePool_Scale)(nil),                       // 15: sandboxes.api.v1.K8sNodePool.Scale
	nil,                                             // 16: sandboxes.api.v1.K8sNodePool.Config.LabelsEntry
	(*K8SNodePool_GPU_Nvidia)(nil),                  // 17: sandboxes.api.v1.K8sNodePool.GPU.Nvidia
	(*K8SNodePool_GPU_Nvidia_TimeSlicing)(nil),      // 18: sandboxes.api.v1.K8sNodePool.GPU.Nvidia.TimeSlicing
	(*K8SNodePool_Storage_Server)(nil),              // 19: sandboxes.api.v1.K8sNodePool.Storage.Server
	(*K8SNodePool_GKE_Accelerator)(nil),             // 20: sandboxes.api.v1.K8sNodePool.GKE.Accelerator
	(*K8SNodePool_EKS_SubnetSelector)(nil),          // 21: sandboxes.api.v1.K8sNodePool.EKS.SubnetSelector
	(*K8SNodePool_EKS_LocalAttachedVolume)(nil),     // 22: sandboxes.api.v1.K8sNodePool.EKS.LocalAttachedVolume
	nil,                                                 // 23: sandboxes.api.v1.K8sNodePool.EKS.TagsEntry
	(*K8SNodePool_OKE_NodeShapeConfig)(nil),             // 24: sandboxes.api.v1.K8sNodePool.OKE.NodeShapeConfig
	(*K8SNodePool_Scale_Condition)(nil),                 // 25: sandboxes.api.v1.K8sNodePool.Scale.Condition
	(*K8SNodePool_Scale_Policy)(nil),                    // 26: sandboxes.api.v1.K8sNodePool.Scale.Policy
	(*K8SNodePool_Scale_Rule)(nil),                      // 27: sandboxes.api.v1.K8sNodePool.Scale.Rule
	(*K8SNodePool_Scale_Condition_Combination)(nil),     // 28: sandboxes.api.v1.K8sNodePool.Scale.Condition.Combination
	(*K8SNodePool_Scale_Policy_AvailableWorkloads)(nil), // 29: sandboxes.api.v1.K8sNodePool.Scale.Policy.AvailableWorkloads
	(*RuntimeStatus)(nil),                               // 30: sandboxes.api.v1.RuntimeStatus
	(*WeeklyTimeWindow)(nil),                            // 31: sandboxes.api.v1.WeeklyTimeWindow
}
var file_sandboxes_api_v1_resource_nodepool_proto_depIdxs = []int32{
	6,  // 0: sandboxes.api.v1.K8sNodePool.config:type_name -> sandboxes.api.v1.K8sNodePool.Config
	3,  // 1: sandboxes.api.v1.K8sNodePoolStatus.state:type_name -> sandboxes.api.v1.K8sNodePoolStatus.State
	30, // 2: sandboxes.api.v1.K8sNodePoolStatus.status:type_name -> sandboxes.api.v1.RuntimeStatus
	16, // 3: sandboxes.api.v1.K8sNodePool.Config.labels:type_name -> sandboxes.api.v1.K8sNodePool.Config.LabelsEntry
	8,  // 4: sandboxes.api.v1.K8sNodePool.Config.swap:type_name -> sandboxes.api.v1.K8sNodePool.Swap
	10, // 5: sandboxes.api.v1.K8sNodePool.Config.provider:type_name -> sandboxes.api.v1.K8sNodePool.Provider
	15, // 6: sandboxes.api.v1.K8sNodePool.Config.scale:type_name -> sandboxes.api.v1.K8sNodePool.Scale
	7,  // 7: sandboxes.api.v1.K8sNodePool.Config.gpu:type_name -> sandboxes.api.v1.K8sNodePool.GPU
	9,  // 8: sandboxes.api.v1.K8sNodePool.Config.storage:type_name -> sandboxes.api.v1.K8sNodePool.Storage
	17, // 9: sandboxes.api.v1.K8sNodePool.GPU.nvidia:type_name -> sandboxes.api.v1.K8sNodePool.GPU.Nvidia
	19, // 10: sandboxes.api.v1.K8sNodePool.Storage.servers:type_name -> sandboxes.api.v1.K8sNodePool.Storage.Server
	11, // 11: sandboxes.api.v1.K8sNodePool.Provider.gke:type_name -> sandboxes.api.v1.K8sNodePool.GKE
	12, // 12: sandboxes.api.v1.K8sNodePool.Provider.eks:type_name -> sandboxes.api.v1.K8sNodePool.EKS
	13, // 13: sandboxes.api.v1.K8sNodePool.Provider.aks:type_name -> sandboxes.api.v1.K8sNodePool.AKS
	14, // 14: sandboxes.api.v1.K8sNodePool.Provider.oke:type_name -> sandboxes.api.v1.K8sNodePool.OKE
	20, // 15: sandboxes.api.v1.K8sNodePool.GKE.accelerators:type_name -> sandboxes.api.v1.K8sNodePool.GKE.Accelerator
	23, // 16: sandboxes.api.v1.K8sNodePool.EKS.tags:type_name -> sandboxes.api.v1.K8sNodePool.EKS.TagsEntry
	21, // 17: sandboxes.api.v1.K8sNodePool.EKS.subnets:type_name -> sandboxes.api.v1.K8sNodePool.EKS.SubnetSelector
	22, // 18: sandboxes.api.v1.K8sNodePool.EKS.local_attached_volumes:type_name -> sandboxes.api.v1.K8sNodePool.EKS.LocalAttachedVolume
	0,  // 19: sandboxes.api.v1.K8sNodePool.EKS.capacity_type:type_name -> sandboxes.api.v1.K8sNodePool.EKS.CapacityType
	24, // 20: sandboxes.api.v1.K8sNodePool.OKE.node_shape_config:type_name -> sandboxes.api.v1.K8sNodePool.OKE.NodeShapeConfig
	1,  // 21: sandboxes.api.v1.K8sNodePool.OKE.capacity_type:type_name -> sandboxes.api.v1.K8sNodePool.OKE.CapacityType
	27, // 22: sandboxes.api.v1.K8sNodePool.Scale.rules:type_name -> sandboxes.api.v1.K8sNodePool.Scale.Rule
	18, // 23: sandboxes.api.v1.K8sNodePool.GPU.Nvidia.time_slicing:type_name -> sandboxes.api.v1.K8sNodePool.GPU.Nvidia.TimeSlicing
	31, // 24: sandboxes.api.v1.K8sNodePool.Scale.Condition.weekly_time_window:type_name -> sandboxes.api.v1.WeeklyTimeWindow
	28, // 25: sandboxes.api.v1.K8sNodePool.Scale.Condition.combination:type_name -> sandboxes.api.v1.K8sNodePool.Scale.Condition.Combination
	29, // 26: sandboxes.api.v1.K8sNodePool.Scale.Policy.available_workloads:type_name -> sandboxes.api.v1.K8sNodePool.Scale.Policy.AvailableWorkloads
	25, // 27: sandboxes.api.v1.K8sNodePool.Scale.Rule.condition:type_name -> sandboxes.api.v1.K8sNodePool.Scale.Condition
	26, // 28: sandboxes.api.v1.K8sNodePool.Scale.Rule.policy:type_name -> sandboxes.api.v1.K8sNodePool.Scale.Policy
	2,  // 29: sandboxes.api.v1.K8sNodePool.Scale.Condition.Combination.op:type_name -> sandboxes.api.v1.K8sNodePool.Scale.Condition.Combination.Op
	25, // 30: sandboxes.api.v1.K8sNodePool.Scale.Condition.Combination.conditions:type_name -> sandboxes.api.v1.K8sNodePool.Scale.Condition
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_resource_nodepool_proto_init() }
func file_sandboxes_api_v1_resource_nodepool_proto_init() {
	if File_sandboxes_api_v1_resource_nodepool_proto != nil {
		return
	}
	file_sandboxes_api_v1_common_proto_init()
	file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[3].OneofWrappers = []any{
		(*K8SNodePool_GPU_Nvidia_)(nil),
	}
	file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[6].OneofWrappers = []any{
		(*K8SNodePool_Provider_Gke)(nil),
		(*K8SNodePool_Provider_Eks)(nil),
		(*K8SNodePool_Provider_Aks)(nil),
		(*K8SNodePool_Provider_Oke)(nil),
	}
	file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[13].OneofWrappers = []any{
		(*K8SNodePool_GPU_Nvidia_TimeSlicing_)(nil),
	}
	file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[15].OneofWrappers = []any{
		(*K8SNodePool_Storage_Server_Uri)(nil),
	}
	file_sandboxes_api_v1_resource_nodepool_proto_msgTypes[21].OneofWrappers = []any{
		(*K8SNodePool_Scale_Condition_WeeklyTimeWindow)(nil),
		(*K8SNodePool_Scale_Condition_Combination_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_nodepool_proto_rawDesc), len(file_sandboxes_api_v1_resource_nodepool_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_resource_nodepool_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_resource_nodepool_proto_depIdxs,
		EnumInfos:         file_sandboxes_api_v1_resource_nodepool_proto_enumTypes,
		MessageInfos:      file_sandboxes_api_v1_resource_nodepool_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_resource_nodepool_proto = out.File
	file_sandboxes_api_v1_resource_nodepool_proto_goTypes = nil
	file_sandboxes_api_v1_resource_nodepool_proto_depIdxs = nil
}
