// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/resource_logintoken.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A time-bounded token used for quick login as a customer service account in an org.
// The resource is org-scoped.
type LoginToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value of encoded token which can be used by the client directly.
	EncodedToken string `protobuf:"bytes,1,opt,name=encoded_token,json=encodedToken,proto3" json:"encoded_token,omitempty"`
	// User ID of the service account.
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// The starting time when the token becomes valid.
	ValidSince *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=valid_since,json=validSince,proto3" json:"valid_since,omitempty"`
	// The time the token becomes invalid.
	ExpireAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// The default redirect path when the token is used in browser.
	WebRedirectPath string `protobuf:"bytes,10,opt,name=web_redirect_path,json=webRedirectPath,proto3" json:"web_redirect_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginToken) Reset() {
	*x = LoginToken{}
	mi := &file_sandboxes_api_v1_resource_logintoken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginToken) ProtoMessage() {}

func (x *LoginToken) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_resource_logintoken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginToken.ProtoReflect.Descriptor instead.
func (*LoginToken) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_resource_logintoken_proto_rawDescGZIP(), []int{0}
}

func (x *LoginToken) GetEncodedToken() string {
	if x != nil {
		return x.EncodedToken
	}
	return ""
}

func (x *LoginToken) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LoginToken) GetValidSince() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidSince
	}
	return nil
}

func (x *LoginToken) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *LoginToken) GetWebRedirectPath() string {
	if x != nil {
		return x.WebRedirectPath
	}
	return ""
}

var File_sandboxes_api_v1_resource_logintoken_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_resource_logintoken_proto_rawDesc = "" +
	"\n" +
	"*sandboxes/api/v1/resource_logintoken.proto\x12\x10sandboxes.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\n" +
	"LoginToken\x12#\n" +
	"\rencoded_token\x18\x01 \x01(\tR\fencodedToken\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12;\n" +
	"\vvalid_since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validSince\x127\n" +
	"\texpire_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x12*\n" +
	"\x11web_redirect_path\x18\n" +
	" \x01(\tR\x0fwebRedirectPathB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_resource_logintoken_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_resource_logintoken_proto_rawDescData []byte
)

func file_sandboxes_api_v1_resource_logintoken_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_resource_logintoken_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_resource_logintoken_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_logintoken_proto_rawDesc), len(file_sandboxes_api_v1_resource_logintoken_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_resource_logintoken_proto_rawDescData
}

var file_sandboxes_api_v1_resource_logintoken_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sandboxes_api_v1_resource_logintoken_proto_goTypes = []any{
	(*LoginToken)(nil),            // 0: sandboxes.api.v1.LoginToken
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_sandboxes_api_v1_resource_logintoken_proto_depIdxs = []int32{
	1, // 0: sandboxes.api.v1.LoginToken.valid_since:type_name -> google.protobuf.Timestamp
	1, // 1: sandboxes.api.v1.LoginToken.expire_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_resource_logintoken_proto_init() }
func file_sandboxes_api_v1_resource_logintoken_proto_init() {
	if File_sandboxes_api_v1_resource_logintoken_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_resource_logintoken_proto_rawDesc), len(file_sandboxes_api_v1_resource_logintoken_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_resource_logintoken_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_resource_logintoken_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_resource_logintoken_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_resource_logintoken_proto = out.File
	file_sandboxes_api_v1_resource_logintoken_proto_goTypes = nil
	file_sandboxes_api_v1_resource_logintoken_proto_depIdxs = nil
}
