// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/systeminfra_azure.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Azure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Azure) Reset() {
	*x = Azure{}
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Azure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Azure) ProtoMessage() {}

func (x *Azure) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Azure.ProtoReflect.Descriptor instead.
func (*Azure) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_systeminfra_azure_proto_rawDescGZIP(), []int{0}
}

// The provider information.
type Azure_Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Azure_Provider) Reset() {
	*x = Azure_Provider{}
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Azure_Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Azure_Provider) ProtoMessage() {}

func (x *Azure_Provider) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Azure_Provider.ProtoReflect.Descriptor instead.
func (*Azure_Provider) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_systeminfra_azure_proto_rawDescGZIP(), []int{0, 0}
}

// Refer to https://learn.microsoft.com/en-us/rest/api/compute/resource-skus/list
// and https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-sizes/list
type Azure_VmSize struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the VM size (e.g. Standard_D2s_v5).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Number of vCPUs.
	Cpus int32 `protobuf:"varint,2,opt,name=cpus,proto3" json:"cpus,omitempty"`
	// Memory size in MB.
	Memory int64 `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	// Architecture of the VM size (e.g. x86_64, arm64).
	Architecture  string `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Azure_VmSize) Reset() {
	*x = Azure_VmSize{}
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Azure_VmSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Azure_VmSize) ProtoMessage() {}

func (x *Azure_VmSize) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Azure_VmSize.ProtoReflect.Descriptor instead.
func (*Azure_VmSize) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_systeminfra_azure_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Azure_VmSize) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Azure_VmSize) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *Azure_VmSize) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Azure_VmSize) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

// ListVmSizesAction lists all available VM sizes.
type Azure_ListVmSizesAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Azure_ListVmSizesAction) Reset() {
	*x = Azure_ListVmSizesAction{}
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Azure_ListVmSizesAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Azure_ListVmSizesAction) ProtoMessage() {}

func (x *Azure_ListVmSizesAction) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Azure_ListVmSizesAction.ProtoReflect.Descriptor instead.
func (*Azure_ListVmSizesAction) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_systeminfra_azure_proto_rawDescGZIP(), []int{0, 2}
}

// ListNodePoolsAction lists all node pools in the AKS cluster.
type Azure_ListNodePoolsAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Azure_ListNodePoolsAction) Reset() {
	*x = Azure_ListNodePoolsAction{}
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Azure_ListNodePoolsAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Azure_ListNodePoolsAction) ProtoMessage() {}

func (x *Azure_ListNodePoolsAction) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Azure_ListNodePoolsAction.ProtoReflect.Descriptor instead.
func (*Azure_ListNodePoolsAction) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_systeminfra_azure_proto_rawDescGZIP(), []int{0, 3}
}

type Azure_ListVmSizesAction_Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of VM sizes retrieved from Azure.
	VmSizes       []*Azure_VmSize `protobuf:"bytes,1,rep,name=vm_sizes,json=vmSizes,proto3" json:"vm_sizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Azure_ListVmSizesAction_Result) Reset() {
	*x = Azure_ListVmSizesAction_Result{}
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Azure_ListVmSizesAction_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Azure_ListVmSizesAction_Result) ProtoMessage() {}

func (x *Azure_ListVmSizesAction_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Azure_ListVmSizesAction_Result.ProtoReflect.Descriptor instead.
func (*Azure_ListVmSizesAction_Result) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_systeminfra_azure_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Azure_ListVmSizesAction_Result) GetVmSizes() []*Azure_VmSize {
	if x != nil {
		return x.VmSizes
	}
	return nil
}

type Azure_ListNodePoolsAction_Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of node pools. Please note that only user nodepools are listed, not the system node pools.
	NodePools     []*Azure_ListNodePoolsAction_Result_NodePool `protobuf:"bytes,1,rep,name=node_pools,json=nodePools,proto3" json:"node_pools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Azure_ListNodePoolsAction_Result) Reset() {
	*x = Azure_ListNodePoolsAction_Result{}
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Azure_ListNodePoolsAction_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Azure_ListNodePoolsAction_Result) ProtoMessage() {}

func (x *Azure_ListNodePoolsAction_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Azure_ListNodePoolsAction_Result.ProtoReflect.Descriptor instead.
func (*Azure_ListNodePoolsAction_Result) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_systeminfra_azure_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *Azure_ListNodePoolsAction_Result) GetNodePools() []*Azure_ListNodePoolsAction_Result_NodePool {
	if x != nil {
		return x.NodePools
	}
	return nil
}

type Azure_ListNodePoolsAction_Result_NodePool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the node pool.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// If the node pool is managed/provisioned by Sandbox.
	Managed bool `protobuf:"varint,2,opt,name=managed,proto3" json:"managed,omitempty"`
	// The Kubernetes labels of this node pool.
	Labels        map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Azure_ListNodePoolsAction_Result_NodePool) Reset() {
	*x = Azure_ListNodePoolsAction_Result_NodePool{}
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Azure_ListNodePoolsAction_Result_NodePool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Azure_ListNodePoolsAction_Result_NodePool) ProtoMessage() {}

func (x *Azure_ListNodePoolsAction_Result_NodePool) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Azure_ListNodePoolsAction_Result_NodePool.ProtoReflect.Descriptor instead.
func (*Azure_ListNodePoolsAction_Result_NodePool) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_systeminfra_azure_proto_rawDescGZIP(), []int{0, 3, 0, 0}
}

func (x *Azure_ListNodePoolsAction_Result_NodePool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Azure_ListNodePoolsAction_Result_NodePool) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *Azure_ListNodePoolsAction_Result_NodePool) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_sandboxes_api_v1_systeminfra_azure_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_systeminfra_azure_proto_rawDesc = "" +
	"\n" +
	"(sandboxes/api/v1/systeminfra_azure.proto\x12\x10sandboxes.api.v1\"\xb1\x04\n" +
	"\x05Azure\x1a\n" +
	"\n" +
	"\bProvider\x1al\n" +
	"\x06VmSize\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04cpus\x18\x02 \x01(\x05R\x04cpus\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\x03R\x06memory\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x1aX\n" +
	"\x11ListVmSizesAction\x1aC\n" +
	"\x06Result\x129\n" +
	"\bvm_sizes\x18\x01 \x03(\v2\x1e.sandboxes.api.v1.Azure.VmSizeR\avmSizes\x1a\xd3\x02\n" +
	"\x13ListNodePoolsAction\x1a\xbb\x02\n" +
	"\x06Result\x12Z\n" +
	"\n" +
	"node_pools\x18\x01 \x03(\v2;.sandboxes.api.v1.Azure.ListNodePoolsAction.Result.NodePoolR\tnodePools\x1a\xd4\x01\n" +
	"\bNodePool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amanaged\x18\x02 \x01(\bR\amanaged\x12_\n" +
	"\x06labels\x18\x03 \x03(\v2G.sandboxes.api.v1.Azure.ListNodePoolsAction.Result.NodePool.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_systeminfra_azure_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_systeminfra_azure_proto_rawDescData []byte
)

func file_sandboxes_api_v1_systeminfra_azure_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_systeminfra_azure_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_systeminfra_azure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_systeminfra_azure_proto_rawDesc), len(file_sandboxes_api_v1_systeminfra_azure_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_systeminfra_azure_proto_rawDescData
}

var file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sandboxes_api_v1_systeminfra_azure_proto_goTypes = []any{
	(*Azure)(nil),                                     // 0: sandboxes.api.v1.Azure
	(*Azure_Provider)(nil),                            // 1: sandboxes.api.v1.Azure.Provider
	(*Azure_VmSize)(nil),                              // 2: sandboxes.api.v1.Azure.VmSize
	(*Azure_ListVmSizesAction)(nil),                   // 3: sandboxes.api.v1.Azure.ListVmSizesAction
	(*Azure_ListNodePoolsAction)(nil),                 // 4: sandboxes.api.v1.Azure.ListNodePoolsAction
	(*Azure_ListVmSizesAction_Result)(nil),            // 5: sandboxes.api.v1.Azure.ListVmSizesAction.Result
	(*Azure_ListNodePoolsAction_Result)(nil),          // 6: sandboxes.api.v1.Azure.ListNodePoolsAction.Result
	(*Azure_ListNodePoolsAction_Result_NodePool)(nil), // 7: sandboxes.api.v1.Azure.ListNodePoolsAction.Result.NodePool
	nil, // 8: sandboxes.api.v1.Azure.ListNodePoolsAction.Result.NodePool.LabelsEntry
}
var file_sandboxes_api_v1_systeminfra_azure_proto_depIdxs = []int32{
	2, // 0: sandboxes.api.v1.Azure.ListVmSizesAction.Result.vm_sizes:type_name -> sandboxes.api.v1.Azure.VmSize
	7, // 1: sandboxes.api.v1.Azure.ListNodePoolsAction.Result.node_pools:type_name -> sandboxes.api.v1.Azure.ListNodePoolsAction.Result.NodePool
	8, // 2: sandboxes.api.v1.Azure.ListNodePoolsAction.Result.NodePool.labels:type_name -> sandboxes.api.v1.Azure.ListNodePoolsAction.Result.NodePool.LabelsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_systeminfra_azure_proto_init() }
func file_sandboxes_api_v1_systeminfra_azure_proto_init() {
	if File_sandboxes_api_v1_systeminfra_azure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_systeminfra_azure_proto_rawDesc), len(file_sandboxes_api_v1_systeminfra_azure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_systeminfra_azure_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_systeminfra_azure_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_systeminfra_azure_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_systeminfra_azure_proto = out.File
	file_sandboxes_api_v1_systeminfra_azure_proto_goTypes = nil
	file_sandboxes_api_v1_systeminfra_azure_proto_depIdxs = nil
}
