// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: sandboxes/api/v1/trafficservice.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrafficService_ListTrafficSessions_FullMethodName  = "/sandboxes.api.v1.TrafficService/ListTrafficSessions"
	TrafficService_CreateTrafficSession_FullMethodName = "/sandboxes.api.v1.TrafficService/CreateTrafficSession"
	TrafficService_UpdateTrafficSession_FullMethodName = "/sandboxes.api.v1.TrafficService/UpdateTrafficSession"
	TrafficService_DeleteTrafficSession_FullMethodName = "/sandboxes.api.v1.TrafficService/DeleteTrafficSession"
	TrafficService_QueryTrafficEvents_FullMethodName   = "/sandboxes.api.v1.TrafficService/QueryTrafficEvents"
)

// TrafficServiceClient is the client API for TrafficService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Traffic API.
type TrafficServiceClient interface {
	// Queries existing traffic recording sessions in the specified org.
	ListTrafficSessions(ctx context.Context, in *ListTrafficSessionsRequest, opts ...grpc.CallOption) (*ListTrafficSessionsResponse, error)
	// Start a traffic recording session by creating the session and activating it
	// on the specified sandbox.
	// It will fail if the sandbox already has an active recording session.
	CreateTrafficSession(ctx context.Context, in *CreateTrafficSessionRequest, opts ...grpc.CallOption) (*CreateTrafficSessionResponse, error)
	// Update the recording session. Currently it's only used to complete the
	// recording session.
	// It will fail if the specified session is not currently active on a sandbox.
	UpdateTrafficSession(ctx context.Context, in *UpdateTrafficSessionRequest, opts ...grpc.CallOption) (*UpdateTrafficSessionResponse, error)
	// Delete selected recording session. All active sessions will be filtered out
	// automatically.
	DeleteTrafficSession(ctx context.Context, in *DeleteTrafficSessionRequest, opts ...grpc.CallOption) (*DeleteTrafficSessionResponse, error)
	// Query the recorded events in the specified session.
	QueryTrafficEvents(ctx context.Context, in *QueryTrafficEventsRequest, opts ...grpc.CallOption) (*QueryTrafficEventsResponse, error)
}

type trafficServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficServiceClient(cc grpc.ClientConnInterface) TrafficServiceClient {
	return &trafficServiceClient{cc}
}

func (c *trafficServiceClient) ListTrafficSessions(ctx context.Context, in *ListTrafficSessionsRequest, opts ...grpc.CallOption) (*ListTrafficSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrafficSessionsResponse)
	err := c.cc.Invoke(ctx, TrafficService_ListTrafficSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficServiceClient) CreateTrafficSession(ctx context.Context, in *CreateTrafficSessionRequest, opts ...grpc.CallOption) (*CreateTrafficSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTrafficSessionResponse)
	err := c.cc.Invoke(ctx, TrafficService_CreateTrafficSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficServiceClient) UpdateTrafficSession(ctx context.Context, in *UpdateTrafficSessionRequest, opts ...grpc.CallOption) (*UpdateTrafficSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTrafficSessionResponse)
	err := c.cc.Invoke(ctx, TrafficService_UpdateTrafficSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficServiceClient) DeleteTrafficSession(ctx context.Context, in *DeleteTrafficSessionRequest, opts ...grpc.CallOption) (*DeleteTrafficSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTrafficSessionResponse)
	err := c.cc.Invoke(ctx, TrafficService_DeleteTrafficSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficServiceClient) QueryTrafficEvents(ctx context.Context, in *QueryTrafficEventsRequest, opts ...grpc.CallOption) (*QueryTrafficEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTrafficEventsResponse)
	err := c.cc.Invoke(ctx, TrafficService_QueryTrafficEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrafficServiceServer is the server API for TrafficService service.
// All implementations must embed UnimplementedTrafficServiceServer
// for forward compatibility.
//
// The Traffic API.
type TrafficServiceServer interface {
	// Queries existing traffic recording sessions in the specified org.
	ListTrafficSessions(context.Context, *ListTrafficSessionsRequest) (*ListTrafficSessionsResponse, error)
	// Start a traffic recording session by creating the session and activating it
	// on the specified sandbox.
	// It will fail if the sandbox already has an active recording session.
	CreateTrafficSession(context.Context, *CreateTrafficSessionRequest) (*CreateTrafficSessionResponse, error)
	// Update the recording session. Currently it's only used to complete the
	// recording session.
	// It will fail if the specified session is not currently active on a sandbox.
	UpdateTrafficSession(context.Context, *UpdateTrafficSessionRequest) (*UpdateTrafficSessionResponse, error)
	// Delete selected recording session. All active sessions will be filtered out
	// automatically.
	DeleteTrafficSession(context.Context, *DeleteTrafficSessionRequest) (*DeleteTrafficSessionResponse, error)
	// Query the recorded events in the specified session.
	QueryTrafficEvents(context.Context, *QueryTrafficEventsRequest) (*QueryTrafficEventsResponse, error)
	mustEmbedUnimplementedTrafficServiceServer()
}

// UnimplementedTrafficServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficServiceServer struct{}

func (UnimplementedTrafficServiceServer) ListTrafficSessions(context.Context, *ListTrafficSessionsRequest) (*ListTrafficSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrafficSessions not implemented")
}
func (UnimplementedTrafficServiceServer) CreateTrafficSession(context.Context, *CreateTrafficSessionRequest) (*CreateTrafficSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrafficSession not implemented")
}
func (UnimplementedTrafficServiceServer) UpdateTrafficSession(context.Context, *UpdateTrafficSessionRequest) (*UpdateTrafficSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTrafficSession not implemented")
}
func (UnimplementedTrafficServiceServer) DeleteTrafficSession(context.Context, *DeleteTrafficSessionRequest) (*DeleteTrafficSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTrafficSession not implemented")
}
func (UnimplementedTrafficServiceServer) QueryTrafficEvents(context.Context, *QueryTrafficEventsRequest) (*QueryTrafficEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTrafficEvents not implemented")
}
func (UnimplementedTrafficServiceServer) mustEmbedUnimplementedTrafficServiceServer() {}
func (UnimplementedTrafficServiceServer) testEmbeddedByValue()                        {}

// UnsafeTrafficServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficServiceServer will
// result in compilation errors.
type UnsafeTrafficServiceServer interface {
	mustEmbedUnimplementedTrafficServiceServer()
}

func RegisterTrafficServiceServer(s grpc.ServiceRegistrar, srv TrafficServiceServer) {
	// If the following call panics, it indicates UnimplementedTrafficServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficService_ServiceDesc, srv)
}

func _TrafficService_ListTrafficSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrafficSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).ListTrafficSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficService_ListTrafficSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).ListTrafficSessions(ctx, req.(*ListTrafficSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficService_CreateTrafficSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrafficSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).CreateTrafficSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficService_CreateTrafficSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).CreateTrafficSession(ctx, req.(*CreateTrafficSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficService_UpdateTrafficSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrafficSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).UpdateTrafficSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficService_UpdateTrafficSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).UpdateTrafficSession(ctx, req.(*UpdateTrafficSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficService_DeleteTrafficSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrafficSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).DeleteTrafficSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficService_DeleteTrafficSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).DeleteTrafficSession(ctx, req.(*DeleteTrafficSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficService_QueryTrafficEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTrafficEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).QueryTrafficEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficService_QueryTrafficEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).QueryTrafficEvents(ctx, req.(*QueryTrafficEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrafficService_ServiceDesc is the grpc.ServiceDesc for TrafficService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandboxes.api.v1.TrafficService",
	HandlerType: (*TrafficServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTrafficSessions",
			Handler:    _TrafficService_ListTrafficSessions_Handler,
		},
		{
			MethodName: "CreateTrafficSession",
			Handler:    _TrafficService_CreateTrafficSession_Handler,
		},
		{
			MethodName: "UpdateTrafficSession",
			Handler:    _TrafficService_UpdateTrafficSession_Handler,
		},
		{
			MethodName: "DeleteTrafficSession",
			Handler:    _TrafficService_DeleteTrafficSession_Handler,
		},
		{
			MethodName: "QueryTrafficEvents",
			Handler:    _TrafficService_QueryTrafficEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sandboxes/api/v1/trafficservice.proto",
}
