// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/user.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of the client.
type User_AuthorizedClient_ClientType int32

const (
	User_AuthorizedClient_UNKNOWN User_AuthorizedClient_ClientType = 0
	User_AuthorizedClient_WEB     User_AuthorizedClient_ClientType = 1
)

// Enum value maps for User_AuthorizedClient_ClientType.
var (
	User_AuthorizedClient_ClientType_name = map[int32]string{
		0: "UNKNOWN",
		1: "WEB",
	}
	User_AuthorizedClient_ClientType_value = map[string]int32{
		"UNKNOWN": 0,
		"WEB":     1,
	}
)

func (x User_AuthorizedClient_ClientType) Enum() *User_AuthorizedClient_ClientType {
	p := new(User_AuthorizedClient_ClientType)
	*p = x
	return p
}

func (x User_AuthorizedClient_ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_AuthorizedClient_ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_sandboxes_api_v1_user_proto_enumTypes[0].Descriptor()
}

func (User_AuthorizedClient_ClientType) Type() protoreflect.EnumType {
	return &file_sandboxes_api_v1_user_proto_enumTypes[0]
}

func (x User_AuthorizedClient_ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_AuthorizedClient_ClientType.Descriptor instead.
func (User_AuthorizedClient_ClientType) EnumDescriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_user_proto_rawDescGZIP(), []int{0, 0, 0}
}

// A human user.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *ObjectMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Madatory, the primary email.
	// meta.name will be set the same value as email.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Optional, Name for display purpose.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional, URL to avatar image.
	AvatarLink string `protobuf:"bytes,4,opt,name=avatar_link,json=avatarLink,proto3" json:"avatar_link,omitempty"`
	// DEPRECATED, use meta.hierarchy.
	// If specified, this is an org-scoped user.
	// An org-scoped user is used in two cases:
	// - Per-org service account;
	// - The user synced from an org specific identity source.
	OrgId string `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Authorized SSH clients. Each item follows the format
	// of an entry in ~/.ssh/authorized_keys file.
	SshAuthorizedKeys []string `protobuf:"bytes,10,rep,name=ssh_authorized_keys,json=sshAuthorizedKeys,proto3" json:"ssh_authorized_keys,omitempty"`
	// The list of clients being issued long-living tokens.
	// Ordered ASC by the expire_at.
	// There's a max limit on the number of items and oldest (the sooner expire_at is)
	// entries are removed automatically.
	AuthorizedClients []*User_AuthorizedClient `protobuf:"bytes,11,rep,name=authorized_clients,json=authorizedClients,proto3" json:"authorized_clients,omitempty"`
	// Only for Service Accounts.
	// The externally linked email of the Service Account.
	// When specified, this enables the email in gitconfig allowing pushing commits
	// if the service account's SSH key is registered in the linked account on the git server.
	LinkedEmail string `protobuf:"bytes,12,opt,name=linked_email,json=linkedEmail,proto3" json:"linked_email,omitempty"`
	// Optional, JSON encoded extra state to store non-essential backend-invisible
	// properties with flexibility. Properties in that can be promoted as
	// permanent properties once verified and consolidated.
	StateJson     string `protobuf:"bytes,100,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_sandboxes_api_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetAvatarLink() string {
	if x != nil {
		return x.AvatarLink
	}
	return ""
}

func (x *User) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *User) GetSshAuthorizedKeys() []string {
	if x != nil {
		return x.SshAuthorizedKeys
	}
	return nil
}

func (x *User) GetAuthorizedClients() []*User_AuthorizedClient {
	if x != nil {
		return x.AuthorizedClients
	}
	return nil
}

func (x *User) GetLinkedEmail() string {
	if x != nil {
		return x.LinkedEmail
	}
	return ""
}

func (x *User) GetStateJson() string {
	if x != nil {
		return x.StateJson
	}
	return ""
}

// The client which has been issued a long-living token.
type User_AuthorizedClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token ID.
	// It's a short ID generated uniquely per user during the login flow.
	TokenId string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The token issue and expiry time.
	IssuedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpireAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// If the token is created from a LoginToken, this is the ID
	// of the LoginToken. Validation will also check the LoginToken.
	LoginTokenId string `protobuf:"bytes,4,opt,name=login_token_id,json=loginTokenId,proto3" json:"login_token_id,omitempty"`
	// The type of the client determined during the login flow.
	// For information only.
	ClientType    User_AuthorizedClient_ClientType `protobuf:"varint,5,opt,name=client_type,json=clientType,proto3,enum=sandboxes.api.v1.User_AuthorizedClient_ClientType" json:"client_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_AuthorizedClient) Reset() {
	*x = User_AuthorizedClient{}
	mi := &file_sandboxes_api_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_AuthorizedClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_AuthorizedClient) ProtoMessage() {}

func (x *User_AuthorizedClient) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_AuthorizedClient.ProtoReflect.Descriptor instead.
func (*User_AuthorizedClient) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_user_proto_rawDescGZIP(), []int{0, 0}
}

func (x *User_AuthorizedClient) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *User_AuthorizedClient) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *User_AuthorizedClient) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *User_AuthorizedClient) GetLoginTokenId() string {
	if x != nil {
		return x.LoginTokenId
	}
	return ""
}

func (x *User_AuthorizedClient) GetClientType() User_AuthorizedClient_ClientType {
	if x != nil {
		return x.ClientType
	}
	return User_AuthorizedClient_UNKNOWN
}

var File_sandboxes_api_v1_user_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1bsandboxes/api/v1/user.proto\x12\x10sandboxes.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dsandboxes/api/v1/object.proto\"\xb4\x05\n" +
	"\x04User\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.sandboxes.api.v1.ObjectMetaR\x04meta\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\vavatar_link\x18\x04 \x01(\tR\n" +
	"avatarLink\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12.\n" +
	"\x13ssh_authorized_keys\x18\n" +
	" \x03(\tR\x11sshAuthorizedKeys\x12V\n" +
	"\x12authorized_clients\x18\v \x03(\v2'.sandboxes.api.v1.User.AuthorizedClientR\x11authorizedClients\x12!\n" +
	"\flinked_email\x18\f \x01(\tR\vlinkedEmail\x12\x1d\n" +
	"\n" +
	"state_json\x18d \x01(\tR\tstateJson\x1a\xbe\x02\n" +
	"\x10AuthorizedClient\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x127\n" +
	"\tissued_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x127\n" +
	"\texpire_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x12$\n" +
	"\x0elogin_token_id\x18\x04 \x01(\tR\floginTokenId\x12S\n" +
	"\vclient_type\x18\x05 \x01(\x0e22.sandboxes.api.v1.User.AuthorizedClient.ClientTypeR\n" +
	"clientType\"\"\n" +
	"\n" +
	"ClientType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03WEB\x10\x01B?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_user_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_user_proto_rawDescData []byte
)

func file_sandboxes_api_v1_user_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_user_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_user_proto_rawDesc), len(file_sandboxes_api_v1_user_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_user_proto_rawDescData
}

var file_sandboxes_api_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sandboxes_api_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sandboxes_api_v1_user_proto_goTypes = []any{
	(User_AuthorizedClient_ClientType)(0), // 0: sandboxes.api.v1.User.AuthorizedClient.ClientType
	(*User)(nil),                          // 1: sandboxes.api.v1.User
	(*User_AuthorizedClient)(nil),         // 2: sandboxes.api.v1.User.AuthorizedClient
	(*ObjectMeta)(nil),                    // 3: sandboxes.api.v1.ObjectMeta
	(*timestamppb.Timestamp)(nil),         // 4: google.protobuf.Timestamp
}
var file_sandboxes_api_v1_user_proto_depIdxs = []int32{
	3, // 0: sandboxes.api.v1.User.meta:type_name -> sandboxes.api.v1.ObjectMeta
	2, // 1: sandboxes.api.v1.User.authorized_clients:type_name -> sandboxes.api.v1.User.AuthorizedClient
	4, // 2: sandboxes.api.v1.User.AuthorizedClient.issued_at:type_name -> google.protobuf.Timestamp
	4, // 3: sandboxes.api.v1.User.AuthorizedClient.expire_at:type_name -> google.protobuf.Timestamp
	0, // 4: sandboxes.api.v1.User.AuthorizedClient.client_type:type_name -> sandboxes.api.v1.User.AuthorizedClient.ClientType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_user_proto_init() }
func file_sandboxes_api_v1_user_proto_init() {
	if File_sandboxes_api_v1_user_proto != nil {
		return
	}
	file_sandboxes_api_v1_object_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_user_proto_rawDesc), len(file_sandboxes_api_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandboxes_api_v1_user_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_user_proto_depIdxs,
		EnumInfos:         file_sandboxes_api_v1_user_proto_enumTypes,
		MessageInfos:      file_sandboxes_api_v1_user_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_user_proto = out.File
	file_sandboxes_api_v1_user_proto_goTypes = nil
	file_sandboxes_api_v1_user_proto_depIdxs = nil
}
