// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/workloadservice.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *WorkloadRef           `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	Action        *anypb.Any             `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadActionRequest) Reset() {
	*x = WorkloadActionRequest{}
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadActionRequest) ProtoMessage() {}

func (x *WorkloadActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadActionRequest.ProtoReflect.Descriptor instead.
func (*WorkloadActionRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workloadservice_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadActionRequest) GetWorkload() *WorkloadRef {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *WorkloadActionRequest) GetAction() *anypb.Any {
	if x != nil {
		return x.Action
	}
	return nil
}

type WorkloadActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *anypb.Any             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadActionResponse) Reset() {
	*x = WorkloadActionResponse{}
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadActionResponse) ProtoMessage() {}

func (x *WorkloadActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadActionResponse.ProtoReflect.Descriptor instead.
func (*WorkloadActionResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workloadservice_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadActionResponse) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

type IndexedLogQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Since *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	// When specified, it's the last log entry pos.
	Pos           string `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexedLogQuery) Reset() {
	*x = IndexedLogQuery{}
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexedLogQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedLogQuery) ProtoMessage() {}

func (x *IndexedLogQuery) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedLogQuery.ProtoReflect.Descriptor instead.
func (*IndexedLogQuery) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workloadservice_proto_rawDescGZIP(), []int{2}
}

func (x *IndexedLogQuery) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *IndexedLogQuery) GetPos() string {
	if x != nil {
		return x.Pos
	}
	return ""
}

type StreamLogRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Workload *WorkloadRef           `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	Log      *LogRef                `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	Tail     *LogTail               `protobuf:"bytes,3,opt,name=tail,proto3" json:"tail,omitempty"`
	// When specified, query with indexed log features
	Indexed       *IndexedLogQuery `protobuf:"bytes,4,opt,name=indexed,proto3" json:"indexed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogRequest) Reset() {
	*x = StreamLogRequest{}
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogRequest) ProtoMessage() {}

func (x *StreamLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogRequest.ProtoReflect.Descriptor instead.
func (*StreamLogRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workloadservice_proto_rawDescGZIP(), []int{3}
}

func (x *StreamLogRequest) GetWorkload() *WorkloadRef {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *StreamLogRequest) GetLog() *LogRef {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *StreamLogRequest) GetTail() *LogTail {
	if x != nil {
		return x.Tail
	}
	return nil
}

func (x *StreamLogRequest) GetIndexed() *IndexedLogQuery {
	if x != nil {
		return x.Indexed
	}
	return nil
}

type IndexedLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque string representing the position.
	Pos           string                 `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Line          []byte                 `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexedLogEntry) Reset() {
	*x = IndexedLogEntry{}
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexedLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedLogEntry) ProtoMessage() {}

func (x *IndexedLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedLogEntry.ProtoReflect.Descriptor instead.
func (*IndexedLogEntry) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workloadservice_proto_rawDescGZIP(), []int{4}
}

func (x *IndexedLogEntry) GetPos() string {
	if x != nil {
		return x.Pos
	}
	return ""
}

func (x *IndexedLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *IndexedLogEntry) GetLine() []byte {
	if x != nil {
		return x.Line
	}
	return nil
}

type StreamLogEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Content []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// This is returned instead of content if StreamLogRequest.indexed is specified.
	Entry         *IndexedLogEntry `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogEvent) Reset() {
	*x = StreamLogEvent{}
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogEvent) ProtoMessage() {}

func (x *StreamLogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogEvent.ProtoReflect.Descriptor instead.
func (*StreamLogEvent) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workloadservice_proto_rawDescGZIP(), []int{5}
}

func (x *StreamLogEvent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StreamLogEvent) GetEntry() *IndexedLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type TrafficInjection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*TrafficInjection_Connect_
	//	*TrafficInjection_Content
	Request       isTrafficInjection_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficInjection) Reset() {
	*x = TrafficInjection{}
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficInjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficInjection) ProtoMessage() {}

func (x *TrafficInjection) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficInjection.ProtoReflect.Descriptor instead.
func (*TrafficInjection) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workloadservice_proto_rawDescGZIP(), []int{6}
}

func (x *TrafficInjection) GetRequest() isTrafficInjection_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TrafficInjection) GetConnect() *TrafficInjection_Connect {
	if x != nil {
		if x, ok := x.Request.(*TrafficInjection_Connect_); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *TrafficInjection) GetContent() *TrafficContent {
	if x != nil {
		if x, ok := x.Request.(*TrafficInjection_Content); ok {
			return x.Content
		}
	}
	return nil
}

type isTrafficInjection_Request interface {
	isTrafficInjection_Request()
}

type TrafficInjection_Connect_ struct {
	// This must be the first message to establish a connection
	// to the port of the specified workload.
	Connect *TrafficInjection_Connect `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type TrafficInjection_Content struct {
	// A stream of content are sent after the connection is established.
	Content *TrafficContent `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*TrafficInjection_Connect_) isTrafficInjection_Request() {}

func (*TrafficInjection_Content) isTrafficInjection_Request() {}

type TrafficInjection_Connect struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*TrafficInjection_Connect_Port_
	Target        isTrafficInjection_Connect_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficInjection_Connect) Reset() {
	*x = TrafficInjection_Connect{}
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficInjection_Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficInjection_Connect) ProtoMessage() {}

func (x *TrafficInjection_Connect) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficInjection_Connect.ProtoReflect.Descriptor instead.
func (*TrafficInjection_Connect) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workloadservice_proto_rawDescGZIP(), []int{6, 0}
}

func (x *TrafficInjection_Connect) GetTarget() isTrafficInjection_Connect_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *TrafficInjection_Connect) GetPort() *TrafficInjection_Connect_Port {
	if x != nil {
		if x, ok := x.Target.(*TrafficInjection_Connect_Port_); ok {
			return x.Port
		}
	}
	return nil
}

type isTrafficInjection_Connect_Target interface {
	isTrafficInjection_Connect_Target()
}

type TrafficInjection_Connect_Port_ struct {
	// Connect to a workload port.
	Port *TrafficInjection_Connect_Port `protobuf:"bytes,1,opt,name=port,proto3,oneof"`
}

func (*TrafficInjection_Connect_Port_) isTrafficInjection_Connect_Target() {}

type TrafficInjection_Connect_Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *WorkloadRef           `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	PortName      string                 `protobuf:"bytes,2,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficInjection_Connect_Port) Reset() {
	*x = TrafficInjection_Connect_Port{}
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficInjection_Connect_Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficInjection_Connect_Port) ProtoMessage() {}

func (x *TrafficInjection_Connect_Port) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workloadservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficInjection_Connect_Port.ProtoReflect.Descriptor instead.
func (*TrafficInjection_Connect_Port) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workloadservice_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *TrafficInjection_Connect_Port) GetWorkload() *WorkloadRef {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *TrafficInjection_Connect_Port) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

var File_sandboxes_api_v1_workloadservice_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_workloadservice_proto_rawDesc = "" +
	"\n" +
	"&sandboxes/api/v1/workloadservice.proto\x12\x10sandboxes.api.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fsandboxes/api/v1/workload.proto\x1a\x1fsandboxes/api/v1/resource.proto\x1a*sandboxes/api/v1/resource_llmsession.proto\"\x80\x01\n" +
	"\x15WorkloadActionRequest\x129\n" +
	"\bworkload\x18\x01 \x01(\v2\x1d.sandboxes.api.v1.WorkloadRefR\bworkload\x12,\n" +
	"\x06action\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x06action\"F\n" +
	"\x16WorkloadActionResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x06result\"U\n" +
	"\x0fIndexedLogQuery\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x10\n" +
	"\x03pos\x18\x02 \x01(\tR\x03pos\"\xe5\x01\n" +
	"\x10StreamLogRequest\x129\n" +
	"\bworkload\x18\x01 \x01(\v2\x1d.sandboxes.api.v1.WorkloadRefR\bworkload\x12*\n" +
	"\x03log\x18\x02 \x01(\v2\x18.sandboxes.api.v1.LogRefR\x03log\x12-\n" +
	"\x04tail\x18\x03 \x01(\v2\x19.sandboxes.api.v1.LogTailR\x04tail\x12;\n" +
	"\aindexed\x18\x04 \x01(\v2!.sandboxes.api.v1.IndexedLogQueryR\aindexed\"q\n" +
	"\x0fIndexedLogEntry\x12\x10\n" +
	"\x03pos\x18\x01 \x01(\tR\x03pos\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04line\x18\x03 \x01(\fR\x04line\"c\n" +
	"\x0eStreamLogEvent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x127\n" +
	"\x05entry\x18\x02 \x01(\v2!.sandboxes.api.v1.IndexedLogEntryR\x05entry\"\xe0\x02\n" +
	"\x10TrafficInjection\x12F\n" +
	"\aconnect\x18\x01 \x01(\v2*.sandboxes.api.v1.TrafficInjection.ConnectH\x00R\aconnect\x12<\n" +
	"\acontent\x18\x02 \x01(\v2 .sandboxes.api.v1.TrafficContentH\x00R\acontent\x1a\xba\x01\n" +
	"\aConnect\x12E\n" +
	"\x04port\x18\x01 \x01(\v2/.sandboxes.api.v1.TrafficInjection.Connect.PortH\x00R\x04port\x1a^\n" +
	"\x04Port\x129\n" +
	"\bworkload\x18\x01 \x01(\v2\x1d.sandboxes.api.v1.WorkloadRefR\bworkload\x12\x1b\n" +
	"\tport_name\x18\x02 \x01(\tR\bportNameB\b\n" +
	"\x06targetB\t\n" +
	"\arequest2\xa9\x02\n" +
	"\x0fWorkloadService\x12c\n" +
	"\x0eWorkloadAction\x12'.sandboxes.api.v1.WorkloadActionRequest\x1a(.sandboxes.api.v1.WorkloadActionResponse\x12S\n" +
	"\tStreamLog\x12\".sandboxes.api.v1.StreamLogRequest\x1a .sandboxes.api.v1.StreamLogEvent0\x01\x12\\\n" +
	"\rInjectTraffic\x12\".sandboxes.api.v1.TrafficInjection\x1a#.sandboxes.api.v1.TrafficEventEntry(\x010\x01B?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_workloadservice_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_workloadservice_proto_rawDescData []byte
)

func file_sandboxes_api_v1_workloadservice_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_workloadservice_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_workloadservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_workloadservice_proto_rawDesc), len(file_sandboxes_api_v1_workloadservice_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_workloadservice_proto_rawDescData
}

var file_sandboxes_api_v1_workloadservice_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sandboxes_api_v1_workloadservice_proto_goTypes = []any{
	(*WorkloadActionRequest)(nil),         // 0: sandboxes.api.v1.WorkloadActionRequest
	(*WorkloadActionResponse)(nil),        // 1: sandboxes.api.v1.WorkloadActionResponse
	(*IndexedLogQuery)(nil),               // 2: sandboxes.api.v1.IndexedLogQuery
	(*StreamLogRequest)(nil),              // 3: sandboxes.api.v1.StreamLogRequest
	(*IndexedLogEntry)(nil),               // 4: sandboxes.api.v1.IndexedLogEntry
	(*StreamLogEvent)(nil),                // 5: sandboxes.api.v1.StreamLogEvent
	(*TrafficInjection)(nil),              // 6: sandboxes.api.v1.TrafficInjection
	(*TrafficInjection_Connect)(nil),      // 7: sandboxes.api.v1.TrafficInjection.Connect
	(*TrafficInjection_Connect_Port)(nil), // 8: sandboxes.api.v1.TrafficInjection.Connect.Port
	(*WorkloadRef)(nil),                   // 9: sandboxes.api.v1.WorkloadRef
	(*anypb.Any)(nil),                     // 10: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),         // 11: google.protobuf.Timestamp
	(*LogRef)(nil),                        // 12: sandboxes.api.v1.LogRef
	(*LogTail)(nil),                       // 13: sandboxes.api.v1.LogTail
	(*TrafficContent)(nil),                // 14: sandboxes.api.v1.TrafficContent
	(*TrafficEventEntry)(nil),             // 15: sandboxes.api.v1.TrafficEventEntry
}
var file_sandboxes_api_v1_workloadservice_proto_depIdxs = []int32{
	9,  // 0: sandboxes.api.v1.WorkloadActionRequest.workload:type_name -> sandboxes.api.v1.WorkloadRef
	10, // 1: sandboxes.api.v1.WorkloadActionRequest.action:type_name -> google.protobuf.Any
	10, // 2: sandboxes.api.v1.WorkloadActionResponse.result:type_name -> google.protobuf.Any
	11, // 3: sandboxes.api.v1.IndexedLogQuery.since:type_name -> google.protobuf.Timestamp
	9,  // 4: sandboxes.api.v1.StreamLogRequest.workload:type_name -> sandboxes.api.v1.WorkloadRef
	12, // 5: sandboxes.api.v1.StreamLogRequest.log:type_name -> sandboxes.api.v1.LogRef
	13, // 6: sandboxes.api.v1.StreamLogRequest.tail:type_name -> sandboxes.api.v1.LogTail
	2,  // 7: sandboxes.api.v1.StreamLogRequest.indexed:type_name -> sandboxes.api.v1.IndexedLogQuery
	11, // 8: sandboxes.api.v1.IndexedLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 9: sandboxes.api.v1.StreamLogEvent.entry:type_name -> sandboxes.api.v1.IndexedLogEntry
	7,  // 10: sandboxes.api.v1.TrafficInjection.connect:type_name -> sandboxes.api.v1.TrafficInjection.Connect
	14, // 11: sandboxes.api.v1.TrafficInjection.content:type_name -> sandboxes.api.v1.TrafficContent
	8,  // 12: sandboxes.api.v1.TrafficInjection.Connect.port:type_name -> sandboxes.api.v1.TrafficInjection.Connect.Port
	9,  // 13: sandboxes.api.v1.TrafficInjection.Connect.Port.workload:type_name -> sandboxes.api.v1.WorkloadRef
	0,  // 14: sandboxes.api.v1.WorkloadService.WorkloadAction:input_type -> sandboxes.api.v1.WorkloadActionRequest
	3,  // 15: sandboxes.api.v1.WorkloadService.StreamLog:input_type -> sandboxes.api.v1.StreamLogRequest
	6,  // 16: sandboxes.api.v1.WorkloadService.InjectTraffic:input_type -> sandboxes.api.v1.TrafficInjection
	1,  // 17: sandboxes.api.v1.WorkloadService.WorkloadAction:output_type -> sandboxes.api.v1.WorkloadActionResponse
	5,  // 18: sandboxes.api.v1.WorkloadService.StreamLog:output_type -> sandboxes.api.v1.StreamLogEvent
	15, // 19: sandboxes.api.v1.WorkloadService.InjectTraffic:output_type -> sandboxes.api.v1.TrafficEventEntry
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_workloadservice_proto_init() }
func file_sandboxes_api_v1_workloadservice_proto_init() {
	if File_sandboxes_api_v1_workloadservice_proto != nil {
		return
	}
	file_sandboxes_api_v1_workload_proto_init()
	file_sandboxes_api_v1_resource_proto_init()
	file_sandboxes_api_v1_resource_llmsession_proto_init()
	file_sandboxes_api_v1_workloadservice_proto_msgTypes[6].OneofWrappers = []any{
		(*TrafficInjection_Connect_)(nil),
		(*TrafficInjection_Content)(nil),
	}
	file_sandboxes_api_v1_workloadservice_proto_msgTypes[7].OneofWrappers = []any{
		(*TrafficInjection_Connect_Port_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_workloadservice_proto_rawDesc), len(file_sandboxes_api_v1_workloadservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandboxes_api_v1_workloadservice_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_workloadservice_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_workloadservice_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_workloadservice_proto = out.File
	file_sandboxes_api_v1_workloadservice_proto_goTypes = nil
	file_sandboxes_api_v1_workloadservice_proto_depIdxs = nil
}
