// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: sandboxes/api/v1/workspaceservice.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspaceService_SyncStream_FullMethodName                           = "/sandboxes.api.v1.WorkspaceService/SyncStream"
	WorkspaceService_CurrentSetup_FullMethodName                         = "/sandboxes.api.v1.WorkspaceService/CurrentSetup"
	WorkspaceService_IssueToken_FullMethodName                           = "/sandboxes.api.v1.WorkspaceService/IssueToken"
	WorkspaceService_SourceControlCredential_FullMethodName              = "/sandboxes.api.v1.WorkspaceService/SourceControlCredential"
	WorkspaceService_MountOverlay_FullMethodName                         = "/sandboxes.api.v1.WorkspaceService/MountOverlay"
	WorkspaceService_WriteFile_FullMethodName                            = "/sandboxes.api.v1.WorkspaceService/WriteFile"
	WorkspaceService_ReportJetbrainsRemoteDevServerStatus_FullMethodName = "/sandboxes.api.v1.WorkspaceService/ReportJetbrainsRemoteDevServerStatus"
)

// WorkspaceServiceClient is the client API for WorkspaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service is exposed into the user container when the workload is running
// as a workspace.
type WorkspaceServiceClient interface {
	// A long-running stream syncing states/events bidirectionally.
	SyncStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SyncStreamCommand, SyncStreamEvent], error)
	// Returns the current workspace setup.
	CurrentSetup(ctx context.Context, in *CurrentSetupRequest, opts ...grpc.CallOption) (*CurrentSetupResponse, error)
	// Issue a JWT token for the current user.
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
	// Retrieve credential for source control provider based on the current checkout path.
	SourceControlCredential(ctx context.Context, in *SourceControlCredentialRequest, opts ...grpc.CallOption) (*SourceControlCredentialResponse, error)
	// Use out container root to mount overlay filesystem to the user container.
	MountOverlay(ctx context.Context, in *MountOverlayRequest, opts ...grpc.CallOption) (*MountOverlayResponse, error)
	// Using the root user of out container to write file.
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	// Report jetbrains dev server status.
	ReportJetbrainsRemoteDevServerStatus(ctx context.Context, in *ReportJetbrainsRemoteDevServerStatusRequest, opts ...grpc.CallOption) (*ReportJetbrainsRemoteDevServerStatusResponse, error)
}

type workspaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceServiceClient(cc grpc.ClientConnInterface) WorkspaceServiceClient {
	return &workspaceServiceClient{cc}
}

func (c *workspaceServiceClient) SyncStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SyncStreamCommand, SyncStreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspaceService_ServiceDesc.Streams[0], WorkspaceService_SyncStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncStreamCommand, SyncStreamEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceService_SyncStreamClient = grpc.BidiStreamingClient[SyncStreamCommand, SyncStreamEvent]

func (c *workspaceServiceClient) CurrentSetup(ctx context.Context, in *CurrentSetupRequest, opts ...grpc.CallOption) (*CurrentSetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrentSetupResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_CurrentSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_IssueToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) SourceControlCredential(ctx context.Context, in *SourceControlCredentialRequest, opts ...grpc.CallOption) (*SourceControlCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceControlCredentialResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_SourceControlCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) MountOverlay(ctx context.Context, in *MountOverlayRequest, opts ...grpc.CallOption) (*MountOverlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountOverlayResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_MountOverlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ReportJetbrainsRemoteDevServerStatus(ctx context.Context, in *ReportJetbrainsRemoteDevServerStatusRequest, opts ...grpc.CallOption) (*ReportJetbrainsRemoteDevServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportJetbrainsRemoteDevServerStatusResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_ReportJetbrainsRemoteDevServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceServiceServer is the server API for WorkspaceService service.
// All implementations must embed UnimplementedWorkspaceServiceServer
// for forward compatibility.
//
// The service is exposed into the user container when the workload is running
// as a workspace.
type WorkspaceServiceServer interface {
	// A long-running stream syncing states/events bidirectionally.
	SyncStream(grpc.BidiStreamingServer[SyncStreamCommand, SyncStreamEvent]) error
	// Returns the current workspace setup.
	CurrentSetup(context.Context, *CurrentSetupRequest) (*CurrentSetupResponse, error)
	// Issue a JWT token for the current user.
	IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	// Retrieve credential for source control provider based on the current checkout path.
	SourceControlCredential(context.Context, *SourceControlCredentialRequest) (*SourceControlCredentialResponse, error)
	// Use out container root to mount overlay filesystem to the user container.
	MountOverlay(context.Context, *MountOverlayRequest) (*MountOverlayResponse, error)
	// Using the root user of out container to write file.
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	// Report jetbrains dev server status.
	ReportJetbrainsRemoteDevServerStatus(context.Context, *ReportJetbrainsRemoteDevServerStatusRequest) (*ReportJetbrainsRemoteDevServerStatusResponse, error)
	mustEmbedUnimplementedWorkspaceServiceServer()
}

// UnimplementedWorkspaceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceServiceServer struct{}

func (UnimplementedWorkspaceServiceServer) SyncStream(grpc.BidiStreamingServer[SyncStreamCommand, SyncStreamEvent]) error {
	return status.Error(codes.Unimplemented, "method SyncStream not implemented")
}
func (UnimplementedWorkspaceServiceServer) CurrentSetup(context.Context, *CurrentSetupRequest) (*CurrentSetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CurrentSetup not implemented")
}
func (UnimplementedWorkspaceServiceServer) IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedWorkspaceServiceServer) SourceControlCredential(context.Context, *SourceControlCredentialRequest) (*SourceControlCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SourceControlCredential not implemented")
}
func (UnimplementedWorkspaceServiceServer) MountOverlay(context.Context, *MountOverlayRequest) (*MountOverlayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MountOverlay not implemented")
}
func (UnimplementedWorkspaceServiceServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedWorkspaceServiceServer) ReportJetbrainsRemoteDevServerStatus(context.Context, *ReportJetbrainsRemoteDevServerStatusRequest) (*ReportJetbrainsRemoteDevServerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportJetbrainsRemoteDevServerStatus not implemented")
}
func (UnimplementedWorkspaceServiceServer) mustEmbedUnimplementedWorkspaceServiceServer() {}
func (UnimplementedWorkspaceServiceServer) testEmbeddedByValue()                          {}

// UnsafeWorkspaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceServiceServer will
// result in compilation errors.
type UnsafeWorkspaceServiceServer interface {
	mustEmbedUnimplementedWorkspaceServiceServer()
}

func RegisterWorkspaceServiceServer(s grpc.ServiceRegistrar, srv WorkspaceServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkspaceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceService_ServiceDesc, srv)
}

func _WorkspaceService_SyncStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkspaceServiceServer).SyncStream(&grpc.GenericServerStream[SyncStreamCommand, SyncStreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceService_SyncStreamServer = grpc.BidiStreamingServer[SyncStreamCommand, SyncStreamEvent]

func _WorkspaceService_CurrentSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).CurrentSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_CurrentSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).CurrentSetup(ctx, req.(*CurrentSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_SourceControlCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SourceControlCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).SourceControlCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_SourceControlCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).SourceControlCredential(ctx, req.(*SourceControlCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_MountOverlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountOverlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).MountOverlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_MountOverlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).MountOverlay(ctx, req.(*MountOverlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ReportJetbrainsRemoteDevServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportJetbrainsRemoteDevServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ReportJetbrainsRemoteDevServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ReportJetbrainsRemoteDevServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ReportJetbrainsRemoteDevServerStatus(ctx, req.(*ReportJetbrainsRemoteDevServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceService_ServiceDesc is the grpc.ServiceDesc for WorkspaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandboxes.api.v1.WorkspaceService",
	HandlerType: (*WorkspaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CurrentSetup",
			Handler:    _WorkspaceService_CurrentSetup_Handler,
		},
		{
			MethodName: "IssueToken",
			Handler:    _WorkspaceService_IssueToken_Handler,
		},
		{
			MethodName: "SourceControlCredential",
			Handler:    _WorkspaceService_SourceControlCredential_Handler,
		},
		{
			MethodName: "MountOverlay",
			Handler:    _WorkspaceService_MountOverlay_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _WorkspaceService_WriteFile_Handler,
		},
		{
			MethodName: "ReportJetbrainsRemoteDevServerStatus",
			Handler:    _WorkspaceService_ReportJetbrainsRemoteDevServerStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncStream",
			Handler:       _WorkspaceService_SyncStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sandboxes/api/v1/workspaceservice.proto",
}
