// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sandboxes/api/v1/workspaceservice.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncStreamCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStreamCommand) Reset() {
	*x = SyncStreamCommand{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStreamCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStreamCommand) ProtoMessage() {}

func (x *SyncStreamCommand) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStreamCommand.ProtoReflect.Descriptor instead.
func (*SyncStreamCommand) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{0}
}

type SyncStreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SyncStreamEvent_Setup
	Event         isSyncStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStreamEvent) Reset() {
	*x = SyncStreamEvent{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStreamEvent) ProtoMessage() {}

func (x *SyncStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStreamEvent.ProtoReflect.Descriptor instead.
func (*SyncStreamEvent) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{1}
}

func (x *SyncStreamEvent) GetEvent() isSyncStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SyncStreamEvent) GetSetup() *Setup {
	if x != nil {
		if x, ok := x.Event.(*SyncStreamEvent_Setup); ok {
			return x.Setup
		}
	}
	return nil
}

type isSyncStreamEvent_Event interface {
	isSyncStreamEvent_Event()
}

type SyncStreamEvent_Setup struct {
	Setup *Setup `protobuf:"bytes,1,opt,name=setup,proto3,oneof"`
}

func (*SyncStreamEvent_Setup) isSyncStreamEvent_Event() {}

type CurrentSetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentSetupRequest) Reset() {
	*x = CurrentSetupRequest{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentSetupRequest) ProtoMessage() {}

func (x *CurrentSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentSetupRequest.ProtoReflect.Descriptor instead.
func (*CurrentSetupRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{2}
}

type CurrentSetupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setup         *Setup                 `protobuf:"bytes,1,opt,name=setup,proto3" json:"setup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentSetupResponse) Reset() {
	*x = CurrentSetupResponse{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentSetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentSetupResponse) ProtoMessage() {}

func (x *CurrentSetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentSetupResponse.ProtoReflect.Descriptor instead.
func (*CurrentSetupResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{3}
}

func (x *CurrentSetupResponse) GetSetup() *Setup {
	if x != nil {
		return x.Setup
	}
	return nil
}

type IssueTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *TokenSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{4}
}

func (x *IssueTokenRequest) GetSpec() *TokenSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type IssueTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{5}
}

func (x *IssueTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SourceControlCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The absolute directory of a checkout, or subdirectories inside a checkout.
	CheckoutPath  string `protobuf:"bytes,1,opt,name=checkout_path,json=checkoutPath,proto3" json:"checkout_path,omitempty"`
	RemoteUrl     string `protobuf:"bytes,2,opt,name=remote_url,json=remoteUrl,proto3" json:"remote_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceControlCredentialRequest) Reset() {
	*x = SourceControlCredentialRequest{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceControlCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceControlCredentialRequest) ProtoMessage() {}

func (x *SourceControlCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceControlCredentialRequest.ProtoReflect.Descriptor instead.
func (*SourceControlCredentialRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{6}
}

func (x *SourceControlCredentialRequest) GetCheckoutPath() string {
	if x != nil {
		return x.CheckoutPath
	}
	return ""
}

func (x *SourceControlCredentialRequest) GetRemoteUrl() string {
	if x != nil {
		return x.RemoteUrl
	}
	return ""
}

type SourceControlCredentialResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Credential    *SourceControlCredential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceControlCredentialResponse) Reset() {
	*x = SourceControlCredentialResponse{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceControlCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceControlCredentialResponse) ProtoMessage() {}

func (x *SourceControlCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceControlCredentialResponse.ProtoReflect.Descriptor instead.
func (*SourceControlCredentialResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{7}
}

func (x *SourceControlCredentialResponse) GetCredential() *SourceControlCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type MountOverlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mountpoint    string                 `protobuf:"bytes,1,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Options       string                 `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountOverlayRequest) Reset() {
	*x = MountOverlayRequest{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountOverlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountOverlayRequest) ProtoMessage() {}

func (x *MountOverlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountOverlayRequest.ProtoReflect.Descriptor instead.
func (*MountOverlayRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{8}
}

func (x *MountOverlayRequest) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *MountOverlayRequest) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

type MountOverlayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountOverlayResponse) Reset() {
	*x = MountOverlayResponse{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountOverlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountOverlayResponse) ProtoMessage() {}

func (x *MountOverlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountOverlayResponse.ProtoReflect.Descriptor instead.
func (*MountOverlayResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{9}
}

// The WriteFileRequest will overwrite/create the file with speicfied data.
type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The file path
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Create the file if not exists.
	CreateIfNotExists bool `protobuf:"varint,2,opt,name=create_if_not_exists,json=createIfNotExists,proto3" json:"create_if_not_exists,omitempty"`
	// When `create_if_not_exists` enabled, creating file with this permission mode. Eg. 0755
	Mode uint32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// The data.
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{10}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetCreateIfNotExists() bool {
	if x != nil {
		return x.CreateIfNotExists
	}
	return false
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{11}
}

// Request of reporting the jetbrains dev server.
type ReportJetbrainsRemoteDevServerStatusRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Servers       []*JetbrainsRemoteDevServerStatus `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJetbrainsRemoteDevServerStatusRequest) Reset() {
	*x = ReportJetbrainsRemoteDevServerStatusRequest{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJetbrainsRemoteDevServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJetbrainsRemoteDevServerStatusRequest) ProtoMessage() {}

func (x *ReportJetbrainsRemoteDevServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJetbrainsRemoteDevServerStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportJetbrainsRemoteDevServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{12}
}

func (x *ReportJetbrainsRemoteDevServerStatusRequest) GetServers() []*JetbrainsRemoteDevServerStatus {
	if x != nil {
		return x.Servers
	}
	return nil
}

// Response of reporting the jetbrains dev server.
type ReportJetbrainsRemoteDevServerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJetbrainsRemoteDevServerStatusResponse) Reset() {
	*x = ReportJetbrainsRemoteDevServerStatusResponse{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJetbrainsRemoteDevServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJetbrainsRemoteDevServerStatusResponse) ProtoMessage() {}

func (x *ReportJetbrainsRemoteDevServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJetbrainsRemoteDevServerStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportJetbrainsRemoteDevServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{13}
}

// The jetbrains remote dev server status.
type JetbrainsRemoteDevServerStatus struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	IdeCode    string                 `protobuf:"bytes,1,opt,name=ide_code,json=ideCode,proto3" json:"ide_code,omitempty"`
	IdeVersion string                 `protobuf:"bytes,2,opt,name=ide_version,json=ideVersion,proto3" json:"ide_version,omitempty"`
	// The timestamp when the jetbrains dev server receives the last activity.
	LastActivityReceivedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_activity_received_at,json=lastActivityReceivedAt,proto3" json:"last_activity_received_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *JetbrainsRemoteDevServerStatus) Reset() {
	*x = JetbrainsRemoteDevServerStatus{}
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JetbrainsRemoteDevServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JetbrainsRemoteDevServerStatus) ProtoMessage() {}

func (x *JetbrainsRemoteDevServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxes_api_v1_workspaceservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JetbrainsRemoteDevServerStatus.ProtoReflect.Descriptor instead.
func (*JetbrainsRemoteDevServerStatus) Descriptor() ([]byte, []int) {
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP(), []int{14}
}

func (x *JetbrainsRemoteDevServerStatus) GetIdeCode() string {
	if x != nil {
		return x.IdeCode
	}
	return ""
}

func (x *JetbrainsRemoteDevServerStatus) GetIdeVersion() string {
	if x != nil {
		return x.IdeVersion
	}
	return ""
}

func (x *JetbrainsRemoteDevServerStatus) GetLastActivityReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivityReceivedAt
	}
	return nil
}

var File_sandboxes_api_v1_workspaceservice_proto protoreflect.FileDescriptor

const file_sandboxes_api_v1_workspaceservice_proto_rawDesc = "" +
	"\n" +
	"'sandboxes/api/v1/workspaceservice.proto\x12\x10sandboxes.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fsandboxes/api/v1/workload.proto\x1a\x1asandboxes/api/v1/org.proto\x1a\x1esandboxes/api/v1/process.proto\x1a-sandboxes/api/v1/resource_sourcecontrol.proto\"\x13\n" +
	"\x11SyncStreamCommand\"K\n" +
	"\x0fSyncStreamEvent\x12/\n" +
	"\x05setup\x18\x01 \x01(\v2\x17.sandboxes.api.v1.SetupH\x00R\x05setupB\a\n" +
	"\x05event\"\x15\n" +
	"\x13CurrentSetupRequest\"E\n" +
	"\x14CurrentSetupResponse\x12-\n" +
	"\x05setup\x18\x01 \x01(\v2\x17.sandboxes.api.v1.SetupR\x05setup\"D\n" +
	"\x11IssueTokenRequest\x12/\n" +
	"\x04spec\x18\x01 \x01(\v2\x1b.sandboxes.api.v1.TokenSpecR\x04spec\"*\n" +
	"\x12IssueTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"d\n" +
	"\x1eSourceControlCredentialRequest\x12#\n" +
	"\rcheckout_path\x18\x01 \x01(\tR\fcheckoutPath\x12\x1d\n" +
	"\n" +
	"remote_url\x18\x02 \x01(\tR\tremoteUrl\"l\n" +
	"\x1fSourceControlCredentialResponse\x12I\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2).sandboxes.api.v1.SourceControlCredentialR\n" +
	"credential\"O\n" +
	"\x13MountOverlayRequest\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x01 \x01(\tR\n" +
	"mountpoint\x12\x18\n" +
	"\aoptions\x18\x02 \x01(\tR\aoptions\"\x16\n" +
	"\x14MountOverlayResponse\"\x7f\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12/\n" +
	"\x14create_if_not_exists\x18\x02 \x01(\bR\x11createIfNotExists\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x13\n" +
	"\x11WriteFileResponse\"y\n" +
	"+ReportJetbrainsRemoteDevServerStatusRequest\x12J\n" +
	"\aservers\x18\x01 \x03(\v20.sandboxes.api.v1.JetbrainsRemoteDevServerStatusR\aservers\".\n" +
	",ReportJetbrainsRemoteDevServerStatusResponse\"\xb3\x01\n" +
	"\x1eJetbrainsRemoteDevServerStatus\x12\x19\n" +
	"\bide_code\x18\x01 \x01(\tR\aideCode\x12\x1f\n" +
	"\vide_version\x18\x02 \x01(\tR\n" +
	"ideVersion\x12U\n" +
	"\x19last_activity_received_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x16lastActivityReceivedAt2\x81\x06\n" +
	"\x10WorkspaceService\x12X\n" +
	"\n" +
	"SyncStream\x12#.sandboxes.api.v1.SyncStreamCommand\x1a!.sandboxes.api.v1.SyncStreamEvent(\x010\x01\x12]\n" +
	"\fCurrentSetup\x12%.sandboxes.api.v1.CurrentSetupRequest\x1a&.sandboxes.api.v1.CurrentSetupResponse\x12W\n" +
	"\n" +
	"IssueToken\x12#.sandboxes.api.v1.IssueTokenRequest\x1a$.sandboxes.api.v1.IssueTokenResponse\x12~\n" +
	"\x17SourceControlCredential\x120.sandboxes.api.v1.SourceControlCredentialRequest\x1a1.sandboxes.api.v1.SourceControlCredentialResponse\x12]\n" +
	"\fMountOverlay\x12%.sandboxes.api.v1.MountOverlayRequest\x1a&.sandboxes.api.v1.MountOverlayResponse\x12T\n" +
	"\tWriteFile\x12\".sandboxes.api.v1.WriteFileRequest\x1a#.sandboxes.api.v1.WriteFileResponse\x12\xa5\x01\n" +
	"$ReportJetbrainsRemoteDevServerStatus\x12=.sandboxes.api.v1.ReportJetbrainsRemoteDevServerStatusRequest\x1a>.sandboxes.api.v1.ReportJetbrainsRemoteDevServerStatusResponseB?Z=pkg.crafting.dev/sandbox/protos/gen/go/proto/sandboxes/api/v1b\x06proto3"

var (
	file_sandboxes_api_v1_workspaceservice_proto_rawDescOnce sync.Once
	file_sandboxes_api_v1_workspaceservice_proto_rawDescData []byte
)

func file_sandboxes_api_v1_workspaceservice_proto_rawDescGZIP() []byte {
	file_sandboxes_api_v1_workspaceservice_proto_rawDescOnce.Do(func() {
		file_sandboxes_api_v1_workspaceservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_workspaceservice_proto_rawDesc), len(file_sandboxes_api_v1_workspaceservice_proto_rawDesc)))
	})
	return file_sandboxes_api_v1_workspaceservice_proto_rawDescData
}

var file_sandboxes_api_v1_workspaceservice_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_sandboxes_api_v1_workspaceservice_proto_goTypes = []any{
	(*SyncStreamCommand)(nil),                            // 0: sandboxes.api.v1.SyncStreamCommand
	(*SyncStreamEvent)(nil),                              // 1: sandboxes.api.v1.SyncStreamEvent
	(*CurrentSetupRequest)(nil),                          // 2: sandboxes.api.v1.CurrentSetupRequest
	(*CurrentSetupResponse)(nil),                         // 3: sandboxes.api.v1.CurrentSetupResponse
	(*IssueTokenRequest)(nil),                            // 4: sandboxes.api.v1.IssueTokenRequest
	(*IssueTokenResponse)(nil),                           // 5: sandboxes.api.v1.IssueTokenResponse
	(*SourceControlCredentialRequest)(nil),               // 6: sandboxes.api.v1.SourceControlCredentialRequest
	(*SourceControlCredentialResponse)(nil),              // 7: sandboxes.api.v1.SourceControlCredentialResponse
	(*MountOverlayRequest)(nil),                          // 8: sandboxes.api.v1.MountOverlayRequest
	(*MountOverlayResponse)(nil),                         // 9: sandboxes.api.v1.MountOverlayResponse
	(*WriteFileRequest)(nil),                             // 10: sandboxes.api.v1.WriteFileRequest
	(*WriteFileResponse)(nil),                            // 11: sandboxes.api.v1.WriteFileResponse
	(*ReportJetbrainsRemoteDevServerStatusRequest)(nil),  // 12: sandboxes.api.v1.ReportJetbrainsRemoteDevServerStatusRequest
	(*ReportJetbrainsRemoteDevServerStatusResponse)(nil), // 13: sandboxes.api.v1.ReportJetbrainsRemoteDevServerStatusResponse
	(*JetbrainsRemoteDevServerStatus)(nil),               // 14: sandboxes.api.v1.JetbrainsRemoteDevServerStatus
	(*Setup)(nil),                                        // 15: sandboxes.api.v1.Setup
	(*TokenSpec)(nil),                                    // 16: sandboxes.api.v1.TokenSpec
	(*SourceControlCredential)(nil),                      // 17: sandboxes.api.v1.SourceControlCredential
	(*timestamppb.Timestamp)(nil),                        // 18: google.protobuf.Timestamp
}
var file_sandboxes_api_v1_workspaceservice_proto_depIdxs = []int32{
	15, // 0: sandboxes.api.v1.SyncStreamEvent.setup:type_name -> sandboxes.api.v1.Setup
	15, // 1: sandboxes.api.v1.CurrentSetupResponse.setup:type_name -> sandboxes.api.v1.Setup
	16, // 2: sandboxes.api.v1.IssueTokenRequest.spec:type_name -> sandboxes.api.v1.TokenSpec
	17, // 3: sandboxes.api.v1.SourceControlCredentialResponse.credential:type_name -> sandboxes.api.v1.SourceControlCredential
	14, // 4: sandboxes.api.v1.ReportJetbrainsRemoteDevServerStatusRequest.servers:type_name -> sandboxes.api.v1.JetbrainsRemoteDevServerStatus
	18, // 5: sandboxes.api.v1.JetbrainsRemoteDevServerStatus.last_activity_received_at:type_name -> google.protobuf.Timestamp
	0,  // 6: sandboxes.api.v1.WorkspaceService.SyncStream:input_type -> sandboxes.api.v1.SyncStreamCommand
	2,  // 7: sandboxes.api.v1.WorkspaceService.CurrentSetup:input_type -> sandboxes.api.v1.CurrentSetupRequest
	4,  // 8: sandboxes.api.v1.WorkspaceService.IssueToken:input_type -> sandboxes.api.v1.IssueTokenRequest
	6,  // 9: sandboxes.api.v1.WorkspaceService.SourceControlCredential:input_type -> sandboxes.api.v1.SourceControlCredentialRequest
	8,  // 10: sandboxes.api.v1.WorkspaceService.MountOverlay:input_type -> sandboxes.api.v1.MountOverlayRequest
	10, // 11: sandboxes.api.v1.WorkspaceService.WriteFile:input_type -> sandboxes.api.v1.WriteFileRequest
	12, // 12: sandboxes.api.v1.WorkspaceService.ReportJetbrainsRemoteDevServerStatus:input_type -> sandboxes.api.v1.ReportJetbrainsRemoteDevServerStatusRequest
	1,  // 13: sandboxes.api.v1.WorkspaceService.SyncStream:output_type -> sandboxes.api.v1.SyncStreamEvent
	3,  // 14: sandboxes.api.v1.WorkspaceService.CurrentSetup:output_type -> sandboxes.api.v1.CurrentSetupResponse
	5,  // 15: sandboxes.api.v1.WorkspaceService.IssueToken:output_type -> sandboxes.api.v1.IssueTokenResponse
	7,  // 16: sandboxes.api.v1.WorkspaceService.SourceControlCredential:output_type -> sandboxes.api.v1.SourceControlCredentialResponse
	9,  // 17: sandboxes.api.v1.WorkspaceService.MountOverlay:output_type -> sandboxes.api.v1.MountOverlayResponse
	11, // 18: sandboxes.api.v1.WorkspaceService.WriteFile:output_type -> sandboxes.api.v1.WriteFileResponse
	13, // 19: sandboxes.api.v1.WorkspaceService.ReportJetbrainsRemoteDevServerStatus:output_type -> sandboxes.api.v1.ReportJetbrainsRemoteDevServerStatusResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sandboxes_api_v1_workspaceservice_proto_init() }
func file_sandboxes_api_v1_workspaceservice_proto_init() {
	if File_sandboxes_api_v1_workspaceservice_proto != nil {
		return
	}
	file_sandboxes_api_v1_workload_proto_init()
	file_sandboxes_api_v1_org_proto_init()
	file_sandboxes_api_v1_process_proto_init()
	file_sandboxes_api_v1_resource_sourcecontrol_proto_init()
	file_sandboxes_api_v1_workspaceservice_proto_msgTypes[1].OneofWrappers = []any{
		(*SyncStreamEvent_Setup)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxes_api_v1_workspaceservice_proto_rawDesc), len(file_sandboxes_api_v1_workspaceservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandboxes_api_v1_workspaceservice_proto_goTypes,
		DependencyIndexes: file_sandboxes_api_v1_workspaceservice_proto_depIdxs,
		MessageInfos:      file_sandboxes_api_v1_workspaceservice_proto_msgTypes,
	}.Build()
	File_sandboxes_api_v1_workspaceservice_proto = out.File
	file_sandboxes_api_v1_workspaceservice_proto_goTypes = nil
	file_sandboxes_api_v1_workspaceservice_proto_depIdxs = nil
}
